<?php
declare(strict_types=1); namespace App\Repositories\ControlEscaneres\Pdo;
use App\Repositories\ControlEscaneres\Contracts\ScannerRepositoryInterface;use App\DTO\ControlEscaneres\{ScannerCreateData,ScannerUpdateData,ScannerFilterData};use App\Domain\ControlEscaneres\{Scanner,ScannerCode,ScannerStatus};use App\Exceptions\ControlEscaneres\{DuplicateScannerCodeException,DuplicateScannerIdentityException,PersistenceException};
final class PdoScannerRepository extends AbstractPdoRepository implements ScannerRepositoryInterface {
 private function map(array $r):Scanner{return new Scanner((int)$r['id'],new ScannerCode($r['codigo']),new ScannerStatus($r['estado']),(bool)$r['activo']);}
 private function one(string $sql,array $p):?Scanner{$r=$this->stmt($sql,$p)->fetch(\PDO::FETCH_ASSOC);return is_array($r)?$this->map($r):null;}
 public function findById(int $id):?Scanner{return $this->one('SELECT * FROM scanners WHERE id=:id',['id'=>$id]);}
 public function findByCode(ScannerCode $c):?Scanner{return $this->one('SELECT * FROM scanners WHERE codigo=:v',['v'=>$c->value]);}
 private function exists(string $column,string $v):bool{return(bool)$this->stmt("SELECT 1 FROM scanners WHERE {$column}=:v LIMIT 1",['v'=>$v])->fetchColumn();}
 public function existsByCode(ScannerCode $c):bool{return $this->exists('codigo',$c->value);}public function existsBySerial(string $v):bool{return $this->exists('numero_serie',$v);}public function existsByImei(string $v):bool{return $this->exists('imei',$v);}public function existsByIccid(string $v):bool{return $this->exists('iccid',$v);}
 public function create(ScannerCreateData $d,int $actor):Scanner{try{$this->stmt('INSERT INTO scanners(codigo,codigo_qr,marca,modelo,estado,numero_serie,imei,iccid,area_id,activo,created_by,updated_by) VALUES(:c,:q,:b,:m,:s,:n,:i,:x,:a,1,:u,:u)',['c'=>$d->code->value,'q'=>$d->qr,'b'=>$d->brand,'m'=>$d->model,'s'=>$d->status->value,'n'=>$d->serial,'i'=>$d->imei,'x'=>$d->iccid,'a'=>$d->areaId,'u'=>$actor]);}catch(PersistenceException $e){if($this->existsByCode($d->code))throw new DuplicateScannerCodeException('Código duplicado.',0,$e);throw new DuplicateScannerIdentityException('Identidad duplicada.',0,$e);}return $this->findById((int)$this->pdo->lastInsertId())??throw new PersistenceException('Alta sin resultado.');}
 public function update(int $id,ScannerUpdateData $d,int $actor):void{$this->stmt('UPDATE scanners SET codigo_qr=:q,marca=:b,modelo=:m,numero_serie=:n,imei=:i,iccid=:x,area_id=:a,updated_by=:u WHERE id=:id',['q'=>$d->qr,'b'=>$d->brand,'m'=>$d->model,'n'=>$d->serial,'i'=>$d->imei,'x'=>$d->iccid,'a'=>$d->areaId,'u'=>$actor,'id'=>$id]);}
 public function deactivate(int $id,int $actor):void{$this->stmt('UPDATE scanners SET activo=0,deactivated_at=CURRENT_TIMESTAMP,updated_by=:u WHERE id=:id',['u'=>$actor,'id'=>$id]);}
 public function changeStatus(int $id,ScannerStatus $s,int $actor):void{$this->stmt('UPDATE scanners SET estado=:s,updated_by=:u WHERE id=:id',['s'=>$s->value,'u'=>$actor,'id'=>$id]);}
 public function list(ScannerFilterData $f):array{$w=[];$p=[];if($f->active!==null){$w[]='activo=:active';$p['active']=(int)$f->active;}if($f->status!==null){$w[]='estado=:status';$p['status']=$f->status;}if($f->areaId!==null){$w[]='area_id=:area';$p['area']=$f->areaId;}if($f->search!==null){$w[]='(codigo LIKE :search OR marca LIKE :search OR modelo LIKE :search)';$p['search']='%'.$f->search.'%';}$sql='SELECT * FROM scanners'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY '.$f->orderBy.' '.$f->direction.' LIMIT '.(int)$f->perPage.' OFFSET '.(int)$f->offset();return array_map(fn($r)=>$this->map($r),$this->stmt($sql,$p)->fetchAll(\PDO::FETCH_ASSOC));}
 public function countByStatus(ScannerStatus $s):int{return(int)$this->stmt('SELECT COUNT(*) FROM scanners WHERE estado=:s',['s'=>$s->value])->fetchColumn();}
 public function lockScannerForUpdate(int $id):?Scanner{return $this->one('SELECT * FROM scanners WHERE id=:id'.$this->forUpdate(),['id'=>$id]);}
}
