<?php
declare(strict_types=1); namespace App\Repositories\ControlEscaneres\Pdo;
use App\Repositories\ControlEscaneres\Contracts\ScannerRepositoryInterface;use App\DTO\ControlEscaneres\{ScannerCreateData,ScannerUpdateData,ScannerFilterData};use App\Domain\ControlEscaneres\{Scanner,ScannerCode,ScannerStatus};use App\Exceptions\ControlEscaneres\{DuplicateScannerCodeException,DuplicateScannerIdentityException,PersistenceException};
final class PdoScannerRepository extends AbstractPdoRepository implements ScannerRepositoryInterface {
 private function map(array $r):Scanner{return new Scanner((int)$r['id'],new ScannerCode($r['codigo']),new ScannerStatus($r['estado']),(bool)$r['activo']);}
 private function one(string $sql,array $p):?Scanner{$r=$this->stmt($sql,$p)->fetch(\PDO::FETCH_ASSOC);return is_array($r)?$this->map($r):null;}
 public function findById(int $id):?Scanner{return $this->one('SELECT * FROM scanners WHERE id=:id',['id'=>$id]);}
 public function details(int$id):?array{$r=$this->stmt('SELECT s.*,ao.nombre area_organizacional_nombre FROM scanners s LEFT JOIN areas_organizacionales ao ON ao.id=s.area_organizacional_id WHERE s.id=:id',['id'=>$id])->fetch(\PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
 public function findByCode(ScannerCode $c):?Scanner{return $this->one('SELECT * FROM scanners WHERE codigo=:v',['v'=>$c->value]);}
 public function resolveIdentifier(string$value):?array{$value=trim($value);if($value==='')return null;$stmt=$this->stmt("SELECT id,codigo,estado,activo FROM scanners WHERE LOWER(codigo)=LOWER(:code) OR LOWER(codigo_qr)=LOWER(:qr) OR LOWER(tag_original)=LOWER(:tag) OR imei=:imei OR LOWER(numero_serie)=LOWER(:serial) ORDER BY CASE WHEN LOWER(codigo)=LOWER(:code_order) THEN 0 WHEN LOWER(codigo_qr)=LOWER(:qr_order) THEN 1 WHEN LOWER(tag_original)=LOWER(:tag_order) THEN 2 WHEN imei=:imei_order THEN 3 ELSE 4 END,id LIMIT 1",['code'=>$value,'qr'=>$value,'tag'=>$value,'imei'=>$value,'serial'=>$value,'code_order'=>$value,'qr_order'=>$value,'tag_order'=>$value,'imei_order'=>$value]);$row=$stmt->fetch(\PDO::FETCH_ASSOC);return is_array($row)?$row:null;}
 public function resolvePublicId(int$id):?array{if($id<1)return null;$row=$this->stmt('SELECT id,codigo,estado,activo FROM scanners WHERE id=:id LIMIT 1',['id'=>$id])->fetch(\PDO::FETCH_ASSOC);return is_array($row)?$row:null;}
 public function nextCode():ScannerCode{$n=(int)$this->stmt("SELECT COALESCE(MAX(CAST(SUBSTRING(codigo,4) AS UNSIGNED)),0)+1 FROM scanners WHERE codigo REGEXP '^SC-[0-9]{4,}$'")->fetchColumn();return new ScannerCode('SC-'.str_pad((string)$n,4,'0',STR_PAD_LEFT));}
 private function exists(string $column,string $v):bool{return(bool)$this->stmt("SELECT 1 FROM scanners WHERE {$column}=:v LIMIT 1",['v'=>$v])->fetchColumn();}
 public function existsByCode(ScannerCode $c):bool{return $this->exists('codigo',$c->value);}public function existsBySerial(string $v):bool{return $this->exists('numero_serie',$v);}public function existsByImei(string $v):bool{return $this->exists('imei',$v);}public function existsByIccid(string $v):bool{return $this->exists('iccid',$v);}
 public function create(ScannerCreateData $d,int $actor):Scanner{try{$this->stmt('INSERT INTO scanners(codigo,codigo_qr,tag_original,marca,modelo,estado,numero_serie,imei,telefono,iccid,red,plan,actividad_habitual,area_habitual,ubicacion,antiguedad_descriptiva,observaciones,fotografia_principal,area_id,activo,created_by,updated_by) VALUES(:c,:q,:tag,:b,:m,:s,:n,:i,:phone,:x,:network,:plan,:activity,:area,:location,:age,:observations,:photo,:area_id,:active,:created_by,:updated_by)',['c'=>$d->code->value,'q'=>$d->qr,'tag'=>$d->tag,'b'=>$d->brand,'m'=>$d->model,'s'=>$d->status->value,'n'=>$d->serial,'i'=>$d->imei,'phone'=>$d->phone,'x'=>$d->iccid,'network'=>$d->network,'plan'=>$d->plan,'activity'=>$d->activity,'area'=>$d->area,'location'=>$d->location,'age'=>$d->age,'observations'=>$d->observations,'photo'=>$d->mainPhoto,'area_id'=>$d->areaId,'active'=>(int)$d->active,'created_by'=>$actor,'updated_by'=>$actor]);}catch(PersistenceException $e){$previous=$e->getPrevious();if(!$previous instanceof \PDOException||!in_array((string)$previous->getCode(),['23000','19'],true))throw$e;if($this->existsByCode($d->code))throw new DuplicateScannerCodeException('El código capturado ya está registrado.',0,$e);if($d->tag!==null&&$this->exists('tag_original',$d->tag))throw new DuplicateScannerIdentityException('El TAG capturado ya está registrado.',0,$e);throw new DuplicateScannerIdentityException('La identidad del escáner ya pertenece a otro registro.',0,$e);}return $this->findById((int)$this->pdo->lastInsertId())??throw new PersistenceException('No fue posible recuperar el escáner registrado.');}
 public function update(int $id,ScannerUpdateData $d,int $actor):void{$this->stmt('UPDATE scanners SET codigo_qr=:q,marca=:b,modelo=:m,numero_serie=:n,imei=:i,iccid=:x,area_id=:a,updated_by=:u WHERE id=:id',['q'=>$d->qr,'b'=>$d->brand,'m'=>$d->model,'n'=>$d->serial,'i'=>$d->imei,'x'=>$d->iccid,'a'=>$d->areaId,'u'=>$actor,'id'=>$id]);}
 public function updateFull(int$id,array$d,int$actor):void{$areaId=null;if($d['area']!==null){$sql=$this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME)==='sqlite'?'INSERT OR IGNORE INTO scanner_areas(nombre,activo)VALUES(:name,1)':'INSERT INTO scanner_areas(nombre,activo)VALUES(:name,1) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre)';$this->stmt($sql,['name'=>$d['area']]);$areaId=(int)$this->stmt('SELECT id FROM scanner_areas WHERE nombre=:name',['name'=>$d['area']])->fetchColumn();}$this->stmt('UPDATE scanners SET tag_original=:tag,marca=:brand,modelo=:model,numero_serie=:serial,imei=:imei,telefono=:phone,iccid=:iccid,red=:network,plan=:plan,actividad_habitual=:activity,area_habitual=:area,area_id=:area_id,ubicacion=:location,antiguedad_descriptiva=:age,observaciones=:observations,updated_by=:actor WHERE id=:id',['tag'=>$d['tag'],'brand'=>$d['brand'],'model'=>$d['model'],'serial'=>$d['serial'],'imei'=>$d['imei'],'phone'=>$d['phone'],'iccid'=>$d['iccid'],'network'=>$d['network'],'plan'=>$d['plan'],'activity'=>$d['activity'],'area'=>$d['area'],'area_id'=>$areaId?:null,'location'=>$d['location'],'age'=>$d['age'],'observations'=>$d['observations'],'actor'=>$actor,'id'=>$id]);}
 public function organizationalAreas():array{return$this->stmt('SELECT id,clave,nombre FROM areas_organizacionales WHERE activo=1 ORDER BY nombre')->fetchAll(\PDO::FETCH_ASSOC);}
 public function setOrganizationalArea(int$id,?int$areaId,int$actor):void{$scanner=$this->stmt('SELECT activo FROM scanners WHERE id=:id',['id'=>$id])->fetchColumn();if($scanner===false)throw new\DomainException('Escáner no encontrado.');if((bool)$scanner&&$areaId===null)throw new\DomainException('El área organizacional propietaria es obligatoria para un escáner activo.');if($areaId!==null){$valid=$this->stmt('SELECT 1 FROM areas_organizacionales WHERE id=:id AND activo=1',['id'=>$areaId])->fetchColumn();if($valid===false)throw new\DomainException('Área organizacional inactiva o inexistente.');}$this->stmt('UPDATE scanners SET area_organizacional_id=:area,updated_by=:actor WHERE id=:id',['area'=>$areaId,'actor'=>$actor,'id'=>$id]);}
 public function setMainPhoto(int$id,string$path,int$actor):void{$this->stmt('UPDATE scanners SET fotografia_principal=:path,updated_by=:actor WHERE id=:id',['path'=>$path,'actor'=>$actor,'id'=>$id]);}
 public function assertIdentityAvailable(int$id,?string$tag,?string$serial,?string$imei,?string$iccid):void{foreach(['tag_original'=>$tag,'numero_serie'=>$serial,'imei'=>$imei,'iccid'=>$iccid]as$column=>$value){if($value===null)continue;$found=$this->stmt("SELECT id FROM scanners WHERE {$column}=:value AND id<>:id LIMIT 1",['value'=>$value,'id'=>$id])->fetchColumn();if($found!==false)throw new DuplicateScannerIdentityException($column==='tag_original'?'El TAG capturado ya está registrado.':'La identidad del escáner ya pertenece a otro registro.');}}
 public function deactivate(int $id,int $actor):void{$current=$this->findById($id);$this->stmt('UPDATE scanners SET activo=0,deactivated_at=CURRENT_TIMESTAMP,deleted_at=CURRENT_TIMESTAMP,updated_by=:u WHERE id=:id',['u'=>$actor,'id'=>$id]);if($current!==null)$this->history($id,$current->status->value,$current->status->value,'baja_logica',$actor);}
 public function reactivate(int$id,int$actor):void{$current=$this->findById($id);$this->stmt('UPDATE scanners SET activo=1,deactivated_at=NULL,deleted_at=NULL,updated_by=:u WHERE id=:id',['u'=>$actor,'id'=>$id]);if($current!==null)$this->history($id,$current->status->value,$current->status->value,'reactivacion',$actor);}
 public function changeStatus(int $id,ScannerStatus $s,int$actor):void{$current=$this->findById($id);$this->stmt('UPDATE scanners SET estado=:s,updated_by=:u WHERE id=:id',['s'=>$s->value,'u'=>$actor,'id'=>$id]);if($current!==null&&$current->status->value!==$s->value)$this->history($id,$current->status->value,$s->value,'cambio_estado',$actor);}
 private function history(int$id,?string$before,string$after,string$reason,int$actor):void{$this->stmt('INSERT INTO scanner_estado_historial(scanner_id,estado_anterior,estado_nuevo,motivo,entidad_origen,registrado_por)VALUES(:id,:before,:after,:reason,\'scanner_repository\',:actor)',['id'=>$id,'before'=>$before,'after'=>$after,'reason'=>$reason,'actor'=>$actor]);}
 public function list(ScannerFilterData $f):array{$w=[];$p=[];if($f->active!==null){$w[]='activo=:active';$p['active']=(int)$f->active;}if($f->status!==null){$w[]='estado=:status';$p['status']=$f->status;}if($f->areaId!==null){$w[]='area_id=:area';$p['area']=$f->areaId;}if($f->search!==null){$w[]='(codigo LIKE :search OR marca LIKE :search OR modelo LIKE :search)';$p['search']='%'.$f->search.'%';}$sql='SELECT * FROM scanners'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY '.$f->orderBy.' '.$f->direction.' LIMIT '.(int)$f->perPage.' OFFSET '.(int)$f->offset();return array_map(fn($r)=>$this->map($r),$this->stmt($sql,$p)->fetchAll(\PDO::FETCH_ASSOC));}
 public function countByStatus(ScannerStatus $s):int{return(int)$this->stmt('SELECT COUNT(*) FROM scanners WHERE estado=:s',['s'=>$s->value])->fetchColumn();}
 public function lockScannerForUpdate(int $id):?Scanner{return $this->one('SELECT * FROM scanners WHERE id=:id'.$this->forUpdate(),['id'=>$id]);}
}
