<?php
declare(strict_types=1);
namespace App\Services;

use App\Repositories\{AuthRepository,UserAdminRepository};

final class UserAdminService
{
    public function __construct(private UserAdminRepository$users,private AuthRepository$auth,private GeneralAuditService$audit,private ?\App\Repositories\OrganizationalAdminRepository$organizational=null){}
    public function create(array$input,int$actor):int{$d=$this->validate($input,true);return$this->transaction(function()use($d,$actor){$this->assertRoles($d['role_ids']);$this->assertOrganizational($d);$dup=$this->users->duplicate($d['usuario'],$d['numero_empleado'],$d['correo']);if($dup)throw new \DomainException('El '.$dup.' ya está registrado.');$id=$this->users->insert($d,$actor);$this->users->replaceRoles($id,$d['role_ids'],$actor);if($this->organizational){$this->users->replaceAreas($id,$d['area_ids'],$d['principal_area_id'],$actor);$this->users->replaceModuleExceptions($id,$d['module_allow_ids'],$d['module_deny_ids'],$actor);$this->auditOrganizationalChanges($id,[], $d,$actor);}$this->audit->record($actor,'usuario.crear','usuario',$id,'exito',[],['roles'=>$d['role_ids'],'areas'=>$d['area_ids'],'area_principal'=>$d['principal_area_id'],'modulos_permitidos'=>$d['module_allow_ids'],'modulos_denegados'=>$d['module_deny_ids'],'activo'=>$d['activo']]);return$id;});}
    public function update(int$id,array$input,int$actor):void{$d=$this->validate($input,false);$this->transaction(function()use($id,$d,$actor){$before=$this->required($id);$this->assertRoles($d['role_ids']);$this->assertOrganizational($d);if((!$d['activo']||$this->losesAdministration($d['role_ids']))&&$this->users->activeAdministratorsExcluding($id)===0)throw new \DomainException('No se puede dejar el sistema sin un administrador activo.');$dup=$this->users->duplicate((string)$before['usuario'],$d['numero_empleado'],$d['correo'],$id);if($dup)throw new \DomainException('El '.$dup.' ya está registrado.');$this->users->update($id,$d,$actor);$this->users->replaceRoles($id,$d['role_ids'],$actor);if($this->organizational){$this->users->replaceAreas($id,$d['area_ids'],$d['principal_area_id'],$actor);$this->users->replaceModuleExceptions($id,$d['module_allow_ids'],$d['module_deny_ids'],$actor);$this->auditOrganizationalChanges($id,$before,$d,$actor);}if(!$d['activo'])$this->auth->revokeAll($id,$actor,'usuario_desactivado');$this->audit->record($actor,'usuario.editar','usuario',$id,'exito',['activo'=>(bool)$before['activo'],'roles'=>$before['role_ids'],'areas'=>$before['area_ids']??[],'area_principal'=>$before['principal_area_id']??null,'modulos_permitidos'=>$before['module_allow_ids']??[],'modulos_denegados'=>$before['module_deny_ids']??[]],['activo'=>$d['activo'],'roles'=>$d['role_ids'],'areas'=>$d['area_ids'],'area_principal'=>$d['principal_area_id'],'modulos_permitidos'=>$d['module_allow_ids'],'modulos_denegados'=>$d['module_deny_ids']]);});}
    public function setActive(int$id,bool$active,int$actor):void{$this->transaction(function()use($id,$active,$actor){$before=$this->required($id);if(!$active&&$this->users->activeAdministratorsExcluding($id)===0)throw new \DomainException('No se puede desactivar al último administrador activo.');$this->users->setActive($id,$active,$actor);if(!$active)$this->auth->revokeAll($id,$actor,'usuario_desactivado');$this->audit->record($actor,$active?'usuario.activar':'usuario.desactivar','usuario',$id,'exito',['activo'=>(bool)$before['activo']],['activo'=>$active]);});}
    public function resetPassword(int$id,string$password,string$confirmation,int$actor):void{$this->password($password,$confirmation);$this->transaction(function()use($id,$password,$actor){$this->required($id);$this->users->setPassword($id,password_hash($password,PASSWORD_DEFAULT),$actor);$this->auth->revokeAll($id,$actor,'password_restablecido');$this->audit->record($actor,'usuario.password_restablecer','usuario',$id,'exito');});}
    private function validate(array$i,bool$creating):array{$name=trim((string)($i['nombre']??''));$employee=strtoupper(trim((string)($i['numero_empleado']??'')));$user=mb_strtolower(trim((string)($i['usuario']??'')));$email=mb_strtolower(trim((string)($i['correo']??'')));$email=$email===''?null:$email;$roles=$this->ids((array)($i['role_ids']??[]));$principal=(int)($i['principal_area_id']??0);$areas=$this->ids([...((array)($i['area_ids']??[])),...($principal>0?[$principal]:[])]);$allow=$this->ids((array)($i['module_allow_ids']??[]));$deny=$this->ids((array)($i['module_deny_ids']??[]));if($name===''||mb_strlen($name)>150)throw new \DomainException('Nombre inválido.');if($employee===''||mb_strlen($employee)>40)throw new \DomainException('Número de empleado inválido.');if($creating&&(!preg_match('/^[a-z0-9._-]{3,80}$/',$user)))throw new \DomainException('Usuario inválido.');if($email!==null&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new \DomainException('Correo inválido.');$active=filter_var($i['activo']??null,FILTER_VALIDATE_BOOL,FILTER_NULL_ON_FAILURE);if($active===null)throw new \DomainException('Estado inválido.');$d=['nombre'=>$name,'numero_empleado'=>$employee,'usuario'=>$user,'correo'=>$email,'activo'=>$active,'role_ids'=>$roles,'area_ids'=>$areas,'principal_area_id'=>$principal,'module_allow_ids'=>$allow,'module_deny_ids'=>$deny];if($creating){$this->password((string)($i['password']??''),(string)($i['password_confirmation']??''));$d['password_hash']=password_hash((string)$i['password'],PASSWORD_DEFAULT);}return$d;}
    private function assertOrganizational(array$d):void{if(!$this->organizational)return;if($d['activo']&&($d['principal_area_id']<=0||!in_array($d['principal_area_id'],$d['area_ids'],true)))throw new\DomainException('Un usuario activo debe tener un área principal.');if($d['area_ids']!==[]&&!$this->organizational->validActiveAreaIds($d['area_ids']))throw new\DomainException('Área organizacional inactiva o inexistente.');if(array_intersect($d['module_allow_ids'],$d['module_deny_ids'])!==[])throw new\DomainException('Un módulo no puede permitirse y denegarse al mismo tiempo.');$modules=array_values(array_unique([...$d['module_allow_ids'],...$d['module_deny_ids']]));if($modules!==[]&&!$this->organizational->validActiveModuleIds($modules))throw new\DomainException('Módulo inactivo o inexistente.');}
    private function ids(array$ids):array{return array_values(array_unique(array_filter(array_map('intval',$ids),fn(int$id):bool=>$id>0)));}
    private function auditOrganizationalChanges(int$userId,array$before,array$after,int$actor):void{$oldAreas=(array)($before['area_ids']??[]);$newAreas=(array)$after['area_ids'];foreach(array_diff($newAreas,$oldAreas)as$id)$this->audit->record($actor,'usuario.area_asignar','usuario',$userId,'exito',[],['area_id'=>(int)$id]);foreach(array_diff($oldAreas,$newAreas)as$id)$this->audit->record($actor,'usuario.area_retirar','usuario',$userId,'exito',['area_id'=>(int)$id],[]);if(($before['principal_area_id']??null)!==$after['principal_area_id'])$this->audit->record($actor,'usuario.area_principal_cambiar','usuario',$userId,'exito',['area_id'=>$before['principal_area_id']??null],['area_id'=>$after['principal_area_id']]);foreach(['permitir'=>'module_allow_ids','denegar'=>'module_deny_ids']as$type=>$key){$old=(array)($before[$key]??[]);$new=(array)$after[$key];foreach(array_diff($new,$old)as$id)$this->audit->record($actor,'usuario.modulo_'.$type,'usuario',$userId,'exito',[],['modulo_id'=>(int)$id]);foreach(array_diff($old,$new)as$id)$this->audit->record($actor,'usuario.modulo_excepcion_retirar','usuario',$userId,'exito',['modulo_id'=>(int)$id,'tipo'=>$type],[]);}}
    private function password(string$p,string$c):void{if(strlen($p)<12||!preg_match('/[A-Z]/',$p)||!preg_match('/[a-z]/',$p)||!preg_match('/\d/',$p))throw new \DomainException('La contraseña debe tener al menos 12 caracteres, mayúscula, minúscula y número.');if(!hash_equals($p,$c))throw new \DomainException('Las contraseñas no coinciden.');}
    private function assertRoles(array$ids):void{if(!$this->users->validRoleIds($ids))throw new \DomainException('Rol inválido.');}
    private function losesAdministration(array$ids):bool{foreach($this->users->roles()as$r)if(in_array((int)$r['id'],$ids,true)&&$r['nombre']==='Administrador')return false;return true;}
    private function required(int$id):array{return$this->users->find($id)??throw new \DomainException('Usuario no encontrado.');}
    private function transaction(callable$fn):mixed{$pdo=$this->users->pdo();$pdo->beginTransaction();try{$result=$fn();$pdo->commit();return$result;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
}
