DROP TABLE IF EXISTS inventario;

CREATE TABLE inventario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    equipo VARCHAR(255) NULL,
    estacion VARCHAR(255) NULL,
    via VARCHAR(255) NULL,
    sec VARCHAR(255) NULL,
    tipo_de_embarque VARCHAR(255) NULL,
    entregar_a VARCHAR(255) NULL,
    numero_de_guia VARCHAR(255) NULL,
    numero_de_bol VARCHAR(255) NULL,
    tipo_especifico_de_equipo VARCHAR(255) NULL,
    tipo_generico_de_equipo VARCHAR(255) NULL,
    tipo_especifico_de_equipo_2 VARCHAR(255) NULL,
    l_e VARCHAR(255) NULL,
    producto VARCHAR(255) NULL,
    grupo_de_producto VARCHAR(255) NULL,
    ferrocarril_actual VARCHAR(255) NULL,
    ultimo_movimiento VARCHAR(255) NULL,
    estacion_de_ultimo_movimiento VARCHAR(255) NULL,
    fecha_de_ultimo_movimiento VARCHAR(255) NULL,
    eta VARCHAR(255) NULL,
    eti VARCHAR(255) NULL,
    estatus_del_viaje VARCHAR(255) NULL,
    excepcion VARCHAR(255) NULL,
    ferrocarril VARCHAR(255) NULL,
    dia_remitido VARCHAR(255) NULL,
    estacion_de_origen VARCHAR(255) NULL,
    remitente VARCHAR(255) NULL,
    estacion_de_destino VARCHAR(255) NULL,
    consignatario VARCHAR(255) NULL,
    ruta VARCHAR(255) NULL,
    indicador_de_actividad VARCHAR(255) NULL,
    disponible VARCHAR(255) NULL,
    destino_en_linea VARCHAR(255) NULL,
    estatus_de_situado VARCHAR(255) NULL,
    fecha_de_situado VARCHAR(255) NULL,
    longitud_de_carro VARCHAR(255) NULL,
    ton_neta VARCHAR(255) NULL,
    sobrepeso VARCHAR(255) NULL,
    limite_de_carga VARCHAR(255) NULL,
    peso_total_del_carro VARCHAR(255) NULL,
    id_de_tren VARCHAR(255) NULL,
    fecha_importacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_equipo (equipo),
    INDEX idx_estacion (estacion),
    INDEX idx_estacion_ultimo_movimiento (estacion_de_ultimo_movimiento),
    INDEX idx_estacion_destino (estacion_de_destino)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;