<?php
declare(strict_types=1);
require dirname(__DIR__) . '/control-escaneres/bootstrap.php';
require_once dirname(__DIR__,2).'/config/config.php';

use App\Core\Database;

$adminUser=(string)getenv('AUTH_TEST_USER');$adminPassword=(string)getenv('AUTH_TEST_PASSWORD');$normalPassword=(string)getenv('AUTH_NORMAL_PASSWORD');
if($adminUser===''||$adminPassword===''||$normalPassword==='')throw new RuntimeException('Faltan credenciales efímeras de prueba.');
$base='http://127.0.0.1/Ferrocheck/public/index.php';$pdo=Database::getConnection();

final class HttpClient{public array$cookies=[];public function request(string$url,string$method='GET',array$data=[]):array{$headers=[];if($this->cookies)$headers[]='Cookie: '.implode('; ',array_map(fn($k,$v)=>$k.'='.$v,array_keys($this->cookies),$this->cookies));$options=['method'=>$method,'ignore_errors'=>true,'follow_location'=>0];if($method==='POST'){$headers[]='Content-Type: application/x-www-form-urlencoded';$options['content']=http_build_query($data);}$options['header']=implode("\r\n",$headers);$body=file_get_contents($url,false,stream_context_create(['http'=>$options]));$response=$http_response_header??[];foreach($response as$h)if(preg_match('/^Set-Cookie:\s*([^=]+)=([^;]*)/i',$h,$m))$this->cookies[$m[1]]=$m[2];preg_match('/\s(\d{3})\s/',$response[0]??'',$m);$location='';foreach($response as$h)if(str_starts_with(strtolower($h),'location:'))$location=trim(substr($h,9));return[(int)($m[1]??0),(string)$body,$location,$response];}}
function token(string$html):string{preg_match('/name="_csrf"\s+value="([^"]+)"/',$html,$m);return html_entity_decode($m[1]??'',ENT_QUOTES,'UTF-8');}
function login(HttpClient$c,string$base,string$user,string$password,string$return=''):array{[$s,$html]=$c->request($base.'?modulo=auth');ok($s===200);$before=$c->cookies['PHPSESSID']??'';[$status,$body,$location]=$c->request($base.'?modulo=auth','POST',['_csrf'=>token($html),'usuario'=>$user,'password'=>$password,'return'=>$return]);return[$status,$location,$before,$c->cookies['PHPSESSID']??''];}

$suffix=strtoupper(bin2hex(random_bytes(3)));$normalUser='fasec_consulta_'.strtolower($suffix);$normalId=null;$scannerId=null;$adminId=(int)$pdo->query("SELECT id FROM usuarios WHERE usuario=".$pdo->quote($adminUser))->fetchColumn();
try{
    $client=new HttpClient();[$status,$html]=$client->request($base.'?modulo=auth');test('GET login muestra campos, CSRF y no registro público',fn()=>ok($status===200&&strlen(token($html))===64&&str_contains($html,'name="usuario"')&&str_contains($html,'name="password"')&&!preg_match('/Registrarse|Crear cuenta/i',$html)));
    [$badStatus,$ignoredBody,$badLocation]=$client->request($base.'?modulo=auth','POST',['_csrf'=>token($html),'usuario'=>'no_existe_'.$suffix,'password'=>'Incorrecta123']);[$ignoredStatus,$badHtml]=$client->request('http://127.0.0.1'.$badLocation);test('usuario inexistente usa mensaje genérico',fn()=>ok($badStatus===303&&str_contains($badHtml,'Usuario o contraseña incorrectos')));
    $wrong=new HttpClient();[$w,$whtml]=$wrong->request($base.'?modulo=auth');[$ws,$ignoredBody,$wl]=$wrong->request($base.'?modulo=auth','POST',['_csrf'=>token($whtml),'usuario'=>$adminUser,'password'=>'Incorrecta123']);[$ignoredStatus,$wh]=$wrong->request('http://127.0.0.1'.$wl);test('contraseña incorrecta no revela existencia',fn()=>ok($w===200&&$ws===303&&str_contains($wh,'Usuario o contraseña incorrectos')));
    $csrfClient=new HttpClient();[$cs]=$csrfClient->request($base.'?modulo=auth','POST',['usuario'=>$adminUser,'password'=>$adminPassword]);test('login sin CSRF se rechaza',fn()=>ok($cs===303));
    $external=new HttpClient();[$ls,$location,$oldSession,$newSession]=login($external,$base,$adminUser,$adminPassword,'https://evil.example/steal');test('login real regenera sesión y rechaza retorno externo',fn()=>ok($ls===303&&$oldSession!==''&&$newSession!==''&&$oldSession!==$newSession&&!str_contains($location,'evil.example')));
    $sessionRow=$pdo->query("SELECT session_hash,revocada_at FROM usuario_sesiones WHERE usuario_id=$adminId ORDER BY id DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);test('sesión persiste sólo huella SHA-256',fn()=>ok($sessionRow['session_hash']===hash('sha256',$newSession)&&$sessionRow['session_hash']!==$newSession&&$sessionRow['revocada_at']===null));
    test('login carga roles, permisos, último acceso y auditoría',fn()=>ok((int)$pdo->query("SELECT COUNT(*) FROM usuario_roles ur JOIN roles r ON r.id=ur.rol_id WHERE ur.usuario_id=$adminId AND r.nombre='Administrador'")->fetchColumn()===1&&(int)$pdo->query("SELECT COUNT(DISTINCT p.id) FROM usuario_roles ur JOIN rol_permisos rp ON rp.rol_id=ur.rol_id JOIN permisos p ON p.id=rp.permiso_id WHERE ur.usuario_id=$adminId")->fetchColumn()===20&&(int)$pdo->query("SELECT ultimo_acceso IS NOT NULL FROM usuarios WHERE id=$adminId")->fetchColumn()===1&&(int)$pdo->query("SELECT COUNT(*) FROM auditoria_eventos WHERE accion='auth.login' AND usuario_id=$adminId")->fetchColumn()>0));
    [$adminStatus,$adminHtml]=$external->request($base.'?modulo=administracion&seccion=usuarios');test('administrador abre listado protegido',fn()=>ok($adminStatus===200&&str_contains($adminHtml,'Usuarios')));
    $consultaRole=(int)$pdo->query("SELECT id FROM roles WHERE nombre='Consulta'")->fetchColumn();[$createStatus,$ignoredBody,$createLocation]=$external->request($base.'?modulo=administracion&seccion=usuarios','POST',['_csrf'=>token($adminHtml),'operation'=>'create','nombre'=>'Consulta Fase C '.$suffix,'numero_empleado'=>'FC-'.$suffix,'usuario'=>$normalUser,'correo'=>$normalUser.'@example.test','password'=>$normalPassword,'password_confirmation'=>$normalPassword,'activo'=>'1','role_ids'=>[$consultaRole]]);$normalId=(int)$pdo->query("SELECT id FROM usuarios WHERE usuario=".$pdo->quote($normalUser))->fetchColumn();test('administrador crea usuario Consulta por POST',fn()=>ok($createStatus===303&&str_contains($createLocation,'administracion')&&$normalId>0));
    $normal=new HttpClient();[$normalLogin]=$tmp=login($normal,$base,$normalUser,$normalPassword);[$forbiddenStatus]=$normal->request($base.'?modulo=administracion');test('usuario Consulta recibe 403 por URL directa',fn()=>ok($normalLogin===303&&$forbiddenStatus===403));
    [$normalAuthStatus,$normalAuthHtml]=$normal->request($base.'?modulo=auth');$normalToken=token($normalAuthHtml);[$logoutGet]=$normal->request($base.'?modulo=auth&accion=logout');test('logout por GET responde 405',fn()=>ok($logoutGet===405));
    [$badLogout]=$normal->request($base.'?modulo=auth&accion=logout','POST',['_csrf'=>'incorrecto']);test('logout con CSRF inválido responde 403',fn()=>ok($badLogout===403));
    // Login devuelve redirect si ya está autenticado; el token general permanece en sesión y está en el formulario administrativo sólo para autorizados.
    $authToken=$pdoToken=null;$sessionFileToken='';
    [$adminPageStatus,$adminPage]=$external->request($base.'?modulo=administracion');$authToken=token($adminPage);[$logoutStatus,$ignoredBody,$logoutLocation]=$external->request($base.'?modulo=auth&accion=logout','POST',['_csrf'=>$authToken]);[$afterLogout]=$external->request($base.'?modulo=administracion');test('logout real revoca, redirige y bloquea administración',fn()=>ok($adminPageStatus===200&&$logoutStatus===303&&str_contains($logoutLocation,'modulo=auth')&&$afterLogout===302));
    $revoked=(int)$pdo->query("SELECT COUNT(*) FROM usuario_sesiones WHERE usuario_id=$adminId AND revocada_at IS NOT NULL")->fetchColumn();test('logout revoca sesión persistente',fn()=>ok($revoked>0));
    $scannerClient=new HttpClient();login($scannerClient,$base,$adminUser,$adminPassword);[$regStatus,$regHtml]=$scannerClient->request($base.'?modulo=control-escaneres&seccion=registrar');$area=(int)$pdo->query('SELECT id FROM scanner_areas WHERE activo=1 ORDER BY id LIMIT 1')->fetchColumn();$tag='AUTH-'.$suffix;[$postScanner,$ignoredBody,$scannerLocation]=$scannerClient->request($base.'?modulo=control-escaneres&seccion=registrar','POST',['_csrf'=>token($regHtml),'tag'=>$tag,'brand'=>'Zebra','model'=>'TC22','area_id'=>$area,'status'=>'disponible','active'=>'1']);$scannerId=(int)$pdo->query("SELECT id FROM scanners WHERE tag_original=".$pdo->quote($tag))->fetchColumn();[$catalogStatus,$catalog]=$scannerClient->request('http://127.0.0.1'.$scannerLocation.'&q='.rawurlencode($tag));test('alta de escáner usa login y actor real',fn()=>ok($regStatus===200&&$postScanner===303&&$scannerId>0&&$catalogStatus===200&&str_contains($catalog,$tag)&&(int)$pdo->query("SELECT created_by FROM scanners WHERE id=$scannerId")->fetchColumn()===$adminId&&(int)$pdo->query("SELECT COUNT(*) FROM auditoria_eventos WHERE accion='scanner.create' AND entidad_id=$scannerId AND usuario_id=$adminId")->fetchColumn()===1));
    [$cleanupStatus,$cleanupPage]=$scannerClient->request($base.'?modulo=administracion&seccion=usuarios');$cleanupToken=token($cleanupPage);$scannerClient->request($base.'?modulo=administracion&seccion=usuarios','POST',['_csrf'=>$cleanupToken,'operation'=>'deactivate','id'=>$normalId]);$inactive=new HttpClient();[$inactiveStatus,$inactiveLocation]=login($inactive,$base,$normalUser,$normalPassword);[$ignoredStatus,$inactiveHtml]=$inactive->request('http://127.0.0.1'.$inactiveLocation);test('usuario inactivo no inicia sesión y recibe mensaje genérico',fn()=>ok($inactiveStatus===303&&!isset($inactive->cookies['auth_session_hash'])&&str_contains($inactiveHtml,'Usuario o contraseña incorrectos')));[$cleanupStatus,$cleanupPage]=$scannerClient->request($base.'?modulo=administracion&seccion=usuarios');$scannerClient->request($base.'?modulo=administracion&seccion=usuarios','POST',['_csrf'=>token($cleanupPage),'operation'=>'deactivate','id'=>$adminId]);test('usuarios de prueba quedan desactivados y sesiones revocadas',fn()=>ok((int)$pdo->query("SELECT COUNT(*) FROM usuarios WHERE id IN ($adminId,$normalId) AND activo=0")->fetchColumn()===2&&(int)$pdo->query("SELECT COUNT(*) FROM usuario_sesiones WHERE usuario_id IN ($adminId,$normalId) AND revocada_at IS NULL")->fetchColumn()===0));
}finally{
    if($scannerId){$pdo->exec("DELETE FROM auditoria_eventos WHERE entidad='scanner' AND entidad_id=$scannerId");$pdo->exec("DELETE FROM scanners WHERE id=$scannerId");}
    if($normalId){$pdo->prepare('UPDATE usuarios SET activo=0 WHERE id=:id')->execute(['id'=>$normalId]);$pdo->prepare("UPDATE usuario_sesiones SET revocada_at=COALESCE(revocada_at,CURRENT_TIMESTAMP(6)),motivo_revocacion=COALESCE(motivo_revocacion,'fin_prueba_fase_c') WHERE usuario_id=:id")->execute(['id'=>$normalId]);}
}
finish('Authentication Phase C HTTP');
