<?php
declare(strict_types=1);
require dirname(__DIR__).'/control-escaneres/bootstrap.php';require_once dirname(__DIR__,2).'/config/config.php';
use App\Core\Database;use App\Repositories\{AuthRepository,RoleAdminRepository,UserAdminRepository};use App\Services\{GeneralAuditService,RoleAdminService,UserAdminService};
$pdo=Database::getConnection();$auth=new AuthRepository($pdo);$users=new UserAdminRepository($pdo);$roles=new RoleAdminRepository($pdo);$audit=new GeneralAuditService($pdo);$userService=new UserAdminService($users,$auth,$audit);$roleService=new RoleAdminService($roles,$audit);$actor=(int)$pdo->query("SELECT id FROM usuarios WHERE usuario='azarel'")->fetchColumn();$target=$pdo->query("SELECT id,nombre,numero_empleado,usuario,correo FROM usuarios WHERE usuario LIKE 'fasec_consulta_%' AND activo=0 ORDER BY id DESC LIMIT 1")->fetch(PDO::FETCH_ASSOC);if(!is_array($target))throw new RuntimeException('No existe usuario controlado para pruebas administrativas.');$targetId=(int)$target['id'];$roleMap=[];foreach($users->roles()as$r)$roleMap[$r['nombre']]=(int)$r['id'];
test('reactivación administrativa funciona',function()use($userService,$targetId,$actor,$pdo){$userService->setActive($targetId,true,$actor);ok((int)$pdo->query("SELECT activo FROM usuarios WHERE id=$targetId")->fetchColumn()===1);});
foreach(['Supervisor','Operador','Consulta']as$name){test('asigna rol '.$name,function()use($userService,$target,$targetId,$actor,$roleMap,$name,$pdo){$userService->update($targetId,['nombre'=>$target['nombre'].' Editado','numero_empleado'=>$target['numero_empleado'],'correo'=>$target['correo'],'activo'=>'1','role_ids'=>[$roleMap[$name]]],$actor);ok((int)$pdo->query("SELECT COUNT(*) FROM usuario_roles ur JOIN roles r ON r.id=ur.rol_id WHERE ur.usuario_id=$targetId AND r.nombre=".$pdo->quote($name))->fetchColumn()===1);});}
$newPassword='Cc3!'.bin2hex(random_bytes(12));test('restablecimiento usa hash y revoca sesiones',function()use($userService,$targetId,$newPassword,$actor,$pdo){$before=(string)$pdo->query("SELECT password_hash FROM usuarios WHERE id=$targetId")->fetchColumn();$userService->resetPassword($targetId,$newPassword,$newPassword,$actor);$after=(string)$pdo->query("SELECT password_hash FROM usuarios WHERE id=$targetId")->fetchColumn();ok($before!==$after&&password_verify($newPassword,$after)&&(int)$pdo->query("SELECT COUNT(*) FROM usuario_sesiones WHERE usuario_id=$targetId AND revocada_at IS NULL")->fetchColumn()===0);});
test('contraseña débil se rechaza',function()use($userService,$targetId,$actor){try{$userService->resetPassword($targetId,'corta','corta',$actor);}catch(DomainException){ok(true);return;}throw new RuntimeException('Contraseña débil aceptada.');});
test('usuario duplicado se rechaza',function()use($userService,$roleMap,$actor){try{$userService->create(['nombre'=>'Duplicado','numero_empleado'=>'DUP-'.random_int(1000,9999),'usuario'=>'azarel','correo'=>'dup'.random_int(1000,9999).'@example.test','password'=>'Dd4!PasswordSeguro','password_confirmation'=>'Dd4!PasswordSeguro','activo'=>'1','role_ids'=>[$roleMap['Consulta']]],$actor);}catch(DomainException){ok(true);return;}throw new RuntimeException('Duplicado aceptado.');});
$roleName='Fase C '.strtoupper(bin2hex(random_bytes(3)));$permissionIds=array_map('intval',array_column(array_slice($roles->permissions(),0,2),'id'));$roleId=$roleService->create(['nombre'=>$roleName,'descripcion'=>'Rol controlado de prueba','activo'=>'1','permission_ids'=>[$permissionIds[0]]],$actor);test('creación de rol asigna permisos validados',fn()=>ok($roleId>0&&$roles->permissionIds($roleId)===[$permissionIds[0]]));$roleService->update($roleId,['nombre'=>$roleName,'descripcion'=>'Rol controlado actualizado','activo'=>'1','permission_ids'=>$permissionIds],$actor);test('edición de rol reemplaza permisos',fn()=>ok(count($roles->permissionIds($roleId))===2));$roleService->update($roleId,['nombre'=>$roleName,'descripcion'=>'Rol controlado actualizado','activo'=>'0','permission_ids'=>$permissionIds],$actor);test('rol de prueba queda inactivo',fn()=>ok((int)$pdo->query("SELECT activo FROM roles WHERE id=$roleId")->fetchColumn()===0));
$userService->setActive($targetId,false,$actor);test('usuario de prueba termina inactivo',fn()=>ok((int)$pdo->query("SELECT activo FROM usuarios WHERE id=$targetId")->fetchColumn()===0));test('auditoría no contiene hashes ni contraseñas en payload',fn()=>ok((int)$pdo->query("SELECT COUNT(*) FROM auditoria_eventos WHERE modulo='autenticacion' AND (COALESCE(valor_anterior_json,'') REGEXP 'password|\\$2[aby]\\$' OR COALESCE(valor_nuevo_json,'') REGEXP 'password|\\$2[aby]\\$' OR COALESCE(metadata_json,'') REGEXP 'password|\\$2[aby]\\$')")->fetchColumn()===0));
finish('Authentication Phase C Administration');
