<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/config/config.php';require dirname(__DIR__,2).'/vendor/autoload.php';
use App\Core\Database;use App\Repositories\UserAdminRepository;use App\Repositories\ControlEscaneres\Pdo\PdoScannerCatalogQuery;use App\DTO\ControlEscaneres\ScannerCatalogFilter;use App\Services\OrganizationalBackfillValidator;
$pass=0;$fail=0;$check=function(bool$ok,string$name)use(&$pass,&$fail):void{echo($ok?'[PASS] ':'[FAIL] ').$name.PHP_EOL;$ok?$pass++:$fail++;};$pdo=Database::getConnection();$users=new UserAdminRepository($pdo);$stats=$users->organizationalStats();$pending=$users->list('',true,1,100,'unassigned');$report=(new OrganizationalBackfillValidator($pdo))->report();
$check($stats['pending']===0&&$pending===[],'todos los usuarios activos tienen area');$check($report['usuarios']['activos_multiples_principales']===0,'sin dobles areas principales');$check($report['usuarios']['asignaciones_areas_inactivas']===0&&$report['usuarios']['relaciones_duplicadas']===0,'sin relaciones de usuario invalidas');$check($report['escaneres']['sin_area']===47,'47 escaneres heredados permanecen sin asignacion');
$catalog=new PdoScannerCatalogQuery($pdo);$unassigned=$catalog->search(new ScannerCatalogFilter(organizationalArea:'unassigned',perPage:100));$check(count($unassigned)===47,'catalogo filtra heredados sin area propietaria');$check(array_reduce($unassigned,static fn(bool$c,array$r):bool=>$c&&array_key_exists('area_organizacional',$r),true),'catalogo expone area propietaria sin ocultar area habitual');
$root=dirname(__DIR__,2);$sources=file_get_contents($root.'/app/Controllers/ControlEscaneres/ControlEscaneresWebController.php').file_get_contents($root.'/app/Views/control-escaneres/plantilla.php').file_get_contents($root.'/public/index.php');$check(!str_contains($sources,'clasificacion-organizacional'),'ruta y navegacion de clasificacion retiradas');$check(!is_file($root.'/app/Views/control-escaneres/clasificacion-organizacional.php'),'pantalla independiente eliminada');$check(!str_contains($sources,'WHERE area_organizacional_id IN'),'sin filtro global por area');$registration=file_get_contents($root.'/app/Views/control-escaneres/registrar.php').file_get_contents($root.'/app/Validators/ControlEscaneres/ScannerRegistrationValidator.php');$check(str_contains($registration,'organizational_area_id')&&str_contains($registration,'obligatoria para un escáner activo'),'alta exige area propietaria para equipo activo');
$check(str_contains($sources,"if(!in_array(\$section,\$allowed,true))"),'ruta desconocida redirige de forma controlada');echo"Resumen Cierre Backfill Organizacional: $pass PASS, $fail FAIL".PHP_EOL;exit($fail===0?0:1);
