<?php
$isEdit=is_array($editing);$selectedRoles=$isEdit?(array)$editing['role_ids']:[];$selectedAreas=$isEdit?(array)($editing['area_ids']??[]):[];$principalArea=$isEdit?(int)($editing['principal_area_id']??0):0;$allowed=$isEdit?(array)($editing['module_allow_ids']??[]):[];$denied=$isEdit?(array)($editing['module_deny_ids']??[]):[];
?>
<form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="<?= $isEdit?'update':'create' ?>"><?php if($isEdit):?><input type="hidden" name="id" value="<?= (int)$editing['id'] ?>"><?php endif?>
<label>Nombre completo<input name="nombre" maxlength="150" required value="<?= $e($editing['nombre']??'') ?>"></label><label>Número de empleado<input name="numero_empleado" maxlength="40" required value="<?= $e($editing['numero_empleado']??'') ?>"></label>
<?php if(!$isEdit):?><label>Usuario<input name="usuario" maxlength="80" required autocomplete="username"></label><label>Contraseña<input type="password" name="password" minlength="12" required autocomplete="new-password"></label><label>Confirmación<input type="password" name="password_confirmation" minlength="12" required autocomplete="new-password"></label><?php else:?><div class="read-only-field"><span>Usuario</span><strong><?= $e($editing['usuario']) ?></strong></div><?php endif?>
<label>Correo<input type="email" name="correo" maxlength="190" value="<?= $e($editing['correo']??'') ?>"></label><label>Estado<select name="activo"><option value="1" <?= !$isEdit||(int)$editing['activo']===1?'selected':'' ?>>Activo</option><option value="0" <?= $isEdit&&(int)$editing['activo']===0?'selected':'' ?>>Inactivo</option></select></label>
<fieldset class="check-grid"><legend>Roles — responsabilidades y permisos de acción</legend><?php foreach($roles as$r):?><label><input type="checkbox" name="role_ids[]" value="<?= (int)$r['id'] ?>" <?= in_array((int)$r['id'],$selectedRoles,true)?'checked':'' ?>><?= $e($r['nombre']) ?></label><?php endforeach?></fieldset>
<fieldset class="check-grid"><legend>Áreas organizacionales</legend><label>Área principal <small>(obligatoria si el usuario está activo)</small><select name="principal_area_id"><option value="">Sin asignar — sólo usuarios inactivos</option><?php foreach($areas as$a):?><option value="<?= (int)$a['id'] ?>" <?= $principalArea===(int)$a['id']?'selected':'' ?>><?= $e($a['nombre']) ?></option><?php endforeach?></select></label><div><strong>Áreas adicionales opcionales</strong><p class="retention-note">El área principal se agrega automáticamente; marca únicamente alcances adicionales.</p><?php foreach($areas as$a):?><label><input type="checkbox" name="area_ids[]" value="<?= (int)$a['id'] ?>" <?= in_array((int)$a['id'],$selectedAreas,true)&&$principalArea!==(int)$a['id']?'checked':'' ?>><?= $e($a['nombre']) ?></label><?php endforeach?></div></fieldset>
<fieldset class="check-grid check-grid--permissions"><legend>Excepciones individuales de módulos</legend><p class="retention-note">Los módulos no seleccionados se heredan de las áreas. Una denegación explícita prevalece sobre cualquier acceso global o heredado.</p><?php foreach($modules as$m):if(!(int)$m['activo'])continue;?><div><strong><?= $e($m['nombre']) ?></strong><label><input type="radio" name="module_decision[<?= (int)$m['id'] ?>]" value="inherit" <?= !in_array((int)$m['id'],$allowed,true)&&!in_array((int)$m['id'],$denied,true)?'checked':'' ?>>Heredar de áreas</label><label><input type="radio" name="module_decision[<?= (int)$m['id'] ?>]" value="permitir" <?= in_array((int)$m['id'],$allowed,true)?'checked':'' ?>>Permitir individualmente</label><label><input type="radio" name="module_decision[<?= (int)$m['id'] ?>]" value="denegar" <?= in_array((int)$m['id'],$denied,true)?'checked':'' ?>>Denegar individualmente</label></div><?php endforeach?></fieldset>
<div class="form-actions"><button class="button button--primary"><?= $isEdit?'Guardar cambios':'Crear usuario' ?></button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios">Cancelar</a></div></form>
