<?php
declare(strict_types=1);
$e=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$can=fn(string$p):bool=>$this->authorization->can($p);$selected=$area?(array)$area['module_ids']:[];ob_start();
?>
<section class="admin-page"><header class="page-header"><div><p class="eyebrow">Administración</p><h1>Áreas organizacionales</h1><p>Administra departamentos y módulos heredados sin mezclarlos con áreas operativas.</p></div><?php if($can('areas.crear')):?><a class="button button--primary" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=areas&amp;accion=nueva">Nueva área</a><?php endif?></header>
<?php if($message):?><div class="alert" role="status"><?= $e($message) ?></div><?php endif?>
<form class="card filter-bar" method="get"><input type="hidden" name="modulo" value="administracion"><input type="hidden" name="seccion" value="areas"><label>Buscar<input name="q" value="<?= $e($search) ?>" placeholder="Nombre o clave"></label><button class="button button--primary">Buscar</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=areas">Limpiar</a></form>
<section class="card"><div class="table-heading"><h2>Catálogo organizacional</h2></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Clave</th><th>Área</th><th>Descripción</th><th>Estado</th><th>Usuarios</th><th>Módulos</th><th>Acciones</th></tr></thead><tbody><?php foreach($items as$item):?><tr><td><code><?= $e($item['clave']) ?></code></td><td><strong><?= $e($item['nombre']) ?></strong></td><td><?= $e($item['descripcion']?:'—') ?></td><td><span class="badge <?= (int)$item['activo']?'badge--success':'badge--muted' ?>"><?= (int)$item['activo']?'Activa':'Inactiva' ?></span></td><td><?= (int)$item['usuarios'] ?></td><td><?= (int)$item['modulos'] ?></td><td><div class="actions"><?php if($can('areas.editar')):?><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=areas&amp;id=<?= (int)$item['id'] ?>">Editar y asociar módulos</a><?php endif?><?php if($can('areas.desactivar')):?><form method="post" data-confirm="¿Confirmas el cambio de estado del área?"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int)$item['id'] ?>"><button class="button" name="operation" value="<?= (int)$item['activo']?'deactivate':'activate' ?>"><?= (int)$item['activo']?'Desactivar':'Activar' ?></button></form><?php endif?></div></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($can('areas.crear')&&($_GET['accion']??'')==='nueva'):?><section class="card form-card"><h2>Nueva área</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="create"><label>Clave estable<input name="clave" required maxlength="80" pattern="[a-z0-9_]+" placeholder="ejemplo_area"></label><label>Nombre<input name="nombre" required maxlength="120"></label><label>Descripción<input name="descripcion" maxlength="500"></label><div class="form-actions"><button class="button button--primary">Crear área</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=areas">Cancelar</a></div></form></section><?php endif?>
<?php if($area&&$can('areas.editar')):?><section class="card form-card"><h2>Editar <?= $e($area['nombre']) ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="update"><input type="hidden" name="id" value="<?= (int)$area['id'] ?>"><div class="read-only-field"><span>Clave protegida</span><strong><?= $e($area['clave']) ?></strong></div><label>Nombre<input name="nombre" required maxlength="120" value="<?= $e($area['nombre']) ?>"></label><label>Descripción<input name="descripcion" maxlength="500" value="<?= $e($area['descripcion']) ?>"></label><fieldset class="check-grid"><legend>Módulos heredados por el área</legend><?php foreach($modules as$module):if(!(int)$module['activo'])continue;?><label><input type="checkbox" name="module_ids[]" value="<?= (int)$module['id'] ?>" <?= in_array((int)$module['id'],$selected,true)?'checked':'' ?>><?= $e($module['nombre']) ?></label><?php endforeach?></fieldset><div class="form-actions"><button class="button button--primary">Guardar área y módulos</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=areas">Cancelar</a></div></form></section><?php endif?></section>
<?php $adminContent=(string)ob_get_clean();$adminTitle='Áreas organizacionales';$adminSection='areas';require __DIR__.'/_layout.php';
