<?php
declare(strict_types=1);
$e=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$can=fn(string$p):bool=>$this->authorization->can($p);$selected=$module?(array)$module['area_ids']:[];ob_start();
?>
<section class="admin-page"><header class="page-header"><div><p class="eyebrow">Administración</p><h1>Módulos</h1><p>Controla visibilidad, orden y acceso base. Las claves y rutas permanecen protegidas.</p></div></header><?php if($message):?><div class="alert" role="status"><?= $e($message) ?></div><?php endif?>
<form class="card filter-bar" method="get"><input type="hidden" name="modulo" value="administracion"><input type="hidden" name="seccion" value="modulos"><label>Buscar<input name="q" value="<?= $e($search) ?>" placeholder="Nombre o clave"></label><button class="button button--primary">Buscar</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=modulos">Limpiar</a></form>
<section class="card"><div class="table-responsive"><table class="data-table"><thead><tr><th>Orden</th><th>Clave</th><th>Módulo</th><th>Ruta protegida</th><th>Estado</th><th>Menú</th><th>Áreas</th><th>Excepciones</th><th>Acciones</th></tr></thead><tbody><?php foreach($items as$item):?><tr><td><?= (int)$item['orden'] ?></td><td><code><?= $e($item['clave']) ?></code></td><td><strong><?= $e($item['nombre']) ?></strong></td><td><code><?= $e($item['ruta']) ?></code></td><td><span class="badge <?= (int)$item['activo']?'badge--success':'badge--muted' ?>"><?= (int)$item['activo']?'Activo':'Inactivo' ?></span></td><td><?= (int)$item['visible_menu']?'Visible':'Oculto' ?></td><td><?= (int)$item['areas'] ?></td><td><?= (int)$item['excepciones'] ?></td><td><?php if($can('modulos.asignar')):?><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=modulos&amp;id=<?= (int)$item['id'] ?>">Configurar</a><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($module&&$can('modulos.asignar')):?><section class="card form-card"><h2>Configurar <?= $e($module['nombre']) ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="id" value="<?= (int)$module['id'] ?>"><div class="read-only-field"><span>Clave</span><strong><?= $e($module['clave']) ?></strong></div><div class="read-only-field"><span>Ruta protegida</span><strong><?= $e($module['ruta']) ?></strong></div><label>Nombre visible<input name="nombre" required maxlength="120" value="<?= $e($module['nombre']) ?>"></label><label>Descripción<input name="descripcion" maxlength="500" value="<?= $e($module['descripcion']) ?>"></label><label>Orden<input type="number" name="orden" min="0" max="65535" required value="<?= (int)$module['orden'] ?>"></label><label>Estado<select name="activo"><option value="1" <?= (int)$module['activo']?'selected':'' ?>>Activo</option><option value="0" <?= !(int)$module['activo']?'selected':'' ?>>Inactivo</option></select></label><label>Visibilidad del menú<select name="visible_menu"><option value="1" <?= (int)$module['visible_menu']?'selected':'' ?>>Visible</option><option value="0" <?= !(int)$module['visible_menu']?'selected':'' ?>>Oculto</option></select></label><fieldset class="check-grid"><legend>Áreas con acceso heredado</legend><?php foreach($areas as$area):?><label><input type="checkbox" name="area_ids[]" value="<?= (int)$area['id'] ?>" <?= in_array((int)$area['id'],$selected,true)?'checked':'' ?>><?= $e($area['nombre']) ?></label><?php endforeach?></fieldset><div class="form-actions"><button class="button button--primary">Guardar configuración</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=modulos">Cancelar</a></div></form></section><?php endif?></section>
<?php $adminContent=(string)ob_get_clean();$adminTitle='Módulos';$adminSection='modulos';require __DIR__.'/_layout.php';
