<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$can=fn(string $p):bool=>$this->authorization->can($p);$selected=$role?(array)$role['permission_ids']:[];
ob_start();?>
<section class="admin-page"><header class="page-header"><div><p class="eyebrow">Administración</p><h1>Roles y permisos</h1><p>Define responsabilidades sin otorgar accesos innecesarios.</p></div><?php if($can('roles.crear')):?><a class="button button--primary" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=roles&amp;accion=nuevo">Nuevo rol</a><?php endif?></header>
<?php if($message):?><div class="alert" role="status"><?= $e($message) ?></div><?php endif?>
<section class="card"><div class="table-heading"><h2>Roles configurados</h2></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Rol</th><th>Descripción</th><th>Estado</th><th>Permisos</th><th>Usuarios</th><th>Acciones</th></tr></thead><tbody><?php foreach($items as$item):?><tr><td><strong><?= $e($item['nombre']) ?></strong><?php if((int)$item['es_sistema']):?> <span class="badge">Sistema</span><?php endif?></td><td><?= $e($item['descripcion']?:'—') ?></td><td><span class="badge <?= (int)$item['activo']?'badge--success':'badge--muted' ?>"><?= (int)$item['activo']?'Activo':'Inactivo' ?></span></td><td><?= (int)$item['permisos'] ?></td><td><?= (int)$item['usuarios'] ?></td><td><?php if($can('roles.editar')):?><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=roles&amp;id=<?= (int)$item['id'] ?>">Editar y administrar permisos</a><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($can($role?'roles.editar':'roles.crear')&&($role||($_GET['accion']??'')==='nuevo')):?><section class="card form-card"><h2><?= $role?'Editar rol':'Nuevo rol' ?></h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="<?= $role?'update':'create' ?>"><?php if($role):?><input type="hidden" name="id" value="<?= (int)$role['id'] ?>"><?php endif?><label>Nombre<input name="nombre" required maxlength="80" value="<?= $e($role['nombre']??'') ?>"></label><label>Descripción<input name="descripcion" maxlength="255" value="<?= $e($role['descripcion']??'') ?>"></label><label>Estado<select name="activo"><option value="1">Activo</option><option value="0" <?= $role&&!(int)$role['activo']?'selected':'' ?>>Inactivo</option></select></label><fieldset class="check-grid check-grid--permissions"><legend>Permisos</legend><?php foreach($permissions as$p):?><label><input type="checkbox" name="permission_ids[]" value="<?= (int)$p['id'] ?>" <?= in_array((int)$p['id'],$selected,true)?'checked':'' ?>><span><strong><?= $e($p['nombre']) ?></strong><small><?= $e($p['clave']) ?></small></span></label><?php endforeach?></fieldset><div class="form-actions"><button class="button button--primary">Guardar rol</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=roles">Cancelar</a></div></form></section><?php endif?></section>
<?php $adminContent=(string)ob_get_clean();$adminTitle='Roles y permisos';$adminSection='roles';require __DIR__.'/_layout.php';
