<?php
declare(strict_types=1);
use App\Support\SpanishDateFormatter;
$e=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$can=fn(string$p):bool=>$this->authorization->can($p);$formatDate=static fn(?string$v):string=>SpanishDateFormatter::format($v,'Nunca');$pages=max(1,(int)ceil($total/20));ob_start();
?>
<section class="admin-page">
 <header class="page-header"><div><p class="eyebrow">Administracion</p><h1>Usuarios</h1><p>Gestiona accesos, roles y clasificacion organizacional.</p></div><?php if($can('usuarios.crear')):?><a class="button button--primary" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios&amp;accion=nuevo">Nuevo usuario</a><?php endif?></header>
 <?php if($message):?><div class="alert" role="status"><?= $e($message) ?></div><?php endif?>
 <div class="stats-grid"><article class="card"><strong><?= (int)$organizationalStats['total'] ?></strong><span>Usuarios activos</span></article><article class="card"><strong><?= (int)$organizationalStats['assigned'] ?></strong><span>Con area</span></article><article class="card"><strong><?= (int)$organizationalStats['pending'] ?></strong><span>Activos sin area</span></article><article class="card"><strong><?= $e($organizationalStats['percentage']) ?>%</strong><span>Clasificados</span></article></div>
 <form class="card filter-bar" method="get"><input type="hidden" name="modulo" value="administracion"><input type="hidden" name="seccion" value="usuarios"><label>Buscar<input name="q" value="<?= $e($search) ?>" placeholder="Nombre, usuario o empleado"></label><label>Estado<select name="activo"><option value="">Todos</option><option value="1" <?= $active===true?'selected':'' ?>>Activos</option><option value="0" <?= $active===false?'selected':'' ?>>Inactivos</option></select></label><label>Area<select name="area"><option value="">Todas</option><option value="unassigned" <?= $areaFilter==='unassigned'?'selected':'' ?>>Sin asignar</option><?php foreach($areas as$area):?><option value="<?= (int)$area['id'] ?>" <?= $areaFilter===(string)$area['id']?'selected':'' ?>><?= $e($area['nombre']) ?></option><?php endforeach?></select></label><button class="button button--primary">Aplicar filtros</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios">Limpiar</a><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios&amp;accion=exportar-pendientes">CSV pendientes</a></form>
 <?php if($action==='nuevo'&&$can('usuarios.crear')):?><section class="card form-card"><h2>Nuevo usuario</h2><?php $editing=null;require __DIR__.'/_user-form.php';?></section><?php endif?>
 <section class="card"><div class="table-heading"><div><h2>Directorio de usuarios</h2><p><?= (int)$total ?> resultado(s)</p><small>Un usuario activo sin área es una configuración incompleta y no hereda módulos.</small></div></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Nombre</th><th>Empleado</th><th>Usuario</th><th>Roles</th><th>Area principal</th><th>Módulos por compatibilidad</th><th>Estado</th><th>Ultimo acceso</th><th>Historial / sesion</th><th>Acciones</th></tr></thead><tbody>
 <?php if($items===[]):?><tr><td colspan="10"><div class="empty-state">No hay usuarios que coincidan con los filtros.</div></td></tr><?php endif?>
 <?php foreach($items as$item):?><tr><td><strong><?= $e($item['nombre']) ?></strong></td><td><?= $e($item['numero_empleado']) ?></td><td><?= $e($item['usuario']) ?></td><td><?= $e($item['roles']?:'Sin rol') ?></td><td><?= $item['area_principal']?$e($item['area_principal']):'<span class="badge badge--muted">Pendiente de asignacion</span>' ?></td><td><small><?= $e($item['modulos_compatibilidad']?:'No aplica') ?></small></td><td><span class="badge <?= (int)$item['activo']?'badge--success':'badge--muted' ?>"><?= (int)$item['activo']?'Activo':'Inactivo' ?></span></td><td><?= $e($formatDate($item['ultimo_acceso']??null)) ?></td><td><?= (int)$item['tiene_historial']?'Con historial':'Sin historial' ?><br><small><?= (int)$item['sesiones_activas']?'Sesion activa':'Sin sesion activa' ?></small></td><td><div class="actions"><?php if($can('areas.asignar')):?><a href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios&amp;accion=asignar-area&amp;id=<?= (int)$item['id'] ?>"><?= $item['area_principal']?'Cambiar areas':'Asignar area' ?></a><?php endif?><?php if($can('usuarios.editar')):?><a href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios&amp;accion=editar&amp;id=<?= (int)$item['id'] ?>">Editar</a><?php endif?></div></td></tr><?php endforeach?></tbody></table></div>
 <?php if($pages>1):?><nav class="pagination" aria-label="Paginacion"><?php for($p=1;$p<=$pages;$p++):?><a class="<?= $p===$page?'is-current':'' ?>" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios&amp;q=<?= rawurlencode($search) ?>&amp;activo=<?= $active===null?'':(int)$active ?>&amp;area=<?= rawurlencode($areaFilter) ?>&amp;pagina=<?= $p ?>"><?= $p ?></a><?php endfor?></nav><?php endif?></section>
 <?php if($action==='asignar-area'&&$user&&$can('areas.asignar')):?><section class="card form-card"><h2>Clasificar areas de <?= $e($user['nombre']) ?></h2><p><strong><?= $e($user['usuario']) ?></strong>. Los roles y permisos no se modificaran.</p><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="preview_areas"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><label>Area principal<select name="principal_area_id" required><option value="">Selecciona</option><?php foreach($areas as$area):?><option value="<?= (int)$area['id'] ?>" <?= (int)($user['principal_area_id']??0)===(int)$area['id']?'selected':'' ?>><?= $e($area['nombre']) ?></option><?php endforeach?></select></label><fieldset><legend>Areas asignadas</legend><?php foreach($areas as$area):?><label><input type="checkbox" name="area_ids[]" value="<?= (int)$area['id'] ?>" <?= in_array((int)$area['id'],(array)$user['area_ids'],true)?'checked':'' ?>> <?= $e($area['nombre']) ?></label><?php endforeach?></fieldset><div class="form-actions"><button class="button button--primary">Previsualizar impacto</button><a class="button" href="<?= $e(BASE_URL) ?>/index.php?modulo=administracion&amp;seccion=usuarios">Cancelar</a></div></form>
 <?php if($areaPreview):?><div class="impact-preview"><h3>Confirma el impacto</h3><p>Usuario: <?= $e($areaPreview['user']['nombre']) ?> (<?= $e($areaPreview['user']['usuario']) ?>). Rol: <?= $e($areaPreview['user']['roles']?:'Sin rol') ?>.</p><p>Area principal nueva: <strong><?= $e($areaPreview['principal']['nombre']) ?></strong></p><p>Modulos heredados: <?= $e(implode(', ',$areaPreview['inherited'])?:'Ninguno') ?></p><p>Ganara: <?= $e(implode(', ',$areaPreview['gained'])?:'Ninguno') ?></p><p>Dejara de heredar: <?= $e(implode(', ',$areaPreview['lost'])?:'Ninguno') ?></p><p>Excepciones: <?php foreach($areaPreview['exceptions'] as$exception):?><span class="badge"><?= $e($exception['nombre'].' - '.$exception['tipo']) ?></span> <?php endforeach?><?= $areaPreview['exceptions']===[]?'Ninguna':'' ?></p><p><strong>Los permisos no cambian.</strong> El area define los modulos disponibles, pero las acciones siguen dependiendo de los permisos del rol.</p><form method="post" data-confirm="Confirma la clasificacion organizacional del usuario."><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="confirm_areas"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><input type="hidden" name="preview_token" value="<?= $e($areaPreview['token']) ?>"><button class="button button--primary">Confirmar asignacion</button></form></div><?php endif?></section><?php endif?>
 <?php if($action==='editar'&&$user):?><section class="card form-card"><h2>Editar usuario</h2><?php $editing=$user;require __DIR__.'/_user-form.php';?></section><?php endif?>
 <?php if($action==='password'&&$user):?><section class="card form-card"><h2>Restablecer contrasena</h2><form method="post" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="operation" value="password"><input type="hidden" name="id" value="<?= (int)$user['id'] ?>"><label>Nueva contrasena<input type="password" name="password" required minlength="12"></label><label>Confirmar<input type="password" name="password_confirmation" required minlength="12"></label><button class="button button--primary">Restablecer</button></form></section><?php endif?>
</section>
<?php $adminContent=(string)ob_get_clean();$adminTitle='Usuarios';$adminSection='usuarios';require __DIR__.'/_layout.php';
