CREATE TABLE IF NOT EXISTS scanners (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo_interno VARCHAR(20) NOT NULL,
    tag VARCHAR(80) NULL,
    marca VARCHAR(100) NULL,
    modelo VARCHAR(120) NULL,
    numero_serie VARCHAR(120) NULL,
    imei VARCHAR(40) NULL,
    chip VARCHAR(80) NULL,
    numero_telefonico VARCHAR(40) NULL,
    red VARCHAR(80) NULL,
    plan VARCHAR(120) NULL,
    pin VARCHAR(20) NULL,
    puk VARCHAR(30) NULL,
    actividad VARCHAR(120) NULL,
    area VARCHAR(120) NULL,
    ubicacion VARCHAR(200) NULL,
    estado VARCHAR(80) NULL,
    indice_conservacion TINYINT UNSIGNED NULL,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    observaciones TEXT NULL,
    fecha_alta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_scanners_codigo UNIQUE (codigo_interno),
    CONSTRAINT uq_scanners_tag UNIQUE (tag),
    CONSTRAINT uq_scanners_serie UNIQUE (numero_serie),
    INDEX idx_scanners_estado (estado),
    INDEX idx_scanners_area (area),
    INDEX idx_scanners_activo (activo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
