-- Generado de forma determinista desde route_codes; no editar las filas manualmente.
-- Fuente SHA-256: 42640d6baf5de85a151c38ea6d1234d5f8a0948bb605e2e173d7a60b5bf9972e
-- MariaDB: los ALTER TABLE producen commits implícitos; el bloque DML posterior sí es transaccional.

ALTER TABLE rail_catalog_versions
    MODIFY imported_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'manual' AFTER active,
    ADD COLUMN IF NOT EXISTS seed_migration VARCHAR(64) NULL AFTER origin,
    ADD CONSTRAINT IF NOT EXISTS chk_rail_catalog_system_importer CHECK (imported_by IS NOT NULL OR origin='system');

ALTER TABLE rail_catalog_route_codes
    DROP INDEX IF EXISTS uq_rail_catalog_route_version_code,
    ADD COLUMN IF NOT EXISTS heavy_duty VARCHAR(255) NULL AFTER carrier,
    ADD COLUMN IF NOT EXISTS usa_canada VARCHAR(255) NULL AFTER heavy_duty,
    ADD COLUMN IF NOT EXISTS production_plant VARCHAR(255) NULL AFTER usa_canada,
    ADD COLUMN IF NOT EXISTS rc_plant VARCHAR(255) NULL AFTER production_plant,
    ADD COLUMN IF NOT EXISTS load_by VARCHAR(255) NULL AFTER rc_plant,
    ADD COLUMN IF NOT EXISTS border_crossing VARCHAR(255) NULL AFTER load_by,
    ADD COLUMN IF NOT EXISTS seed_migration VARCHAR(64) NULL AFTER border_crossing,
    ADD UNIQUE INDEX IF NOT EXISTS uq_rail_catalog_route_version_source (catalog_version_id,source_row);

START TRANSACTION;
SET @official_sha256 := '42640d6baf5de85a151c38ea6d1234d5f8a0948bb605e2e173d7a60b5bf9972e';
SET @official_preexisting := (SELECT COUNT(*) FROM rail_catalog_versions WHERE source_sha256=@official_sha256);

INSERT INTO rail_catalog_versions
    (source_filename,source_sha256,imported_by,active,origin,seed_migration)
VALUES ('vascor_sm_db.xlsx',@official_sha256,NULL,0,'system',NULL)
ON DUPLICATE KEY UPDATE
    source_filename=VALUES(source_filename),origin='system',id=LAST_INSERT_ID(id);

SET @official_catalog_version_id := (SELECT id FROM rail_catalog_versions WHERE source_sha256=@official_sha256 LIMIT 1);
UPDATE rail_catalog_versions
SET seed_migration=IF(@official_preexisting=0,CONCAT('20260731_019_seed_official_rail_route_catalog',':created'),CONCAT('20260731_019_seed_official_rail_route_catalog',':adopted'))
WHERE id=@official_catalog_version_id;
UPDATE rail_catalog_versions SET active=0 WHERE active=1 AND id<>@official_catalog_version_id;
UPDATE rail_catalog_versions SET active=1 WHERE id=@official_catalog_version_id;

INSERT INTO rail_catalog_route_codes
    (catalog_version_id,source_row,route_code,route_king,market,shipping_destination,carrier,
     heavy_duty,usa_canada,production_plant,rc_plant,load_by,border_crossing,seed_migration)
VALUES
(@official_catalog_version_id,2,'20','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,3,'20IA','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,4,'20IL','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,5,'20IN','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,6,'20MI','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,7,'20MN','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,8,'20OH','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,9,'20WI','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,10,'20IA','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,11,'20IL','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,12,'20IN','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,13,'20MI','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,14,'20MN','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,15,'20WI','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,16,'20M','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,17,'20W','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,18,'HD20','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,19,'HD20IA','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,20,'HD20IL','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,21,'HD20IN','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,22,'HD20M','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,23,'HD20MI','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,24,'HD20MN','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,25,'HD20OH','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,26,'HD20W','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,27,'HD20WI','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','RAM','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,28,'HD20','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,29,'HD20IA','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,30,'HD20IL','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,31,'HD20IN','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,32,'HD20M','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,33,'HD20MI','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,34,'HD20MN','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,35,'HD20OH','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,36,'HD20W','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,37,'HD20WI','20','NAFTA','LOGISTICS PARK, IL','BNSF','SI','USA','Promaster','20RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,38,'20','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,39,'20M','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,40,'20OH','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,41,'20W','20','NAFTA','LOGISTICS PARK, IL','BNSF','NO','USA','Promaster','20Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,42,'68','68','NAFTA','ALLIANCE, TX','DTYG','NO','USA','RAM','68RAM','Truck','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,43,'68','68','NAFTA','ALLIANCE, TX','DTYG','NO','USA','RAM','68RAM','Truck','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,44,'HD68','68','NAFTA','ALLIANCE, TX','DTYG','SI','USA','RAM','68RAM','Truck','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,45,'HD68','68','NAFTA','ALLIANCE, TX','DTYG','SI','USA','RAM','68RAM','Truck','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,46,'85B','85','NAFTA','big lift','BNSF','NO','USA','RAM','85BRAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,47,'85','85','NAFTA','big lift','BNSF','NO','USA','RAM','85RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,48,'85','85','NAFTA','big lift','BNSF','NO','USA','Promaster','85Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,49,'HD85','85','NAFTA','big lift','BNSF','NO','USA','RAM','85RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,50,'HD85B','85','NAFTA','big lift','BNSF','NO','USA','RAM','85RAM','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,51,'HD85','85','NAFTA','big lift','BNSF','NO','USA','Promaster','85Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,52,'HD85B','85','NAFTA','big lift','BNSF','NO','USA','Promaster','85Promaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,53,'85B','85','NAFTA','big lift','BNSF','NO','USA','Promaster','85BPromaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,54,'85','85','NAFTA','big lift','BNSF','NO','USA','Promaster','85BPromaster','Multi-Max','Multi-Max','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,55,'21','21','NAFTA','JACKSONVILLE','UP','NO','USA','RAM','21RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,56,'GT','21','NAFTA','JACKSONVILLE','UP','NO','USA','RAM','21RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,57,'HD21','21','NAFTA','JACKSONVILLE','UP','SI','USA','RAM','21RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,58,'PA','21','NAFTA','JACKSONVILLE','UP','NO','USA','RAM','21RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,59,'24W','24','NAFTA','ROLLA, CO UP RAILHEAD','UP','NO','USA','RAM','24RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,60,'24','24','NAFTA','ROLLA, CO UP RAILHEAD','UP','NO','USA','RAM','24RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,61,'24','24','NAFTA','ROLLA, CO UP RAILHEAD','UP','NO','USA','RAM','24RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,62,'HD24','24','NAFTA','ROLLA, CO UP RAILHEAD','UP','SI','USA','RAM','24RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,63,'HD24W','24','NAFTA','ROLLA, CO UP RAILHEAD','UP','SI','USA','RAM','24RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,64,'25','25','NAFTA','WINSTON SALEM,NC','UP','NO','USA','RAM','25RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,65,'HD25','25','NAFTA','WINSTON SALEM,NC','UP','SI','USA','RAM','25RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,66,'26','26','NAFTA','TAMPA','UP','NO','USA','RAM','26RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,67,'HD26','26','NAFTA','TAMPA','UP','SI','USA','RAM','26RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,68,'27','27','NAFTA','COUNCIL BLUFFS, IA','UP','NO','USA','RAM','27RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,69,'27','27','NAFTA','COUNCIL BLUFFS, IA','UP','NO','USA','RAM','27RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,70,'HD27','27','NAFTA','COUNCIL BLUFFS, IA','UP','SI','USA','RAM','27RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,71,'HD27','27','NAFTA','COUNCIL BLUFFS, IA','UP','SI','USA','RAM','27RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,72,'28','28','NAFTA','BUFFALO','JCC','NO','USA','RAM','28RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,73,'HD28','28','NAFTA','BUFFALO','JCC','SI','USA','RAM','28RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,74,'29','29','NAFTA','ORLANDO RAILHEAD','UP','NO','USA','RAM','29RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,75,'29A','29','NAFTA','ORLANDO RAILHEAD','UP','NO','USA','RAM','29RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,76,'HD29','29','NAFTA','ORLANDO RAILHEAD','UP','SI','USA','RAM','29RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,77,'HD29A','29','NAFTA','ORLANDO RAILHEAD','UP','SI','USA','RAM','29RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,78,'30','30','NAFTA','KANSAS CITY, KS','BNSF','NO','USA','RAM','30RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,79,'HD30','30','NAFTA','KANSAS CITY, KS','BNSF','SI','USA','RAM','30RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,80,'31N','31','NAFTA',NULL,'BNSF','NO','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,81,'31K','31','NAFTA',NULL,'BNSF','NO','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,82,'31L','31','NAFTA',NULL,'BNSF','NO','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,83,'31M','31','NAFTA',NULL,'BNSF','NO','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,84,'HD31K','31','NAFTA',NULL,'BNSF','SI','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,85,'HD31L','31','NAFTA',NULL,'BNSF','SI','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,86,'HD31N','31','NAFTA',NULL,'BNSF','SI','USA','RAM','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,87,'38','38','NAFTA','PETERSBURG','UP','NO','USA','RAM','38RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,88,'HD38','38','NAFTA','PETERSBURG','UP','SI','USA','RAM','38RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,89,'40','40','NAFTA','SALT LAKE CITY MM','UP','NO','USA','RAM','40RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,90,'HD40','40','NAFTA','SALT LAKE CITY MM','UP','SI','USA','RAM','40RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,91,'43','43','NAFTA','BENICIA, CA','UP','NO','USA','RAM','43RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,92,'HD43','43','NAFTA','BENICIA, CA','UP','SI','USA','RAM','43RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,93,'44','44','NAFTA','Miami','UP','NO','USA','RAM','44RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,94,'44A','44','NAFTA','Miami','UP','NO','USA','RAM','44RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,95,'HD44','44','NAFTA','Miami','UP','NO','USA','RAM','44RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,96,'HD44A','44','NAFTA','Miami','UP','NO','USA','RAM','44RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,97,'46','46','NAFTA','OKLAHOMA CITY, OK','BNSF','NO','USA','RAM','46RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,98,'46','46','NAFTA','OKLAHOMA CITY, OK','BNSF','NO','USA','RAM','46RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,99,'HD46','46','NAFTA','OKLAHOMA CITY, OK','BNSF','SI','USA','RAM','46RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,100,'HD46','46','NAFTA','OKLAHOMA CITY, OK','BNSF','SI','USA','RAM','46RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,101,'47','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,102,'31K','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,103,'31L','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,104,'31M','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,105,'31N','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,106,'HD47','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,107,'31','47','NAFTA','SAN DIEGO, CA','BNSF','NO','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,108,'HD31','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,109,'HD31K','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,110,'HD31L','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,111,'HD31M','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,112,'HD31N','47','NAFTA','SAN DIEGO, CA','BNSF','SI','USA','RAM','47RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,113,'48','48','NAFTA','MIRA LOMA CALIFORNIA','UP','NO','USA','RAM','48RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,114,'35','48','NAFTA','MIRA LOMA CALIFORNIA','UP','NO','USA','RAM','48RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,115,'HD48','48','NAFTA','MIRA LOMA CALIFORNIA','UP','SI','USA','RAM','48RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,116,'HD35','48','NAFTA','MIRA LOMA CALIFORNIA','UP','SI','USA','RAM','48RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,117,'52','52','NAFTA','SPOKANE,WA','BNSF','NO','USA','RAM','52RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,118,'HD52','52','NAFTA','SPOKANE,WA','BNSF','SI','USA','RAM','52RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,119,'55','55','NAFTA','COTIAGE GROVE, MN','BNSF','NO','USA','RAM','55RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,120,'55A','55','NAFTA','COTIAGE GROVE, MN','BNSF','NO','USA','RAM','55RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,121,'HD55','55','NAFTA','COTIAGE GROVE, MN','BNSF','SI','USA','RAM','55RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,122,'HD55A','55','NAFTA','COTIAGE GROVE, MN','BNSF','SI','USA','RAM','55RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,123,'56','56','NAFTA','Hapeville','UP','SI','USA','RAM','56RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,124,'HD56','56','NAFTA','Hapeville','UP','SI','USA','RAM','56RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,125,'58','58','NAFTA','PALM CENTER VDC','UP','NO','USA','RAM','58RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,126,'58A','58','NAFTA','PALM CENTER VDC','UP','NO','USA','RAM','58RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,127,'HD58','58','NAFTA','PALM CENTER VDC','UP','SI','USA','RAM','58RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,128,'HD58A','58','NAFTA','PALM CENTER VDC','UP','SI','USA','RAM','58RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,129,'59','59','NAFTA',NULL,'UP','NO','USA','RAM',NULL,'Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,130,'HD59','59','NAFTA',NULL,'UP','SI','USA','RAM',NULL,'Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,131,'62','62','NAFTA','NASHVILLE','UP','NO','USA','RAM','62RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,132,'62','62','NAFTA','NASHVILLE','UP','NO','USA','RAM','62RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,133,'HD62','62','NAFTA','NASHVILLE','UP','SI','USA','RAM','62RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,134,'HD62','62','NAFTA','NASHVILLE','UP','SI','USA','RAM','62RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,135,'69','69','NAFTA','JEFFERSON NORTH RAIL','BNSF','NO','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,136,'70C','69','NAFTA','SHAP YARD','BNSF','NO','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,137,'70E','69','NAFTA','SHAP YARD','BNSF','NO','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,138,'HD69','69','NAFTA','JEFFERSON NORTH RAIL','BNSF','SI','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,139,'HD70C','69','NAFTA','SHAP YARD','BNSF','SI','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,140,'HD70E','69','NAFTA','SHAP YARD','BNSF','SI','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,141,'HDF2','69','NAFTA','JEFFERSO N NORTH RAIL','BNSF','SI','Canada','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,142,'HD79','69','NAFTA','ALBURQUEQUE','BNSF','SI','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,143,'HD79','69','NAFTA','ALBURQUEQUE','BNSF','SI','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,144,'79','69','NAFTA','JEFFERSON ASSY','BNSF','NO','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,145,'79','69','NAFTA','JEFFERSON ASSY','BNSF','NO','USA','RAM','69RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,146,'71','71','NAFTA','LAUREL','BNSF','NO','USA','RAM','71RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,147,'71B','71','NAFTA','SILVER BOW MT','BNSF','NO','USA','RAM','71RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,148,'HD71','71','NAFTA','LAUREL','BNSF','SI','USA','RAM','71RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,149,'73','73','NAFTA','LORDSTOWN','BNSF','NO','USA','RAM','73RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,150,'HD73','73','NAFTA','LORDSTOWN TOYOTA','BNSF','SI','USA','RAM','73RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,151,'81','81','NAFTA','CENTERVILLE RAIL HEAD','UP','NO','USA','RAM','81RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,152,'HD81','81','NAFTA','CENTERVILLE RAIL HEAD','UP','SI','USA','RAM','81RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,153,'82','82','NAFTA','TOLEDO RAIL HEAD','BNSF','NO','USA','RAM','82RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,154,'82','82','NAFTA','TOLEDO RAIL HEAD','UP','NO','USA','RAM','82RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,155,'82B','82','NAFTA','FOSTORIA MIXING CENTER','BNSF','NO','USA','RAM','82RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,156,'HD82','82','NAFTA','TOLEDO RAIL HEAD','BNSF','SI','USA','RAM','82RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,157,'HD82','82','NAFTA','TOLEDO RAIL HEAD','BNSF','SI','USA','RAM','82RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,158,'59','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,159,'83','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,160,'54','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,161,'54B','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,162,'54C','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,163,'54D','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,164,'53','83','NAFTA','ORILLIA','BNSF','NO','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,165,'HD54','83','NAFTA','ORILLIA','BNSF','SI','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,166,'HD54B','83','NAFTA','ORILLIA','BNSF','SI','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,167,'HD54C','83','NAFTA','ORILLIA','BNSF','SI','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,168,'HD54D','83','NAFTA','ORILLIA','BNSF','SI','USA','RAM','83RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,169,'86','86','NAFTA','LAWRENCEVILLE RAMP','UP','NO','USA','RAM','86RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,170,'HD86','86','NAFTA','LAWRENCEVILLE RAMP','UP','SI','USA','RAM','86RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,171,'88','88','NAFTA','PORTLAND','BNSF','NO','USA','RAM','88RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,172,'HD95','95','NAFTA','Ayer','JCC','SI','USA','RAM','95RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,173,'96B','96','NAFTA','MECHANICVILLE RAMP','BNSF','NO','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,174,'96C','96','NAFTA','MECHANICVILLE RAMP','BNSF','NO','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,175,'96L','96','NAFTA','MECHANICVILLE RAMP','BNSF','NO','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,176,'96M','96','NAFTA','MECHANICVILLE RAMP','BNSF','NO','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,177,'HD96B','96','NAFTA','MECHANICVILLE RAMP','BNSF','SI','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,178,'HD96C','96','NAFTA','MECHANICVILLE RAMP','BNSF','SI','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,179,'HD96L','96','NAFTA','MECHANICVILLE RAMP','BNSF','SI','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,180,'HD96M','96','NAFTA','MECHANICVILLE RAMP','BNSF','SI','USA','RAM','96RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,181,'HD96','96','NAFTA','MECHANICVILLE RAMP','JCC','SI','USA','RAM','96RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,182,'98','98','NAFTA','EL MIRAGE, AZ','BNSF','NO','USA','RAM','98RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,183,'98C','98','NAFTA','EL MIRAGE, AZ','BNSF','NO','USA','RAM','98RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,184,'98','98','NAFTA','EL MIRAGE, AZ','BNSF','NO','USA','RAM','98RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,185,'HD98','98','NAFTA','EL MIRAGE, AZ','BNSF','SI','USA','RAM','98RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,186,'HD98','98','NAFTA','EL MIRAGE, AZ','BNSF','SI','USA','RAM','98RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,187,'99','99','NAFTA','PORT ALLEN,LA','BNSF','NO','USA','RAM','99RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,188,'99','99','NAFTA','PORT ALLEN,LA','BNSF','NO','USA','RAM','99RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,189,'HD99','99','NAFTA','PORT ALLEN,LA','BNSF','SI','USA','RAM','99RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,190,'HD99','99','NAFTA','PORT ALLEN,LA','BNSF','SI','USA','RAM','99RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,191,'A8','A8','NAFTA','DARTMOUTH,NS','BNSF','NO','Canada','RAM','A8RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,192,'HDA8','A8','NAFTA','DARTMOUTH,NS','BNSF','SI','Canada','RAM','A8RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,193,'A9','A9','NAFTA','MONCTON CANADA','BNSF','NO','Canada','RAM','A9RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,194,'HDA9','A9','NAFTA','MONCTON CANADA','BNSF','SI','Canada','RAM','A9RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,195,'D3','D3','NAFTA','JOFFRE, QC','BNSF','NO','Canada','RAM','D3RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,196,'A3','D3','NAFTA','JOFFRE, QC','BNSF','NO','Canada','RAM','D3RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,197,'HDD3','D3','NAFTA','MONCTON CANADA','BNSF','SI','Canada','RAM','D3RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,198,'A1','D4','NAFTA','Halifax MultiMFG','BNSF','NO','Canada','RAM','D4RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,199,'D4','D4','NAFTA','MONTREAL CHRYSLER','BNSF','NO','Canada','RAM','D4RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,200,'HDA1','D4','NAFTA','Halifax MultiMFG','BNSF','SI','Canada','RAM','D4RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,201,'HDD4','D4','NAFTA','MONTREAL CHRYSLER','BNSF','SI','Canada','RAM','D4RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,202,'E1','E1','NAFTA','WINNIPEG','UP','NO','Canada','RAM','E1RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,203,'HDE1','E1','NAFTA','WINNIPEG','UP','SI','Canada','RAM','E1RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,204,'F2','F3','NAFTA','CONCORD KEELE CHRYSLER','XKSM','NO','Canada','RAM','F3RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,205,'F3','F3','NAFTA','CONCORD KEELE CHRYSLER','XKSM','NO','Canada','RAM','F3RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,206,'HDF3','F3','NAFTA','CONCORD KEELE CHRYSLER','XKSM','SI','Canada','RAM','F3RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,207,'S1','S1','NAFTA','SASKATOON RAILHEAD','UP','NO','Canada','RAM','S1RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,208,'HDS1','S1','NAFTA','SASKATOON RAILHEAD','UP','SI','Canada','RAM','S1RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,209,'F5','F5','NAFTA','AGINCOURT, ON','XKSM','NO','Canada','RAM','F5RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,210,'F5B','F5','NAFTA','AGINCOURT, ON','XKSM','NO','Canada','RAM','F5RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,211,'HDF5','F5','NAFTA','AGINCOURT, ON','XKSM','SI','Canada','RAM','F5RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,212,'HDF5B','F5','NAFTA','AGINCOURT, ON','XKSM','SI','Canada','RAM','F5RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,213,'J4','J4','NAFTA','CALGARY,AB','XKSM','NO','Canada','RAM','J4RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,214,'HDJ4','J4','NAFTA','CALGARY,AB','XKSM','SI','Canada','RAM','J4RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,215,'HDJ4W','J4','NAFTA','CALGARY,AB','XKSM','SI','Canada','RAM','J4RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,216,'J4W','J4','NAFTA','CALGARY,AB','XKSM','NO','Canada','RAM','J4RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,217,'L1','L1','NAFTA','VANCOUVER','XKSM','NO','Canada','RAM','L1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,218,'L1F','L1','NAFTA','VANCOUVER','XKSM','NO','Canada','RAM','L1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,219,'HDL1','L1','NAFTA','VANCOUVER','XKSM','SI','Canada','RAM','L1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,220,'HDL1F','L1','NAFTA','VANCOUVER','XKSM','SI','Canada','RAM','L1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,221,'W1','W1','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,222,'W1X','W1','NAFTA','EDMONTON CHRYSLER','XKSM','NO','USA','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,223,'W1Y','W1','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,224,'HDW1','W1','NAFTA','EDMONTON CHRYSLER','XKSM','SI','Canada','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,225,'HDW1W','W1','NAFTA','EDMONTON CHRYSLER','XKSM','SI','Canada','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,226,'W1W','W1','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W1RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,227,'W2','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,228,'W2X','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,229,'W2Y','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,230,'HDW2','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,231,'HDW2X','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,232,'HDW2Y','W2','NAFTA','EDMONTON CHRYSLER','XKSM','NO','Canada','RAM','W2RAM','Rail Kansas','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,233,'M2','M2','Domestic','Domestic',NULL,'NO','Domestico','RAM','M2RAM','Domestico','Domestico','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,234,'M1','M2','Domestic','Domestic',NULL,'NO','Domestico','RAM','M2RAM','Domestico','Domestico','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,235,'M3','M2','Domestic','Domestic',NULL,'NO','Domestico','RAM','M2RAM','Domestico','Domestico','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,236,'M4','M2','Domestic','Domestic',NULL,'NO','Domestico','RAM','M2RAM','Domestico','Domestico','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,237,'17','17','NAFTA','BAYVIEW','JCC','NO','USA','RAM','17RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,238,'17B','17','NAFTA','BAYVIEW','JCC','NO','USA','RAM','17RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,239,'17','17','NAFTA','BAYVIEW','JCC','NO','USA','RAM','17RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,240,'17B','17','NAFTA','BAYVIEW','JCC','NO','USA','RAM','17RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,241,'HD17','17','NAFTA','BAYVIEW','JCC','SI','USA','RAM','17RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,242,'19','19','NAFTA','REISOR LA','BNSF','NO','USA','RAM','19RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,243,'19M','19','NAFTA','REISOR LA','BNSF','NO','USA','RAM','19RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,244,'19','19','NAFTA','REISOR LA','BNSF','NO','USA','RAM','19RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,245,'HD19','19','NAFTA','REISOR LA','BNSF','SI','USA','RAM','19RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,246,'HD19','19','NAFTA','REISOR LA','BNSF','SI','USA','RAM','19RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,247,'31N','31','NAFTA','Vascor Laredo','BNSF','NO','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,248,'31K','31','NAFTA','Vascor Laredo','BNSF','NO','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,249,'31L','31','NAFTA','Vascor Laredo','BNSF','NO','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,250,'31M','31','NAFTA','Vascor Laredo','BNSF','NO','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,251,'HD31K','31','NAFTA','Vascor Laredo','BNSF','SI','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,252,'HD31L','31','NAFTA','Vascor Laredo','BNSF','SI','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,253,'HD31N','31','NAFTA','Vascor Laredo','BNSF','SI','USA','Promaster','31Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,254,'50','50','NAFTA','MCCALLA AL','BNSF','NO','USA','RAM','50RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,255,'50','50','NAFTA','MCCALLA AL','BNSF','NO','USA','RAM','50RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,256,'HD50','50','NAFTA','MCCALLA AL','BNSF','SI','USA','RAM','50RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,257,'HD50','50','NAFTA','MCCALLA AL','BNSF','SI','USA','RAM','50RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,258,'54','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,259,'54B','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,260,'54B','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,261,'54D','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,262,'54D','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,263,'54','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,264,'54B','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,265,'54D','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,266,'54C','53','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,267,'HD54','53','NAFTA',NULL,'BNSF','SI','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,268,'HD54B','53','NAFTA',NULL,'BNSF','SI','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,269,'HD54C','53','NAFTA',NULL,'BNSF','SI','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,270,'HD54D','53','NAFTA',NULL,'BNSF','SI','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,271,'54','54','NAFTA',NULL,'BNSF','NO','USA','Promaster','53Promaster','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,272,'63','63','NAFTA','TWIN OAKS','JCC','NO','USA','RAM','63RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,273,'63','63','NAFTA','TWIN OAKS','JCC','NO','USA','RAM','63RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,274,'HD63','63','NAFTA','TWIN OAKS','JCC','SI','USA','RAM','63RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,275,'66A','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,276,'66L','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,277,'66L','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,278,'66','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,279,'66','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,280,'66L','66','NAFTA','DOREMUS','JCC','NO','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,281,'HD66A','66','NAFTA','DOREMUS','JCC','SI','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,282,'HD66','66','NAFTA','DOREMUS','JCC','SI','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,283,'HD66L','66','NAFTA','DOREMUS','JCC','SI','USA','RAM','66RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,284,'67','67','NAFTA','Pearland (Houston)','BNSF','NO','USA','RAM','67RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,285,'67','67','NAFTA','Pearland (Houston)','BNSF','NO','USA','RAM','67RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,286,'HD67','67','NAFTA','Pearland (Houston)','BNSF','SI','USA','RAM','67RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,287,'HD67','67','NAFTA','Pearland (Houston)','BNSF','SI','USA','RAM','67RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,288,'75','75','NAFTA','Amarillo, TX','BNSF','NO','USA','RAM','75RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,289,'75','75','NAFTA','Laredo','BNSF','NO','USA','RAM','75RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,290,'HD75','75','NAFTA','Laredo','BNSF','SI','USA','RAM','75RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,291,'HD75','75','NAFTA','Laredo','BNSF','SI','USA','RAM','75RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,292,'87','87','NAFTA','SAN ANTONIO TX','BNSF','NO','USA','RAM','87RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,293,'87','87','NAFTA','SAN ANTONIO TX','BNSF','NO','USA','RAM','87RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,294,'HD87','87','NAFTA','SAN ANTONIO TX','BNSF','SI','USA','RAM','87RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,295,'HD87','87','NAFTA','SAN ANTONIO TX','BNSF','SI','USA','RAM','87RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,296,'95','95','NAFTA','Ayer','JCC','NO','USA','RAM','95RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,297,'95','95','NAFTA','Ayer','JCC','NO','USA','RAM','95RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,298,'96','96','NAFTA','MECHANICVILLE RAMP','JCC','NO','USA','RAM','96RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,299,'96','96','NAFTA','MECHANICVILLE RAMP','JCC','NO','USA','RAM','96RAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,300,'10PRO','10PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','10PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,301,'10PRO','10PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','10PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,302,'10PRO','10PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','10PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,303,'11PRO','11PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','11PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,304,'11PRO','11PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','11PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,305,'11PRO','11PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','11PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,306,'15PRO','15PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','15PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,307,'15PRO','15PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','15PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,308,'15PRO','15PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','15PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,309,'16PRO','16PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','16PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,310,'16PRO','16PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','16PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,311,'16PRO','16PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','16PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,312,'1BPRO','1BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','1BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,313,'2BPRO','2BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,314,'2BPRO','2BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,315,'2BPRO','2BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,316,'2GPRO','2GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,317,'2GPRO','2GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,318,'2GPRO','2GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,319,'2JPRO','2JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,320,'2JPRO','2JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,321,'2JPRO','2JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,322,'2NPRO','2NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,323,'2NPRO','2NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,324,'2NPRO','2NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','2NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,325,'30PRO','30PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','30PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,326,'3GPRO','3GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,327,'3GPRO','3GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,328,'3GPRO','3GPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3GPROPromaster','Truck','Lazaro Cardenas','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,329,'3JPRO','3JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,330,'3JPRO','3JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,331,'3JPRO','3JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,332,'3NPRO','3NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,333,'3NPRO','3NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,334,'3NPRO','3NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','3NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,335,'3PRO','3PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','3PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,336,'3PRO','3PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','3PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,337,'3PRO','3PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','3PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,338,'4BPRO','4BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,339,'4BPRO','4BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,340,'4BPRO','4BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,341,'4JPRO','4JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,342,'4JPRO','4JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,343,'4JPRO','4JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','4JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,344,'4PRO','4PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','4PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,345,'4PRO','4PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','4PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,346,'4PRO','4PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','4PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,347,'5BPRO','5BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,348,'5BPRO','5BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,349,'5BPRO','5BPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5BPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,350,'5NPRO','5NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,351,'5NPRO','5NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,352,'5NPRO','5NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','5NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,353,'5PRO','5PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','5PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,354,'5PRO','5PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','5PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,355,'5PRO','5PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','5PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,356,'5TX','5TX','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','SI','CANADA','RAM','5TXRAM','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,357,'5PRO','5TX','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','CANADA','RAM','5TXRAM','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,358,'HD5TX','5TX','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','SI','CANADA','RAM','5TXRAM','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,359,'6JPRO','6JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,360,'6JPRO','6JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,361,'6JPRO','6JPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6JPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,362,'6NPRO','6NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,363,'6NPRO','6NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,364,'6NPRO','6NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','6NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,365,'6PRO','6PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','6PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,366,'6PRO','6PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','6PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,367,'6PRO','6PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','6PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,368,'6TX','6TX','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','CANADA','RAM','6TXRAM','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,369,'HD6TX','6TX','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','SI','CANADA','RAM','6TXRAM','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,370,'7NPRO','7NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','7NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,371,'7NPRO','7NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','7NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,372,'7NPRO','7NPRO','NAFTA','Truck','TLE','NO','USA','Promaster','7NPROPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,373,'7PRO','7PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','7PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,374,'7PRO','7PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','7PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,375,'7PRO','7PRO','NAFTA','Laredo','Swift','NO','USA','Promaster','7PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,376,'8PRO','8PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','8PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,377,'8PRO','8PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','8PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,378,'8PRO','8PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','8PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,379,'9PRO','9PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','9PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,380,'9PRO','9PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','9PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,381,'9PRO','9PRO','NAFTA','Vascor Laredo','MULTIPLE CARRIERS','NO','USA','Promaster','9PROPromaster','Truck','Laredo','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,382,'A1','A1','NAFTA','Halifax MultiMFG','TLE','NO','Canada','PROMASTER','A1PROMASTER','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,383,'A1','A1','NAFTA','Halifax MultiMFG','TLE','NO','Canada','Promaster','A1Promaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,384,'A1','A1','NAFTA','Halifax MultiMFG','TLE','NO','Canada','Promaster','A1Promaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,385,'HDA1','A1','NAFTA','Halifax MultiMFG','TLE','SI','Canada','Promaster','A1Promaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,386,'HDA1','A1','NAFTA','Halifax MultiMFG','TLE','SI','Canada','PROMASTER','A1PROMASTER','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,387,'HDA1','A1','NAFTA','Halifax MultiMFG','TLE','SI','Canada','Promaster','A1Promaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,388,'AR','AR','BUX','Altamira','JCC','NO','LATAM','RAM','ARRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,389,'AR','AR','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','Promaster','ARPromaster','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,390,'HDAR','AR','BUX','Altamira','JCC','SI','LATAM','RAM','ARRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,391,'BR','BR','BUX','Truck','JCC','NO','BUX','RAM','BRRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,392,'BR','BR','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','Promaster','BRPromaster','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,393,'BR','BR','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','Promaster','BRPromaster','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,394,'KW','KW','BUX','ALTAMIRA','JCC','NO','LATAM','RAM','KWRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,395,'HDKW','KW','BUX','ALTAMIRA','JCC','SI','LATAM','RAM','KWRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,396,'NANTU','NANTU','BUX','Altamira','JCC','NO','BUX','RAM','NANTURAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,397,'PR','PR','NAFTA','Jacksonville','JCC','NO','USA','RAM','PRRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,398,'PR','PR','NAFTA','Jacksonville','TLE','NO','USA','Promaster','PRPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,399,'PR','PR','NAFTA','Jacksonville','TLE','NO','USA','Promaster','PRPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,400,'PR','PR','NAFTA','Jacksonville','TLE','NO','USA','Promaster','PRPromaster','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,401,'HDPR','PR','NAFTA','Jacksonville','JCC','SI','USA','RAM','PRRAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,402,'HDSA','SA','BUX','VERACRUZ','JCC','SI','LATAM','RAM','SARAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,403,'SA','SA','BUX','VERACRUZ','JCC','NO','LATAM','RAM','SARAM','Truck','Altamira','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,404,'CL','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,405,'AJ','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,406,'ANT','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,407,'IL','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,408,'UE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,409,'HN','VZ','NAFTA','JACKSONVILLE','UP','NO','USA','RAM','VZRAM','Truck','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,410,'AE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,411,'BA','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,412,'BO','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,413,'CO','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,414,'CR','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,415,'DD','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,416,'HDAE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,417,'HDAJ','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,418,'HDANT','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,419,'HDBO','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,420,'HDCL','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,421,'HDCO','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,422,'HDCR','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,423,'HDIL','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,424,'HDPE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,425,'HDQA','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,426,'HDUE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','SI','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,427,'OM','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,428,'PE','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,429,'PY','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,430,'QA','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,431,'UY','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,432,'VR','VZ','BUX','Verificar Destino en Solicitud de BUX','Verificar Destino en Solicitud de BUX','NO','BUX','RAM','VZRAM','Truck','BUX','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,433,'0','0','Storage','Storage','Storage','NO','Storage','RAM','UTILRAM','Upfit Required','Upfit Required','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,434,'UTIL','UTIL','NAFTA','Storage','Storage','NO','Storage','RAM','UTILRAM','Upfit Required','Upfit Required','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,435,'99509','UTIL','NAFTA','Storage','Storage','NO','Storage','RAM','UTILRAM','Upfit Required','Upfit Required','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,436,'FPMEX','UTIL','NAFTA','Storage','Storage','NO','Storage','RAM','UTILRAM','Upfit Required','Upfit Required','20260731_019_seed_official_rail_route_catalog'),
(@official_catalog_version_id,437,'40F','40','NAFTA','SALT LAKE CITY MM','UP','NO','USA','RAM','40RAM','Rail','Saltillo Rail - USA','20260731_019_seed_official_rail_route_catalog')
ON DUPLICATE KEY UPDATE
    route_code=VALUES(route_code),route_king=VALUES(route_king),market=VALUES(market),
    shipping_destination=VALUES(shipping_destination),carrier=VALUES(carrier),
    heavy_duty=VALUES(heavy_duty),usa_canada=VALUES(usa_canada),
    production_plant=VALUES(production_plant),rc_plant=VALUES(rc_plant),
    load_by=VALUES(load_by),border_crossing=VALUES(border_crossing);

COMMIT;
