<?php

return [
    ['original' => 'Equipo', 'internal' => 'equipo'],
    ['original' => 'Estación', 'internal' => 'estacion'],
    ['original' => 'Vía', 'internal' => 'via'],
    ['original' => 'Sec', 'internal' => 'sec'],
    ['original' => 'TipodeEmbarque', 'internal' => 'tipo_de_embarque'],
    ['original' => 'EntregarA', 'internal' => 'entregar_a'],
    ['original' => 'NúmerodeGuía', 'internal' => 'numero_de_guia'],
    ['original' => 'NumerodeBOL', 'internal' => 'numero_de_bol'],
    ['original' => 'TipoEspecíficodeEquipo', 'internal' => 'tipo_especifico_de_equipo'],
    ['original' => 'TipoGenéricodeEquipo', 'internal' => 'tipo_generico_de_equipo'],
    ['original' => 'TipoEspecíficodeEquipo', 'internal' => 'tipo_especifico_de_equipo_2'],
    ['original' => 'L/E', 'internal' => 'l_e'],
    ['original' => 'Producto', 'internal' => 'producto'],
    ['original' => 'GrupodeProducto', 'internal' => 'grupo_de_producto'],
    ['original' => 'FerrocarrilActual', 'internal' => 'ferrocarril_actual'],
    ['original' => 'ÚltimoMovimiento', 'internal' => 'ultimo_movimiento'],
    ['original' => 'EstaciondeÚltimoMovimiento', 'internal' => 'estacion_de_ultimo_movimiento'],
    ['original' => 'FechadeÚltimoMovimiento', 'internal' => 'fecha_de_ultimo_movimiento'],
    ['original' => 'ETA', 'internal' => 'eta'],
    ['original' => 'ETI', 'internal' => 'eti'],
    ['original' => 'Estatus del Viaje', 'internal' => 'estatus_del_viaje'],
    ['original' => 'Excepción', 'internal' => 'excepcion'],
    ['original' => 'Ferrocarril', 'internal' => 'ferrocarril'],
    ['original' => 'DíaRemitido', 'internal' => 'dia_remitido'],
    ['original' => 'EstaciondeOrigen', 'internal' => 'estacion_de_origen'],
    ['original' => 'Remitente', 'internal' => 'remitente'],
    ['original' => 'EstaciondeDestino', 'internal' => 'estacion_de_destino'],
    ['original' => 'Consignatario', 'internal' => 'consignatario'],
    ['original' => 'Ruta', 'internal' => 'ruta'],
    ['original' => 'IndicadordeActividad', 'internal' => 'indicador_de_actividad'],
    ['original' => 'Disponible', 'internal' => 'disponible'],
    ['original' => 'Destinoenlínea', 'internal' => 'destino_en_linea'],
    ['original' => 'EstatusdeSituado', 'internal' => 'estatus_de_situado'],
    ['original' => 'FechadeSituado', 'internal' => 'fecha_de_situado'],
    ['original' => 'LongituddeCarro', 'internal' => 'longitud_de_carro'],
    ['original' => 'TonNeta', 'internal' => 'ton_neta'],
    ['original' => 'Sobrepeso', 'internal' => 'sobrepeso'],
    ['original' => 'LímitedeCarga', 'internal' => 'limite_de_carga'],
    ['original' => 'PesoTotaldelCarro', 'internal' => 'peso_total_del_carro'],
    ['original' => 'IDdeTren', 'internal' => 'id_de_tren'],
];
