<?php
declare(strict_types=1);
namespace App\Controllers\ControlEscaneres;
use App\Domain\ControlEscaneres\{BatteryPercentage,IncidentSeverity,ScannerCode,ScannerFolio,ScannerStatus};
use App\DTO\ControlEscaneres\{IncidentResolutionData,IncidentSeverityChangeData,MaintenanceCommandData,ScannerCreateData,ScannerIncidentCreateData,ScannerInspectionDetailData,ScannerMovementCreateData,ScannerReceptionData,ScannerUpdateData};
use App\Factories\ControlEscaneresServiceFactory;
use App\Exceptions\ControlEscaneres\{DuplicateScannerCodeException,DuplicateScannerIdentityException,InvalidBusinessActorException,ScannerRegistrationValidationException};
use App\Presentation\ControlEscaneres\SensitiveScannerDataPresenter;
use App\Presentation\ControlEscaneres\ScannerDashboardViewModelFactory;
use App\Security\ControlEscaneres\{AuthenticatedActorProviderInterface,CsrfTokenManagerInterface};
use App\Services\ControlEscaneres\Shared\ScannerStateMachine;
use App\Services\ControlEscaneres\Import\{ScannerImportStagingStore,ScannerInventoryExcelPreviewer};
use App\Services\ControlEscaneres\Qr\ScannerQrContentNormalizer;
use App\Support\ControlEscaneres\{BusinessRequestContextFactory,ControlEscaneresErrorMapper,FlashMessageStore};
use App\ViewModels\ControlEscaneres\{ScannerDeliveryFormViewModel,ScannerIncidentFormViewModel,ScannerMaintenanceFormViewModel,ScannerReceptionFormViewModel};
use App\Validators\ControlEscaneres\ScannerRegistrationValidator;
final class ControlEscaneresWebController
{
    private const COMPONENTS=['bateria','pantalla','touch','botones','lector','wifi','datos_moviles','accesorios'];
    public function __construct(private ControlEscaneresServiceFactory$factory,private AuthenticatedActorProviderInterface$actors,private CsrfTokenManagerInterface$csrf,private BusinessRequestContextFactory$contexts,private FlashMessageStore$flash,private ControlEscaneresErrorMapper$errors){}
    public function dispatch(array$query,array$post,array$files,string$method):void{$action=(string)($query['accion']??'');if($action==='resolver-equipo'){$this->resolveScanner($method==='POST'?$post:$query);return;}if($action==='resolver-qr'){$this->resolveQr($method==='POST'?$post:$query,$query);return;}$section=trim((string)($query['seccion']??'dashboard'));$allowed=['dashboard','catalogo','expediente','entrega','recepcion','incidencias','mantenimiento','historial','reporte','reportes','areas','importar-inventario','registrar','editar','baja','reactivar','qr','pdf','evidencia','reporte-exportar'];if(!in_array($section,$allowed,true)){header('Location: '.(defined('BASE_URL')?BASE_URL:'').'/index.php?modulo=control-escaneres&seccion=catalogo',true,302);return;}if($method==='POST'){$this->post($section,$post,$files);return;}$this->get($section,$query);}
    private function resolveScanner(array$input):void
    {
        header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
        try{$this->actors->getActor();$code=trim((string)($input['codigo']??''));$mode=trim((string)($input['modo']??'automatico'));if(!in_array($mode,['automatico','entrega','recepcion'],true))throw new\InvalidArgumentException('Modo de búsqueda inválido.');if($code===''||mb_strlen($code)>255)throw new\InvalidArgumentException('Escribe un código válido.');$scanner=$this->factory->scanners()->resolveIdentifier($code);$result=$this->resolution($scanner,'No se encontró un escáner con ese código.');$result['requested_mode']=$mode;echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
        }catch(\Throwable$e){http_response_code(400);echo json_encode(['ok'=>false,'message'=>$e instanceof \InvalidArgumentException?$e->getMessage():'No fue posible localizar el equipo.'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
    }
    private function resolveQr(array$input,array$query):void
    {
        header('Cache-Control: no-store');$json=(($query['formato']??'')==='json')||str_contains(strtolower((string)($_SERVER['HTTP_ACCEPT']??'')),'application/json');
        try{$this->actors->getActor();$normalized=(new ScannerQrContentNormalizer())->normalize((string)($input['codigo']??''));$scanner=$normalized['scanner_id']!==null?$this->factory->scanners()->resolvePublicId((int)$normalized['scanner_id']):$this->factory->scanners()->resolveIdentifier((string)$normalized['identifier']);$result=$this->resolution($scanner,'QR no reconocido.');$result['qr_antiguo']=(bool)$normalized['legacy'];if($json){header('Content-Type: application/json; charset=UTF-8');echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return;}if(!$result['ok']){$this->renderQrMessage((string)$result['message'],400);return;}header('Location: '.$result['redirect_url'],true,302);
        }catch(\InvalidArgumentException$e){if($json){http_response_code(400);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return;}$this->renderQrMessage($e->getMessage(),400);}catch(\Throwable$e){error_log('ControlEscaneres QR: '.$e->getMessage());if($json){http_response_code(500);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>false,'message'=>'No fue posible resolver el QR.'],JSON_UNESCAPED_UNICODE);return;}$this->renderQrMessage('No fue posible resolver el QR.',500);}
    }
    private function resolution(?array$scanner,string$notFound):array
    {
        if($scanner===null)return['ok'=>false,'message'=>$notFound];$id=(int)$scanner['id'];$hasOpen=$this->factory->movements()->hasOpenMovement($id);$state=(string)$scanner['estado'];$active=(bool)$scanner['activo'];$public=['id'=>$id,'codigo'=>(string)$scanner['codigo'],'estado'=>$state,'activo'=>$active];if(!$active||in_array($state,['pendiente_reparacion','mantenimiento','baja_definitiva','extraviado','eliminado'],true))return['ok'=>false,'scanner'=>$public,'tiene_entrega_activa'=>$hasOpen,'message'=>'El equipo no está operativo. Estado: '.str_replace('_',' ',$state).'.'];if($hasOpen)$action='recepcion';elseif($state==='disponible')$action='entrega';else return['ok'=>false,'scanner'=>$public,'tiene_entrega_activa'=>false,'message'=>'El estado del equipo no coincide con una entrega activa. Revisa su expediente.'];return['ok'=>true,'scanner'=>$public,'tiene_entrega_activa'=>$hasOpen,'accion_recomendada'=>$action,'redirect_url'=>(defined('BASE_URL')?BASE_URL:'').'/index.php?modulo=control-escaneres&seccion='.$action.'&scanner_id='.$id];
    }
    private function renderQrMessage(string$message,int$status):void{http_response_code($status);header('Content-Type: text/html; charset=UTF-8');$safe=htmlspecialchars($message,ENT_QUOTES,'UTF-8');$back=htmlspecialchars((defined('BASE_URL')?BASE_URL:'').'/index.php?modulo=control-escaneres&seccion=catalogo',ENT_QUOTES,'UTF-8');echo'<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Control de Escáneres</title><body><main><h1>No fue posible continuar</h1><p>'.$safe.'</p><a href="'.$back.'">Volver al catálogo</a></main></body></html>';}
    private function get(string$section,array$query):void
    {
        try{$messages=$this->flash->consume();$id=max(0,(int)($query['scanner_id']??0));if($section==='qr'){$this->renderQr($id,$query);return;}if($section==='pdf'){$this->actors->getActor();$this->renderPdf(max(0,(int)($query['movement_id']??0)));return;}if($section==='evidencia'){$this->actors->getActor();$this->renderEvidence(max(0,(int)($query['evidence_id']??0)));return;}if($section==='reporte-exportar'){$this->actors->getActor();$this->renderReport($query);return;}
            if($section==='dashboard'){$dashboardViewModel=(new ScannerDashboardController($this->factory->dashboard(),$this->factory->businessClock(),new ScannerDashboardViewModelFactory()))->index(isset($query['rango'])?(string)$query['rango']:null,defined('BASE_URL')?BASE_URL:'');}
            elseif($section==='catalogo'){$catalogViewModel=(new ScannerCatalogController($this->factory->catalog(),new SensitiveScannerDataPresenter()))->index($query,$messages);$catalogOrganizationalAreas=$this->factory->scanners()->organizationalAreas();}
            elseif($section==='importar-inventario'){$importCsrfToken=$this->csrf->token();}
            elseif($section==='registrar'){$registrationCsrfToken=$this->csrf->token();$registrationMessages=$messages;$registrationForm=$this->flash->consumeForm('registrar');$registrationAreas=array_values(array_filter($this->factory->areas()->listWithMetrics(),static fn(array$area):bool=>(bool)$area['activo']));$registrationOrganizationalAreas=$this->factory->scanners()->organizationalAreas();}
            elseif($section==='areas'){$areas=$this->factory->areas()->listWithMetrics();$areaCsrfToken=$this->csrf->token();$areaMessages=$messages;}
            elseif(in_array($section,['reporte','reportes'],true)){$report=$this->factory->reports()->generate($query);$reportAreas=$this->factory->areas()->listWithMetrics();}
            elseif($section==='editar'){$scannerEdit=$id?$this->factory->scanners()->details($id):null;$organizationalAreas=$this->factory->scanners()->organizationalAreas();$editCsrfToken=$this->csrf->token();}
            elseif(in_array($section,['baja','reactivar'],true)){$scannerToggle=$id?$this->factory->scanners()->details($id):null;$toggleAction=$section;$toggleCsrfToken=$this->csrf->token();}
            elseif($section==='entrega'){$s=$id?$this->factory->scanners()->findById($id):null;$valid=$s!==null&&$s->active&&$s->status->value==='disponible';$deliveryMessages=$messages;if($id>0&&!$valid)$deliveryMessages[]=['type'=>'warning','message'=>$s===null?'El escáner solicitado no existe.':'El escáner no está disponible para entrega. Estado: '.$s->status->value.'.'];$deliveryForm=new ScannerDeliveryFormViewModel($valid?$s->id:null,$valid?$s->code->value:null,$s?->status->value,$this->csrf->token(),self::COMPONENTS,$deliveryMessages);}
            elseif($section==='recepcion'){$receptionPending=$this->pendingReceptions((string)($query['q']??''));$s=$id?$this->factory->scanners()->findById($id):null;$scannerDetails=$s?$this->factory->scanners()->details($s->id):null;$m=$s?$this->factory->movements()->findOpenByScannerId($s->id):null;$delivery=$m?$this->factory->inspections()->findByMovementAndType($m->id,new \App\Domain\ControlEscaneres\InspectionType('entrega')):null;$deliveryDetails=$delivery?$this->factory->inspections()->listDetailsByInspectionId($delivery->id):[];$deliveryPhotos=$delivery?array_values(array_filter($this->factory->evidence()->listByInspectionId($delivery->id),static fn($e)=>str_starts_with($e->type,'fotografia_'))):[];$receptionForm=new ScannerReceptionFormViewModel($s?->id,$s?->code->value,$m?->id,$m?->personaEntregaNombre,$m?->entregadoAt->format('Y-m-d H:i:s.u'),$this->csrf->token(),self::COMPONENTS,$messages,$deliveryDetails,$delivery?->battery?->value,$delivery?->rating,$delivery?->observations,$deliveryPhotos,$scannerDetails['tag_original']??null,$m?->numeroEmpleado,$m?->areaNombre,$m?->supervisorNombre,$m?->responsableEntregaNombre,$m?->turno);}
            elseif($section==='incidencias'){$s=$id?$this->factory->scanners()->findById($id):null;$m=$s?$this->factory->movements()->findOpenByScannerId($s->id):null;$list=$s?$this->factory->incidents()->listByScannerId($s->id):[];$allowed=$s?array_map(fn($x)=>$x->value,(new ScannerStateMachine())->allowedTransitionsFrom($s->status)):[];$followUps=[];foreach($list as$incident)$followUps[$incident->id]=$this->factory->incidents()->listFollowUps($incident->id);$incidentForm=new ScannerIncidentFormViewModel($s?->id,$s?->code->value,$m?->id,$list,$allowed,$this->csrf->token(),$messages,$followUps);}
            elseif($section==='mantenimiento'){$s=$id?$this->factory->scanners()->findById($id):null;$allowed=$s?array_map(fn($x)=>$x->value,(new ScannerStateMachine())->allowedTransitionsFrom($s->status)):[];$maintenanceForm=new ScannerMaintenanceFormViewModel($s?->id,$s?->code->value,$s?->status->value,$allowed,$this->csrf->token(),$messages,$s?$this->factory->maintenanceRecords()->listByScannerId($s->id):[]);}
            elseif($section==='expediente'&&$id>0){$historyViewModel=(new ScannerHistoryController($this->factory->history(),$this->factory->auditQuery(),new SensitiveScannerDataPresenter()))->show($id,$messages);}
            if($section==='recepcion'&&isset($s)&&$s!==null&&!$s->active){unset($receptionForm);$integrationError='El escáner seleccionado está inactivo y no puede recibirse.';}
        }catch(\Throwable$e){$trackingId=bin2hex(random_bytes(8));error_log(sprintf('ControlEscaneres GET [%s]: %s: %s at %s:%d%s%s',$trackingId,get_class($e),$e->getMessage(),$e->getFile(),$e->getLine(),PHP_EOL,$e->getTraceAsString()));$integrationError=$this->errors->message($e);if($integrationError==='No fue posible completar la operación.')$integrationError='No fue posible cargar la información. Intenta nuevamente. Seguimiento: '.$trackingId;}
        require dirname(__DIR__,2).'/Views/inventario/importar.php';
    }
    private function post(string$section,array$post,array$files):void
    {
        try{if(!$this->csrf->validate((string)($post['_csrf']??'')))throw new \DomainException('CSRF');if($section==='importar-inventario'&&($post['operation']??'preview')!=='confirm'){$this->previewImport($files);return;}$actor=$this->actors->getActor();$context=$this->contexts->create();if($section==='importar-inventario'){$result=$this->confirmImport($post,$actor->userId);$this->flash->add('success','Importación terminada: '.$result['inserted'].' equipo(s) insertado(s); '.$result['conflicts_excluded'].' conflicto(s) excluido(s).');$section='catalogo';$this->csrf->rotate();}elseif($section==='areas'){$this->area($post,$actor,$context);$this->flash->add('success','Catálogo de áreas actualizado.');$this->csrf->rotate();}elseif($section==='registrar'){$this->register($post,$files,$actor,$context);$this->flash->add('success','Escáner registrado correctamente.');$section='catalogo';$this->csrf->rotate();}else{$id=$this->positive($post,'scanner_id');
            if($section==='baja'){$this->factory->transactions()->transactional(function()use($id,$actor,$context){$this->factory->scanners()->deactivate($id,$actor->userId);$this->factory->auditService()->record('scanner.deactivate','scanner',$id,['activo'=>true],['activo'=>false],$actor,$context);});$this->flash->add('success','Escáner dado de baja lógica.');$section='catalogo';}
            elseif($section==='reactivar'){$this->factory->transactions()->transactional(function()use($id,$actor,$context){$this->factory->scanners()->reactivate($id,$actor->userId);$this->factory->auditService()->record('scanner.reactivate','scanner',$id,['activo'=>false],['activo'=>true],$actor,$context);});$this->flash->add('success','Escáner reactivado.');$section='catalogo';}
            elseif($section==='editar'){$this->edit($id,$post,$files,$actor,$context);$this->flash->add('success','Escáner actualizado correctamente.');}
            elseif($section==='entrega'){$evidence=$this->operationEvidence($id,'entrega',$post,$files,$actor);try{$result=$this->factory->delivery()->deliver(new ScannerMovementCreateData($id,new ScannerFolio('MOV-20000101-TEMP01'),$this->required($post,'person_name'),$this->required($post,'employee_number'),$this->required($post,'shift'),new \DateTimeImmutable(),$actor,$this->battery($post),$this->rating($post),$this->optional($post,'observations'),$this->details($post),$evidence,$this->required($post,'area'),$this->required($post,'supervisor'),$this->required($post,'responsible_name')),$actor,$context);}catch(\Throwable$e){$this->cleanupEvidence($evidence);throw$e;}$this->flash->add('success','Entrega registrada. Folio: '.$result->movement->folio->value);}
            elseif($section==='recepcion'){$evidence=$this->operationEvidence($id,'recepcion',$post,$files,$actor);try{$result=$this->factory->reception()->receive(new ScannerReceptionData($this->positive($post,'movement_id'),$id,$this->required($post,'receiver_name'),$this->battery($post),$this->rating($post),$this->optional($post,'observations'),$this->details($post),$evidence,responsibleName:$this->required($post,'responsible_name'),confirmSevereDifferences:isset($post['confirm_severe_differences'])),$actor,$context);}catch(\Throwable$e){$this->cleanupEvidence($evidence);throw$e;}$this->flash->add('success','Recepcion registrada. Estado: '.$result->resultingStatus->value);}
            elseif($section==='incidencias'){$this->incident($post,$files,$id,$actor,$context);$this->flash->add('success','Incidencia actualizada correctamente.');}
            elseif($section==='mantenimiento'){$action=$this->required($post,'operation');$target=$action==='return'?$this->validatedTransition($id,(string)($post['resulting_status']??'')):null;$evidence=$this->photoEvidence($id,'mantenimiento',$files,$actor);try{$this->factory->maintenance()->execute(new MaintenanceCommandData($id,$action,$this->required($post,'reason'),$this->optional($post,'observations'),$evidence,resultingStatus:$target,technician:$this->optional($post,'technician'),diagnosis:$this->optional($post,'diagnosis'),cost:$this->optionalFloat($post,'cost'),estimatedDate:$this->optional($post,'estimated_date'),result:$this->optional($post,'result')),$actor,$context);}catch(\Throwable$e){$this->cleanupEvidence($evidence);throw$e;}$this->flash->add('success','Mantenimiento actualizado correctamente.');}
            else throw new \DomainException('Operacion');$this->csrf->rotate();}
        }catch(\Throwable$e){$trackingId=bin2hex(random_bytes(8));error_log(sprintf('ControlEscaneres POST [%s]: %s: %s at %s:%d',$trackingId,get_class($e),$e->getMessage(),$e->getFile(),$e->getLine()));if($section==='registrar'){$validator=new ScannerRegistrationValidator();$values=$e instanceof ScannerRegistrationValidationException?$e->values:$validator->values($post);$fieldErrors=$e instanceof ScannerRegistrationValidationException?$e->errors:[];if($e instanceof DuplicateScannerCodeException)$fieldErrors['code']=$this->errors->message($e);if($e instanceof DuplicateScannerIdentityException&&str_contains($e->getMessage(),'TAG'))$fieldErrors['tag']=$this->errors->message($e);$this->flash->keepForm('registrar',$values,$fieldErrors);if($e instanceof InvalidBusinessActorException)$this->flash->setReturnUrl((defined('BASE_URL')?BASE_URL:'').'/index.php?modulo=control-escaneres&seccion=registrar');}$message=$e->getMessage()==='CSRF'?'La sesión del formulario terminó. Intenta nuevamente.':($e instanceof ScannerRegistrationValidationException?$e->getMessage():$this->errors->message($e));if($message==='No fue posible completar la operación.')$message='No fue posible guardar la operación. Intenta nuevamente. Seguimiento: '.$trackingId;$this->flash->add('error',$message);}
        $url=(defined('BASE_URL')?BASE_URL:'').'/index.php?modulo=control-escaneres&seccion='.rawurlencode($section).((int)($post['scanner_id']??0)>0?'&scanner_id='.(int)$post['scanner_id']:'');header('Location: '.$url,true,303);
    }
    private function previewImport(array$files):void
    {
        $file=$files['inventory_file']??null;if(!is_array($file))throw new\InvalidArgumentException('Selecciona un archivo Excel válido.');
        $staged=$this->importStore()->stage($file);$importToken=$staged['token'];$importPreview=(new ScannerInventoryExcelPreviewer())->preview($staged['path'],$this->factory->catalog()->identities());$importCsrfToken=$this->csrf->token();
        require dirname(__DIR__,2).'/Views/inventario/importar.php';
    }
    private function confirmImport(array$post,int$actorId):array{if(($post['confirm_import']??'')!=='1')throw new\DomainException('Confirma expresamente el dry-run antes de importar.');$token=$this->required($post,'import_token');$store=$this->importStore();$path=$store->resolve($token);$preview=(new ScannerInventoryExcelPreviewer())->preview($path,$this->factory->catalog()->identities());$result=$this->factory->inventoryImporter()->import($preview,defined('BASE_URL')?BASE_URL:'',$actorId);$store->discard($token);return$result;}
    private function importStore():ScannerImportStagingStore{return new ScannerImportStagingStore(dirname(__DIR__,3).'/storage/tmp/control-escaneres-import',$_SESSION);}
    private function register(array$post,array$files,$actor,$context):void{$repo=$this->factory->scanners();$areaId=filter_var($post['area_id']??null,FILTER_VALIDATE_INT);$area=$areaId!==false&&$areaId>0?$this->factory->areas()->findActiveById($areaId):null;$organizationalId=filter_var($post['organizational_area_id']??null,FILTER_VALIDATE_INT);$organizationalArea=null;if($organizationalId!==false&&$organizationalId>0)foreach($repo->organizationalAreas()as$candidate)if((int)$candidate['id']===$organizationalId){$organizationalArea=$candidate+['activo'=>1];break;}$data=(new ScannerRegistrationValidator())->validate($post,$repo->nextCode(),$area,$organizationalArea);$this->factory->registration()->register($data,is_array($files['main_photo']??null)?$files['main_photo']:null,$actor,$context);}
    private function area(array$post,$actor,$context):void{$operation=$this->required($post,'operation');$repo=$this->factory->areas();$id=null;$this->factory->transactions()->transactional(function()use($operation,$post,$repo,$actor,$context,&$id){if($operation==='create')$id=$repo->create($this->required($post,'name'));else{$id=$this->positive($post,'area_id');if($operation==='rename')$repo->rename($id,$this->required($post,'name'));elseif($operation==='deactivate')$repo->deactivate($id);elseif($operation==='reactivate')$repo->reactivate($id);else throw new\DomainException('Operación de área inválida.');}$this->factory->auditService()->record('scanner.area.'.$operation,'scanner_area',$id,[],['name'=>$this->optional($post,'name')],$actor,$context);});}
    private function edit(int$id,array$post,array$files,$actor,$context):void{$status=new ScannerStatus((string)($post['estado']??''));$organizationalRaw=trim((string)($post['area_organizacional_id']??''));$organizationalId=$organizationalRaw===''?null:filter_var($organizationalRaw,FILTER_VALIDATE_INT);if($organizationalId===false||($organizationalId!==null&&$organizationalId<1))throw new\InvalidArgumentException('Área organizacional inválida.');$data=['tag'=>$this->optional($post,'tag_original'),'brand'=>$this->required($post,'marca'),'model'=>$this->required($post,'modelo'),'serial'=>$this->optional($post,'numero_serie'),'imei'=>$this->optional($post,'imei'),'phone'=>$this->optional($post,'telefono'),'iccid'=>$this->optional($post,'iccid'),'network'=>$this->optional($post,'red'),'plan'=>$this->optional($post,'plan'),'activity'=>$this->optional($post,'actividad_habitual'),'area'=>$this->optional($post,'area_habitual'),'location'=>$this->optional($post,'ubicacion'),'age'=>$this->optional($post,'antiguedad_descriptiva'),'observations'=>$this->optional($post,'observaciones')];$stored=null;try{$this->factory->transactions()->transactional(function()use($id,$data,$status,$organizationalId,$files,$actor,$context,&$stored){$repo=$this->factory->scanners();$before=$repo->details($id)??throw new\DomainException('Escáner no encontrado.');$repo->assertIdentityAvailable($id,$data['tag'],$data['serial'],$data['imei'],$data['iccid']);$current=new ScannerStatus((string)$before['estado']);if($current->value!==$status->value)(new ScannerStateMachine())->assertTransition($current,$status);$repo->updateFull($id,$data,$actor->userId);$repo->setOrganizationalArea($id,$organizationalId,$actor->userId);$photo=$files['main_photo']??null;if(is_array($photo)&&($photo['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$stored=$this->factory->evidenceStorage()->upload($photo,$id,'fotografia_principal',$actor);$this->factory->evidence()->create($stored);$repo->setMainPhoto($id,$stored->storagePath,$actor->userId);}$repo->changeStatus($id,$status,$actor->userId);$this->factory->auditService()->record('scanner.update','scanner',$id,['estado'=>$before['estado'],'area_organizacional_id'=>$before['area_organizacional_id']??null],['estado'=>$status->value,'area_organizacional_id'=>$organizationalId,'fotografia_nueva'=>$stored!==null],$actor,$context);});}catch(\Throwable$e){if($stored!==null)$this->factory->evidenceStorage()->remove($stored);throw$e;}}
    private function renderQr(int$id,array$query):void{$qr=$this->factory->qr()->png($id,(int)($query['size']??300));header('Content-Type: '.$qr['mime']);header('Content-Disposition: '.(($query['download']??'')==='1'?'attachment':'inline').'; filename="qr-'.$qr['code'].'.png"');header('X-Content-Type-Options: nosniff');echo$qr['bytes'];}
    private function renderPdf(int$id):void{$pdf=$this->factory->movementPdf()->render($id);header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="'.$pdf['filename'].'"');header('X-Content-Type-Options: nosniff');echo$pdf['bytes'];}
    private function renderEvidence(int$id):void{$evidence=$this->factory->evidence()->findById($id)??throw new\DomainException('Evidencia no encontrada.');$file=$this->factory->evidenceStorage()->read($evidence);header('Content-Type: '.$file['mime']);header('Content-Length: '.(string)$file['size']);header('Content-Disposition: inline; filename="evidencia-'.$id.'.'.match($file['mime']){'image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'}.'"');header('X-Content-Type-Options: nosniff');header('Content-Security-Policy: default-src \'none\'; sandbox');header('Cache-Control: private, no-store');echo$file['bytes'];}
    private function renderReport(array$query):void{$report=$this->factory->reports()->generate($query);$file=($query['formato']??'pdf')==='xlsx'?$this->factory->reports()->xlsx($report):$this->factory->reports()->pdf($report);header('Content-Type: '.$file['mime']);header('Content-Disposition: attachment; filename="'.$file['filename'].'"');header('Content-Length: '.strlen($file['bytes']));header('X-Content-Type-Options: nosniff');echo$file['bytes'];}
    private function pendingReceptions(string$search):array{$search=mb_strtolower(trim($search));$items=[];foreach($this->factory->movements()->listOpen()as$movement){$scanner=$this->factory->scanners()->details($movement->scannerId);if(!is_array($scanner))continue;$haystack=mb_strtolower(implode(' ',[(string)($scanner['tag_original']??''),(string)($scanner['codigo']??''),$movement->personaEntregaNombre,$movement->numeroEmpleado]));if($search!==''&&!str_contains($haystack,$search))continue;$items[]=['movement'=>$movement,'scanner'=>$scanner];}return$items;}
    private function operationEvidence(int$id,string$section,array$post,array$files,$actor):array
    {
        $storage=$this->factory->evidenceStorage();$out=[];
        try{foreach(['user_signature'=>'firma_usuario_'.$section,'responsible_signature'=>'firma_responsable_'.$section]as$field=>$type)$out[]=$storage->signature((string)($post[$field]??''),$id,$type,$actor);
        $photos=$files['photos']??null;
        if(is_array($photos)&&is_array($photos['name']??null))foreach(array_keys($photos['name'])as$i){if(($photos['error'][$i]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;$out[]=$storage->upload(['name'=>$photos['name'][$i]??'','type'=>$photos['type'][$i]??'','tmp_name'=>$photos['tmp_name'][$i]??'','error'=>$photos['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$photos['size'][$i]??0],$id,'fotografia_'.$section,$actor);}}catch(\Throwable$e){$this->cleanupEvidence($out);throw$e;}
        return$out;
    }
    private function cleanupEvidence(array$evidence):void{$storage=$this->factory->evidenceStorage();foreach($evidence as$item)if($item instanceof \App\DTO\ControlEscaneres\ScannerEvidenceMetadata)$storage->remove($item);}
    private function photoEvidence(int$id,string$type,array$files,$actor):array{$storage=$this->factory->evidenceStorage();$out=[];$photos=$files['photos']??null;try{if(is_array($photos)&&is_array($photos['name']??null))foreach(array_keys($photos['name'])as$i){if(($photos['error'][$i]??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;$out[]=$storage->upload(['name'=>$photos['name'][$i]??'','type'=>$photos['type'][$i]??'','tmp_name'=>$photos['tmp_name'][$i]??'','error'=>$photos['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$photos['size'][$i]??0],$id,'fotografia_'.$type,$actor);}}catch(\Throwable$e){$this->cleanupEvidence($out);throw$e;}return$out;}
    private function incident(array$p,array$files,int$id,$actor,$context):void{$action=(string)($p['operation']??'report');$evidence=$this->photoEvidence($id,'incidencia',$files,$actor);try{if($action==='resolve'){$this->factory->incident()->resolve(new IncidentResolutionData($this->positive($p,'incident_id'),$this->longText($p,'resolution'),$this->validatedTransition($id,(string)($p['resulting_status']??'')),evidenceReferences:$evidence),$actor,$context);}elseif($action==='severity'){$incident=$this->factory->incidents()->findById($this->positive($p,'incident_id'))??throw new\DomainException('Incidencia');$this->factory->incident()->changeSeverity(new IncidentSeverityChangeData($incident->id,$incident->severity,new IncidentSeverity($this->required($p,'severity')),$this->longText($p,'reason')),$actor,$context);}elseif($action==='follow_up'){$this->factory->incident()->followUp($this->positive($p,'incident_id'),$this->longText($p,'comment'),$actor,$context);}elseif($action==='cancel'){$this->factory->incident()->cancel($this->positive($p,'incident_id'),$this->longText($p,'reason'),$actor,$context);}else{$m=(int)($p['movement_id']??0);$this->factory->incident()->report(new ScannerIncidentCreateData($id,$this->required($p,'type'),new IncidentSeverity($this->required($p,'severity')),$this->longText($p,'description'),new\DateTimeImmutable(),$actor,$m>0?$m:null,$evidence),$actor,$context);}}catch(\Throwable$e){$this->cleanupEvidence($evidence);throw$e;}}
    private function required(array$p,string$k):string{$v=trim((string)($p[$k]??''));if($v===''||mb_strlen($v)>500)throw new \InvalidArgumentException('Dato requerido invalido.');return$v;}
    private function longText(array$p,string$k,int$max=2000):string{$v=trim((string)($p[$k]??''));if($v===''||mb_strlen($v)>$max)throw new\InvalidArgumentException('Texto requerido invalido.');return$v;}
    private function optional(array$p,string$k):?string{$v=trim((string)($p[$k]??''));if($k==='imei'&&!(new ScannerRegistrationValidator())->isValidImei($v))throw new \InvalidArgumentException('Captura un IMEI válido de 15 dígitos.');return$v===''?null:$v;}
    private function optionalFloat(array$p,string$k):?float{$value=trim((string)($p[$k]??''));if($value==='')return null;if(!is_numeric($value))throw new\InvalidArgumentException('Importe inválido.');return(float)$value;}
    private function positive(array$p,string$k):int{$v=filter_var($p[$k]??null,FILTER_VALIDATE_INT);if($v===false||$v<1)throw new\InvalidArgumentException('Identificador invalido.');return$v;}
    private function battery(array$p):?BatteryPercentage{$v=$p['battery']??'';return$v===''?null:new BatteryPercentage((int)$v);}
    private function rating(array$p):?int{$v=$p['rating']??'';if($v==='')return null;$stars=filter_var($v,FILTER_VALIDATE_INT);if($stars===false||$stars<1||$stars>5)throw new\InvalidArgumentException('Valoracion invalida.');return$stars*20;}
    private function details(array$p):array{$out=[];foreach(self::COMPONENTS as$c){$v=trim((string)($p['component'][$c]??''));if($v!=='')$out[]=new ScannerInspectionDetailData($c,$v);}return$out;}
    private function validatedTransition(int$id,string$target):ScannerStatus{$s=$this->factory->scanners()->findById($id)??throw new\DomainException('Scanner');$t=new ScannerStatus($target);(new ScannerStateMachine())->assertTransition($s->status,$t);return$t;}
}
