CREATE TABLE inventario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    equipo VARCHAR(255),
    estacion VARCHAR(255),
    via VARCHAR(255),
    sec VARCHAR(255),
    tipo_de_embarque VARCHAR(255),
    entregar_a VARCHAR(255),
    numero_de_guia VARCHAR(255),
    numero_de_bol VARCHAR(255),
    tipo_especifico_de_equipo VARCHAR(255),
    tipo_generico_de_equipo VARCHAR(255),
    tipo_especifico_de_equipo_2 VARCHAR(255),
    l_e VARCHAR(255),
    producto VARCHAR(255),
    grupo_de_producto VARCHAR(255),
    ferrocarril_actual VARCHAR(255),
    ultimo_movimiento VARCHAR(255),
    estacion_de_ultimo_movimiento VARCHAR(255),
    fecha_de_ultimo_movimiento VARCHAR(255),
    eta VARCHAR(255),
    eti VARCHAR(255),
    estatus_del_viaje VARCHAR(255),
    excepcion VARCHAR(255),
    ferrocarril VARCHAR(255),
    dia_remitido VARCHAR(255),
    estacion_de_origen VARCHAR(255),
    remitente VARCHAR(255),
    estacion_de_destino VARCHAR(255),
    consignatario VARCHAR(255),
    ruta VARCHAR(255),
    indicador_de_actividad VARCHAR(255),
    disponible VARCHAR(255),
    destino_en_linea VARCHAR(255),
    estatus_de_situado VARCHAR(255),
    fecha_de_situado VARCHAR(255),
    longitud_de_carro VARCHAR(255),
    ton_neta VARCHAR(255),
    sobrepeso VARCHAR(255),
    limite_de_carga VARCHAR(255),
    peso_total_del_carro VARCHAR(255),
    id_de_tren VARCHAR(255),
    fecha_importacion DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
