<?php
declare(strict_types=1);
$vistaActual='areas';$h=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');ob_start();
?>
<div class="vascor-ui ce-operation"><?php $pageTitle='Áreas operativas';$pageDescription='Gestiona áreas sin borrar su historial y consulta sus métricas actuales.';$breadcrumbs=['Control de Escáneres','Áreas'];require dirname(__DIR__).'/components/page-header.php'; ?>
<?php foreach(($areaMessages??[])as$message):$alertType=$message['type']??'info';$alertMessage=$message['message']??'';require dirname(__DIR__).'/components/alert.php';endforeach; ?>
<section class="vo-form-section"><h2>Nueva área</h2><form method="post" class="vo-actions"><input type="hidden" name="_csrf" value="<?= $h($areaCsrfToken??'') ?>"><input type="hidden" name="operation" value="create"><label class="vo-field"><span>Nombre</span><input class="vo-input" name="name" maxlength="120" required></label><button class="vo-btn vo-btn--primary">Crear área</button></form></section>
<section class="vo-form-section"><h2>Catálogo</h2><div class="vo-table-wrap"><table class="vo-table"><thead><tr><th>Área</th><th>Estado</th><th>Equipos</th><th>Incidencias abiertas</th><th>Pendientes</th><th>Acciones</th></tr></thead><tbody><?php foreach(($areas??[])as$area): ?><tr><td><?= $h($area['nombre']) ?></td><td><?= (int)$area['activo']===1?'Activa':'Inactiva' ?></td><td><?= (int)$area['equipos'] ?></td><td><?= (int)$area['incidencias_abiertas'] ?></td><td><?= (int)$area['pendientes'] ?></td><td><form method="post" class="vo-actions"><input type="hidden" name="_csrf" value="<?= $h($areaCsrfToken??'') ?>"><input type="hidden" name="area_id" value="<?= (int)$area['id'] ?>"><input class="vo-input" name="name" maxlength="120" value="<?= $h($area['nombre']) ?>" required><button class="vo-btn vo-btn--subtle" name="operation" value="rename">Renombrar</button><button class="vo-btn vo-btn--subtle" name="operation" value="<?= (int)$area['activo']===1?'deactivate':'reactivate' ?>"><?= (int)$area['activo']===1?'Desactivar':'Reactivar' ?></button></form></td></tr><?php endforeach; ?></tbody></table></div><?php if(($areas??[])===[]): ?><p class="vo-muted">No hay áreas registradas.</p><?php endif; ?></section></div>
<?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
