<?php
use App\ViewModels\ControlEscaneres\ScannerCatalogViewModel;
$vistaActual='catalogo';$catalogViewModel=$catalogViewModel??new ScannerCatalogViewModel([],0,1,25,1,[]);$h=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$baseParams=['modulo'=>'control-escaneres','seccion'=>'catalogo'];$filterParams=array_filter(['q'=>$catalogViewModel->filters['search']??null,'marca'=>$catalogViewModel->filters['brand']??null,'modelo'=>$catalogViewModel->filters['model']??null,'estado'=>$catalogViewModel->filters['status']??null,'activo'=>isset($catalogViewModel->filters['active'])?(int)$catalogViewModel->filters['active']:null,'incidencia'=>isset($catalogViewModel->filters['withIncident'])?(int)$catalogViewModel->filters['withIncident']:null,'orden'=>$catalogViewModel->filters['orderBy']??null,'direccion'=>$catalogViewModel->filters['direction']??null],fn($v)=>$v!==null&&$v!=='');
$buildUrl=static fn(array$p):string=>BASE_URL.'/index.php?'.htmlspecialchars(http_build_query($p),ENT_QUOTES,'UTF-8');$operationUrl=static fn(string$s,int$id):string=>BASE_URL.'/index.php?modulo=control-escaneres&amp;seccion='.$s.'&amp;scanner_id='.$id;
ob_start(); ?>
<link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/control-escaneres/catalogo.css">
<div class="vascor-ui ce-catalog">
<?php $pageTitle='Escáneres registrados';$pageDescription='Consulta el estado actual de los equipos y abre únicamente las acciones disponibles.';$breadcrumbs=['Control de Escáneres','Catálogo'];require dirname(__DIR__).'/components/page-header.php'; ?>
<?php foreach($catalogViewModel->flashMessages as$message){$alertType=in_array($message['type']??'',['success','warning','error'],true)?$message['type']:'info';$alertMessage=$message['message']??'';require dirname(__DIR__).'/components/alert.php';} ?>
<details class="vo-filter" open><summary>Filtrar catálogo</summary><form method="get" aria-label="Filtros del catálogo"><input type="hidden" name="modulo" value="control-escaneres"><input type="hidden" name="seccion" value="catalogo"><div class="vo-filter__grid"><div class="vo-field"><label for="catalog-search">Buscar equipo</label><input class="vo-input" id="catalog-search" name="q" maxlength="100" value="<?= $h($catalogViewModel->filters['search']??'') ?>" placeholder="Ejemplo: SC-0001"><small class="vo-field__help">Código, serie, marca o modelo.</small></div><div class="vo-field"><label for="catalog-brand">Marca <span>(opcional)</span></label><input class="vo-input" id="catalog-brand" name="marca" maxlength="100" value="<?= $h($catalogViewModel->filters['brand']??'') ?>"></div><div class="vo-field"><label for="catalog-model">Modelo <span>(opcional)</span></label><input class="vo-input" id="catalog-model" name="modelo" maxlength="100" value="<?= $h($catalogViewModel->filters['model']??'') ?>"></div><div class="vo-field"><label for="catalog-status">Estado</label><select class="vo-select" id="catalog-status" name="estado"><option value="">Todos los estados</option><?php foreach(\App\Domain\ControlEscaneres\ScannerStatus::VALUES as$status): ?><option value="<?= $h($status) ?>" <?=($catalogViewModel->filters['status']??null)===$status?'selected':''?>><?= $h(ucwords(str_replace('_',' ',$status))) ?></option><?php endforeach; ?></select></div><div class="vo-field"><label for="catalog-active">Actividad</label><select class="vo-select" id="catalog-active" name="activo"><option value="">Activos e inactivos</option><option value="1" <?=($catalogViewModel->filters['active']??null)===true?'selected':''?>>Sólo activos</option><option value="0" <?=($catalogViewModel->filters['active']??null)===false?'selected':''?>>Sólo inactivos</option></select></div><div class="vo-field"><label for="catalog-incident">Incidencias</label><select class="vo-select" id="catalog-incident" name="incidencia"><option value="">Con y sin incidencias</option><option value="1" <?=($catalogViewModel->filters['withIncident']??null)===true?'selected':''?>>Con incidencia abierta</option><option value="0" <?=($catalogViewModel->filters['withIncident']??null)===false?'selected':''?>>Sin incidencia abierta</option></select></div></div><div class="vo-actions" style="margin-top:var(--vo-space-md)"><button class="vo-btn vo-btn--primary">Aplicar filtros</button><a class="vo-btn vo-btn--subtle" href="<?= $buildUrl($baseParams) ?>">Limpiar filtros</a></div></form></details>
<section aria-labelledby="catalog-results"><div class="vo-actions" style="justify-content:space-between;margin-block:var(--vo-space-lg) var(--vo-space-sm)"><h3 id="catalog-results" style="margin:0"><?= $catalogViewModel->total ?> <?= $catalogViewModel->total===1?'equipo encontrado':'equipos encontrados' ?></h3><span class="vo-badge vo-badge--info">Datos operativos</span></div>
<?php if(!$catalogViewModel->items): ?><div class="vo-card"><?php $emptyTitle='No encontramos escáneres con estos filtros';$emptyDescription='Puedes ajustar la búsqueda o limpiar los filtros para volver a ver el catálogo.';$emptyActionUrl=$buildUrl($baseParams);$emptyActionLabel='Limpiar filtros';require dirname(__DIR__).'/components/empty-state.php'; ?></div><?php else: ?>
<div class="vo-table-wrap" tabindex="0" aria-label="Tabla de escáneres; puede desplazarse horizontalmente"><table class="vo-table"><thead><tr><th scope="col">Equipo</th><th scope="col">Marca y modelo</th><th scope="col">Serie</th><th scope="col">Contacto protegido</th><th scope="col">Estado</th><th scope="col">Última entrega</th><th scope="col">Incidencia</th><th scope="col">Acciones</th></tr></thead><tbody><?php foreach($catalogViewModel->items as$item): ?><tr><td><div class="vo-table__primary"><?= $h($item->code) ?></div><small>#<?= $item->id ?> · <?= $item->active?'Activo':'Inactivo' ?></small></td><td><?= $h($item->brand) ?><br><small><?= $h($item->model) ?></small></td><td><?= $h($item->serial) ?></td><td><span aria-label="IMEI protegido"><?= $h($item->maskedImei) ?></span><br><small aria-label="Teléfono protegido"><?= $h($item->maskedPhone) ?></small></td><td><?php $badgeStatus=$item->active?$item->status:'inactivo';$badgeLabel=$item->active?ucwords(str_replace('_',' ',$item->status)):'Inactivo';require dirname(__DIR__).'/components/badge.php'; ?></td><td><?= $h($item->lastDelivery??'Sin entregas') ?></td><td><?php if($item->hasOpenIncident){$badgeStatus='critica';$badgeLabel='Incidencia abierta';require dirname(__DIR__).'/components/badge.php';}else echo'<span>Sin incidencias</span>'; ?></td><td><div class="vo-actions"><?php foreach($item->actions as$index=>$action): ?><a class="vo-btn <?= $index===0?'':'vo-btn--subtle' ?>" href="<?= $operationUrl($action,$item->id) ?>"><?= $h(ucfirst($action)) ?></a><?php endforeach; ?></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php $paginationPage=$catalogViewModel->page;$paginationTotal=$catalogViewModel->totalPages;if($paginationPage>1)$paginationPrevious=$buildUrl($baseParams+$filterParams+['pagina'=>$paginationPage-1]);if($paginationPage<$paginationTotal)$paginationNext=$buildUrl($baseParams+$filterParams+['pagina'=>$paginationPage+1]);require dirname(__DIR__).'/components/pagination.php';unset($paginationPrevious,$paginationNext);endif; ?></section></div>
<?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
