<?php $vistaActual='dashboard'; ob_start(); ?>
<div class="ce-page-head"><div><span class="ce-eyebrow">Visión general</span><h2>Estado de la operación</h2><p>Indicadores de disponibilidad, conservación y movimientos recientes.</p></div><div class="ce-actions"><button class="ce-btn" type="button" disabled>Hoy ▾</button><button class="ce-btn ce-btn--primary" type="button" disabled>Actualizar</button></div></div>
<section class="ce-grid ce-grid--5" aria-label="Indicadores">
<?php foreach ([['Total de escáneres','48','100%','#e8f3fb'],['Disponibles','21','43.8%','#e7f7f1'],['Entregados','19','39.6%','#e8f3fb'],['En mantenimiento','6','12.5%','#fff2db'],['Baja definitiva','2','4.1%','#fceaea']] as $k): ?>
<article class="ce-card ce-kpi" style="--tone:<?php echo $k[3]; ?>"><div class="ce-kpi__label"><?php echo $k[0]; ?></div><div class="ce-kpi__value"><?php echo $k[1]; ?></div><div class="ce-kpi__meta"><?php echo $k[2]; ?> del parque</div></article><?php endforeach; ?>
</section>
<section class="ce-grid ce-grid--2">
<article class="ce-card"><div class="ce-card__head"><div><span class="ce-eyebrow">Conservación</span><h3>Índice por área</h3></div><small>Promedio 91%</small></div><div class="ce-bars"><?php foreach ([['Andenes',96],['Patio Norte',93],['Almacén',89],['Patio Sur',86],['Taller',78]] as $b): ?><div><div class="ce-bar__meta"><span><?php echo $b[0]; ?></span><strong><?php echo $b[1]; ?>%</strong></div><div class="ce-bar__track"><div class="ce-bar__fill" style="width:<?php echo $b[1]; ?>%"></div></div></div><?php endforeach; ?></div></article>
<article class="ce-card"><div class="ce-card__head"><div><span class="ce-eyebrow">Ranking</span><h3>Áreas con mejor cuidado</h3></div></div><div class="ce-list"><?php foreach ([['1','Andenes','96% · 8 equipos'],['2','Patio Norte','93% · 12 equipos'],['3','Almacén','89% · 10 equipos'],['4','Patio Sur','86% · 11 equipos']] as $x): ?><div class="ce-list__item"><div class="ce-list__icon"><?php echo $x[0]; ?></div><div class="ce-list__body"><strong><?php echo $x[1]; ?></strong><small><?php echo $x[2]; ?></small></div><span class="ce-badge">Óptimo</span></div><?php endforeach; ?></div></article>
</section>
<section class="ce-grid ce-grid--2">
<article class="ce-card"><div class="ce-card__head"><div><span class="ce-eyebrow">Atención</span><h3>Pendientes por devolver</h3></div><span class="ce-badge ce-badge--amber">3 pendientes</span></div><div class="ce-list"><div class="ce-list__item"><div class="ce-list__icon">01</div><div class="ce-list__body"><strong>ESC-014 · Carlos Méndez</strong><small>Patio Norte · vence 18:00</small></div></div><div class="ce-list__item"><div class="ce-list__icon">02</div><div class="ce-list__body"><strong>ESC-027 · Ana Torres</strong><small>Andén B · retraso de 42 min</small></div></div></div></article>
<article class="ce-card"><div class="ce-card__head"><div><span class="ce-eyebrow">Incidencias</span><h3>Últimos daños registrados</h3></div></div><div class="ce-list"><div class="ce-list__item"><div class="ce-list__icon">!</div><div class="ce-list__body"><strong>ESC-009 · Pantalla fisurada</strong><small>Recepción · hace 35 min</small></div><span class="ce-badge ce-badge--red">Crítico</span></div><div class="ce-list__item"><div class="ce-list__icon">!</div><div class="ce-list__body"><strong>ESC-031 · Gatillo con desgaste</strong><small>Recepción · ayer 17:42</small></div><span class="ce-badge ce-badge--amber">Medio</span></div></div></article>
</section>
<article class="ce-card"><div class="ce-card__head"><div><span class="ce-eyebrow">Actividad</span><h3>Últimos movimientos</h3></div><button class="ce-btn" type="button" disabled>Ver historial</button></div><div class="ce-list"><div class="ce-list__item"><div class="ce-list__icon">←</div><div class="ce-list__body"><strong>Recepción de ESC-018</strong><small>María Ríos · Andén A · hace 8 min</small></div><span class="ce-badge">Recibido</span></div><div class="ce-list__item"><div class="ce-list__icon">→</div><div class="ce-list__body"><strong>Entrega de ESC-033</strong><small>José Salas · Patio Sur · hace 21 min</small></div><span class="ce-badge ce-badge--blue">Entregado</span></div></div></article>
<?php $contenidoModulo=ob_get_clean(); require __DIR__.'/plantilla.php'; ?>
