<?php
declare(strict_types=1);
$vistaActual='dashboard';$h=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');ob_start();$pageTitle='Control de Escáneres';$pageDescription='Disponibilidad, custodia, condiciones e incidencias con datos persistidos.';$breadcrumbs=['Control de Escáneres','Inicio'];require __DIR__.'/../components/page-header.php';
?>
<div class="ce-operation vo-dashboard">
<?php if(isset($integrationError)): $alertType='error';$alertMessage='No fue posible cargar el resumen operativo.';require __DIR__.'/../components/alert.php';elseif(!isset($dashboardViewModel)): $alertType='warning';$alertMessage='No existe estructura de datos disponible en este entorno.';require __DIR__.'/../components/alert.php';else:$vm=$dashboardViewModel; ?>
<div class="vo-dashboard-toolbar"><div><small>Última actualización</small><strong><?= $h($vm->updatedAt) ?></strong></div><form method="get"><input type="hidden" name="modulo" value="control-escaneres"><input type="hidden" name="seccion" value="dashboard"><label for="dashboard-range">Periodo</label><select id="dashboard-range" name="rango"><option value="today" <?= $vm->rangeKey==='today'?'selected':'' ?>>Hoy</option><option value="7d" <?= $vm->rangeKey==='7d'?'selected':'' ?>>7 días</option><option value="30d" <?= $vm->rangeKey==='30d'?'selected':'' ?>>30 días</option></select><button class="vo-btn vo-btn--secondary" type="submit">Actualizar</button></form></div>
<section><h2>Resumen operativo</h2><p><?= $h($vm->rangeLabel) ?> · <?= $vm->deliveriesInRange ?> entregas · <?= $vm->receptionsInRange ?> recepciones</p><div class="vo-dashboard-kpis"><?php foreach($vm->kpis as$kpi)require __DIR__.'/../components/dashboard-kpi.php'; ?></div></section>
<section class="vo-form-section"><h2>Atención requerida</h2><?php if($vm->alerts===[]): ?><p class="vo-dashboard-ok">No hay situaciones críticas pendientes.</p><?php else: ?><div class="vo-dashboard-list"><?php foreach($vm->alerts as$item): ?><article><div><strong><?= $h($item->scannerCode) ?> · <?= $h($item->situation) ?></strong><small><?= $h(ucfirst($item->severity)) ?> · <?= $h($item->occurredAt) ?></small></div><a href="<?= $h($item->url) ?>">Abrir expediente</a></article><?php endforeach; ?></div><?php endif; ?></section>
<div class="vo-dashboard-columns"><section class="vo-form-section"><h2>Estado de equipos</h2><div class="vo-status-bars"><?php foreach($vm->statuses as$item): ?><div><div><span><?= $h($item->label) ?></span><strong><?= $item->count ?> · <?= number_format($item->percentage,1) ?>%</strong></div><progress max="100" value="<?= $h($item->percentage) ?>"></progress></div><?php endforeach; ?></div></section><section class="vo-form-section"><h2>Actividad reciente</h2><?php foreach($vm->activity as$item): ?><div class="vo-timeline__item"><time><?= $h($item->occurredAt) ?></time><h4><?= $h($item->title) ?> · <?= $h($item->scannerCode) ?></h4><a href="<?= $h($item->url) ?>">Abrir expediente</a></div><?php endforeach; ?><?php if($vm->activity===[]): ?><p class="vo-muted">Sin actividad en el periodo.</p><?php endif; ?></section></div>
<section class="vo-form-section"><h2>Entregas, recepciones e incidencias por día</h2><div class="vo-table-wrap"><table class="vo-table"><thead><tr><th>Fecha</th><th>Entregas</th><th>Recepciones</th><th>Incidencias</th></tr></thead><tbody><?php foreach($vm->trend as$point): ?><tr><td><?= $h($point->label) ?></td><td><?= $point->deliveries ?></td><td><?= $point->receptions ?></td><td><?= $point->incidents ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="vo-form-section"><h2>Indicadores por área y deterioro</h2><div class="vo-dashboard-columns"><?php foreach(['incidents_by_area'=>'Incidencias por área','ratings_by_area'=>'Valoración por área','deterioration'=>'Deterioro por día','most_incidents'=>'Equipos con más incidencias']as$key=>$label): ?><article><h3><?= $h($label) ?></h3><div class="vo-table-wrap"><table class="vo-table"><thead><tr><th>Grupo</th><th>Valor</th></tr></thead><tbody><?php foreach(($vm->analytics[$key]??[])as$row): ?><tr><td><?= $h($row['label']??'—') ?></td><td><?= $h($row['average']??$row['total']??0) ?></td></tr><?php endforeach; ?><?php if(($vm->analytics[$key]??[])===[]): ?><tr><td colspan="2">Sin datos.</td></tr><?php endif; ?></tbody></table></div></article><?php endforeach; ?></div></section>
<section class="vo-form-section"><h2>Accesos rápidos</h2><div class="vo-quick-actions"><?php foreach($vm->quickActions as$item): ?><a class="vo-card" href="<?= $h($item->url) ?>"><strong><?= $h($item->label) ?></strong><span><?= $h($item->description) ?></span></a><?php endforeach; ?></div></section>
<?php endif; ?></div><?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
