<?php
declare(strict_types=1);
use App\Domain\ControlEscaneres\ScannerStatus;
$vistaActual='catalogo';$h=static fn(mixed$v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$fields=['tag_original'=>'TAG','marca'=>'Marca','modelo'=>'Modelo','numero_serie'=>'Serie','imei'=>'IMEI','telefono'=>'Teléfono','iccid'=>'ICCID','red'=>'Red','plan'=>'Plan','actividad_habitual'=>'Actividad habitual','area_habitual'=>'Área habitual','ubicacion'=>'Ubicación','antiguedad_descriptiva'=>'Antigüedad'];ob_start();
?>
<div class="vascor-ui ce-catalog"><?php $pageTitle='Editar escáner';$pageDescription='Actualiza el registro maestro sin cambiar la identidad de su QR.';$breadcrumbs=['Control de Escáneres','Catálogo','Editar'];require dirname(__DIR__).'/components/page-header.php'; ?>
<?php if(!is_array($scannerEdit)): $emptyTitle='Escáner no encontrado';$emptyDescription='Selecciona otro equipo desde el catálogo.';$emptyActionUrl=BASE_URL.'/index.php?modulo=control-escaneres&seccion=catalogo';$emptyActionLabel='Ir al catálogo';require dirname(__DIR__).'/components/empty-state.php';else: ?>
<form class="vo-card ce-form" method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= $h($editCsrfToken) ?>"><input type="hidden" name="scanner_id" value="<?= (int)$scannerEdit['id'] ?>"><div class="vo-form-grid">
<?php foreach($fields as$name=>$label): ?><div class="vo-field"><label for="edit-<?= $h($name) ?>"><?= $h($label) ?></label><input class="vo-input" id="edit-<?= $h($name) ?>" name="<?= $h($name) ?>" maxlength="<?= $name==='imei'?15:160 ?>" value="<?= $h($scannerEdit[$name]??'') ?>" <?= in_array($name,['marca','modelo'],true)?'required':'' ?> <?= $name==='imei'?'inputmode="numeric" pattern="[0-9]{15}"':'' ?>></div><?php endforeach; ?>
<div class="vo-field"><label for="edit-organizational-area">Área organizacional propietaria <?= (int)($scannerEdit['activo']??0)?'*':'(opcional si permanece inactivo)' ?></label><select class="vo-select" id="edit-organizational-area" name="area_organizacional_id" <?= (int)($scannerEdit['activo']??0)?'required':'' ?>><?php if(!(int)($scannerEdit['activo']??0)):?><option value="">Sin asignar</option><?php elseif(empty($scannerEdit['area_organizacional_id'])):?><option value="" selected disabled>Selecciona el departamento responsable</option><?php endif?><?php foreach(($organizationalAreas??[])as$area):?><option value="<?= (int)$area['id'] ?>" <?= (int)($scannerEdit['area_organizacional_id']??0)===(int)$area['id']?'selected':'' ?>><?= $h($area['nombre']) ?></option><?php endforeach?></select><small>Área actual: <?= $h($scannerEdit['area_organizacional_nombre']??($scannerEdit['area_organizacional_id']?'Asignada':'Sin asignar')) ?>. No sustituye el área operativa habitual.</small></div>
<div class="vo-field"><label for="edit-status">Estado</label><select class="vo-select" id="edit-status" name="estado"><?php foreach(ScannerStatus::VALUES as$status): ?><option value="<?= $h($status) ?>" <?= $scannerEdit['estado']===$status?'selected':'' ?>><?= $h(ucwords(str_replace('_',' ',$status))) ?></option><?php endforeach; ?></select></div>
<div class="vo-field"><label for="edit-photo">Nueva fotografía principal <span>(opcional)</span></label><input class="vo-input" id="edit-photo" type="file" name="main_photo" accept="image/jpeg,image/png,image/webp" capture="environment"><small>La fotografía anterior se conserva como evidencia histórica.</small></div>
<div class="vo-field" style="grid-column:1/-1"><label for="edit-observations">Observaciones</label><textarea class="vo-textarea" id="edit-observations" name="observaciones" maxlength="500"><?= $h($scannerEdit['observaciones']??'') ?></textarea></div></div><div class="vo-actions"><button class="vo-btn vo-btn--primary" type="submit">Guardar cambios</button><a class="vo-btn vo-btn--subtle" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=catalogo">Cancelar</a></div></form>
<?php endif; ?></div><?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
