<?php $vistaActual='expediente';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');ob_start(); ?>
<div class="ce-page-head"><div><span class="ce-eyebrow">Expediente básico</span><h2>Información integral del equipo</h2><p>Trazabilidad operativa sin datos secretos ni payloads técnicos.</p></div></div>
<?php if(isset($integrationError)): ?><article class="ce-card"><?= $h($integrationError) ?></article><?php elseif(!isset($historyViewModel)): ?><article class="ce-card">Seleccione un escáner desde el catálogo.</article><?php else:$s=$historyViewModel->scanner; ?>
<article class="ce-card ce-device-head"><span class="ce-qr ce-qr--large"></span><div><span class="ce-badge"><?= $h($s['status']) ?></span><h2><?= $h($s['code']) ?></h2><p><?= $h($s['brand']) ?> · <?= $h($s['model']) ?> · Serie <?= $h($s['serial']) ?></p></div></article>
<article class="ce-card"><h3>Datos generales</h3><div class="ce-detail-grid"><?php foreach(['ID'=>$s['id'],'QR'=>$s['qr'],'IMEI'=>$s['imei'],'Teléfono'=>$s['phone'],'ICCID'=>$s['iccid'],'Conservación'=>$s['conservation']??'—','Activo'=>$s['active']?'Sí':'No']as$label=>$value): ?><div class="ce-detail"><small><?= $h($label) ?></small><strong><?= $h($value) ?></strong></div><?php endforeach; ?></div></article>
<section class="ce-grid ce-grid--2"><article class="ce-card"><h3>Movimientos</h3><?php foreach($historyViewModel->movements as$m): ?><div class="ce-list__item"><div class="ce-list__body"><strong><?= $h($m['folio']) ?> · <?= $h($m['status']) ?></strong><small><?= $h($m['custodian']) ?> · <?= $h($m['deliveredAt']) ?></small></div></div><?php endforeach; ?></article><article class="ce-card"><h3>Inspecciones</h3><?php foreach($historyViewModel->inspections as$i): ?><div class="ce-list__item"><div class="ce-list__body"><strong><?= $h($i['type']) ?> · calificación <?= $h($i['rating']??'—') ?></strong><small>Batería <?= $h($i['battery']??'—') ?>% · <?= $h($i['at']) ?></small></div></div><?php endforeach; ?></article></section>
<section class="ce-grid ce-grid--2"><article class="ce-card"><h3>Incidencias</h3><?php foreach($historyViewModel->incidents as$i): ?><div class="ce-list__item"><div class="ce-list__body"><strong><?= $h($i['type']) ?> · <?= $h($i['severity']) ?></strong><small><?= $h($i['status']) ?> · <?= $h($i['at']) ?></small></div></div><?php endforeach; ?></article><article class="ce-card"><h3>Evidencias registradas</h3><?php foreach($historyViewModel->evidences as$e): ?><div class="ce-list__item"><div class="ce-list__body"><strong><?= $h($e['type']) ?></strong><small><?= $h($e['capturedAt']) ?></small></div></div><?php endforeach; ?></article></section>
<section class="ce-grid ce-grid--2"><article class="ce-card"><h3>Timeline</h3><div class="ce-timeline"><?php foreach($historyViewModel->timeline as$t): ?><div class="ce-event"><time><?= $h($t['at']) ?></time><h4><?= $h(ucfirst($t['type'])) ?></h4></div><?php endforeach; ?></div></article><article class="ce-card"><h3>Auditoría visible</h3><?php foreach($historyViewModel->auditEvents as$a): ?><div class="ce-list__item"><div class="ce-list__body"><strong><?= $h($a['action']) ?></strong><small><?= $h($a['result']) ?> · <?= $h($a['at']) ?></small></div></div><?php endforeach; ?></article></section>
<?php endif; ?>
<?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
