<?php
$vistaActual='catalogo';$h=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');ob_start();
?>
<div class="vascor-ui ce-catalog">
<?php $pageTitle='Importar inventario';$pageDescription='Revisa el archivo antes de insertar equipos. PIN, PUK, filas vacías y la sección Modem se ignoran.';$breadcrumbs=['Control de Escáneres','Catálogo','Importar'];require dirname(__DIR__).'/components/page-header.php'; ?>
<section class="vo-card"><form method="post" enctype="multipart/form-data" action="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=importar-inventario"><input type="hidden" name="_csrf" value="<?= $h($importCsrfToken??'') ?>"><div class="vo-field"><label for="inventory-file">Archivo Excel</label><input class="vo-input" id="inventory-file" type="file" name="inventory_file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><small class="vo-field__help">Máximo 10 MB. Se leerá exclusivamente la hoja INVENTARIO.</small></div><div class="vo-actions"><button class="vo-btn vo-btn--primary" type="submit">Generar vista previa</button><a class="vo-btn vo-btn--subtle" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=catalogo">Cancelar</a></div></form></section>
<?php if(isset($importPreview)): $stats=$importPreview['stats']; ?>
<section class="vo-card" aria-labelledby="preview-title"><h2 id="preview-title">Vista previa sin escritura</h2><div class="vo-actions"><?php foreach(['total_leido'=>'Filas leídas','tags_unicos'=>'TAG únicos','nuevos'=>'Nuevos','existentes'=>'Existentes','actualizables'=>'Actualizables','conflictos'=>'Conflictos','invalidos'=>'Inválidos'] as$key=>$label): ?><span class="vo-badge vo-badge--info"><?= $h($label) ?>: <?= (int)$stats[$key] ?></span><?php endforeach; ?></div><p><strong>No se ha modificado la base de datos.</strong> Los conflictos marcados como “Requiere revisión” no se importarán automáticamente.</p>
<div class="vo-table-wrap" tabindex="0"><table class="vo-table"><thead><tr><th>Código</th><th>Bloque</th><th>Área</th><th>Estado propuesto</th><th>IMEI</th><th>ICCID</th><th>Teléfono</th><th>Resultado</th></tr></thead><tbody><?php foreach($importPreview['items'] as$item): ?><tr><td><?= $h($item['code']) ?></td><td><?= $h($item['block']) ?></td><td><?= $h($item['area']) ?></td><td><?= $h($item['status']) ?></td><td><?= $h($item['imei']) ?></td><td><?= $h($item['iccid']) ?></td><td><?= $h($item['phone']) ?></td><td><?= $h($item['reason']??ucfirst($item['result'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
<form method="post" action="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=importar-inventario"><input type="hidden" name="_csrf" value="<?= $h($importCsrfToken??'') ?>"><input type="hidden" name="operation" value="confirm"><input type="hidden" name="import_token" value="<?= $h($importToken??'') ?>"><label class="vo-field"><span><input type="checkbox" name="confirm_import" value="1" required> Confirmo que revisé el dry-run y autorizo insertar únicamente los registros marcados como nuevos.</span></label><div class="vo-actions"><button class="vo-btn vo-btn--primary" type="submit">Confirmar importación</button><a class="vo-btn vo-btn--subtle" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=importar-inventario">Descartar vista previa</a></div></form></section>
<?php endif; ?></div>
<?php $contenidoModulo=ob_get_clean();require __DIR__.'/plantilla.php'; ?>
