<?php
declare(strict_types=1);
use App\Support\SpanishDateFormatter;
$vistaActual='recepcion';$h=static fn(mixed$value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');ob_start();
?>
<div class="vascor-ui ce-operation">
<?php $pageTitle='Recepción de escáner';$pageDescription='Compara y documenta las condiciones de regreso.';$breadcrumbs=['Control de Escáneres','Recepción'];require dirname(__DIR__).'/components/page-header.php'; ?>
<?php if(isset($integrationError)): $alertType='error';$alertMessage=$integrationError;require dirname(__DIR__).'/components/alert.php'; ?>
<?php elseif(!isset($receptionForm)||$receptionForm->movementId===null): ?>
    <?php foreach(($receptionForm->messages??[])as$message){$alertType=$message['type']??'info';$alertMessage=$message['message']??'';require dirname(__DIR__).'/components/alert.php';} ?>
    <?php if(($receptionForm->scannerId??null)!==null): ?>
        <?php $emptyTitle='No hay una entrega abierta para este escáner.';$emptyDescription='El movimiento pudo haber sido recibido, cancelado o no corresponde al equipo seleccionado.';$emptyActionUrl=BASE_URL.'/index.php?modulo=control-escaneres&seccion=recepcion';$emptyActionLabel='Ver entregas pendientes';require dirname(__DIR__).'/components/empty-state.php'; ?>
    <?php else: ?>
        <form class="vo-card ce-filter" method="get"><input type="hidden" name="modulo" value="control-escaneres"><input type="hidden" name="seccion" value="recepcion"><div class="vo-field"><label for="reception-search">Buscar entrega pendiente</label><input class="vo-input" id="reception-search" name="q" value="<?= $h($_GET['q']??'') ?>" placeholder="TAG, código, persona o empleado"></div><div class="vo-actions"><button class="vo-btn vo-btn--primary">Buscar</button><a class="vo-btn vo-btn--subtle" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=recepcion">Limpiar</a></div></form>
        <?php if(($receptionPending??[])===[]): ?>
            <?php $emptyTitle='No hay escáneres pendientes de recepción.';$emptyDescription='Cuando exista una entrega abierta aparecerá en esta lista.';require dirname(__DIR__).'/components/empty-state.php'; ?>
        <?php else: ?>
            <div class="vo-table-wrap"><table class="vo-table"><thead><tr><th>Escáner</th><th>Persona</th><th>Empleado</th><th>Área</th><th>Entrega</th><th>Responsable</th><th>Acción</th></tr></thead><tbody><?php foreach($receptionPending as$item):$movement=$item['movement'];$scanner=$item['scanner'];?><tr><td><strong><?= $h($scanner['codigo']??'—') ?></strong><br><small><?= $h($scanner['tag_original']??'Sin TAG') ?></small></td><td><?= $h($movement->personaEntregaNombre) ?></td><td><?= $h($movement->numeroEmpleado) ?></td><td><?= $h($movement->areaNombre??'—') ?></td><td><?= $h(SpanishDateFormatter::format($movement->entregadoAt)) ?></td><td><?= $h($movement->responsableEntregaNombre??'—') ?></td><td><a class="vo-btn vo-btn--primary" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=recepcion&amp;scanner_id=<?= (int)$movement->scannerId ?>">Recibir</a></td></tr><?php endforeach?></tbody></table></div>
        <?php endif; ?>
    <?php endif; ?>
<?php else: ?>
    <?php foreach($receptionForm->messages as$message){$alertType=$message['type']??'info';$alertMessage=$message['message']??'';require dirname(__DIR__).'/components/alert.php';} ?>
    <section class="vo-card"><h2>Entrega seleccionada</h2><div class="vo-comparison"><div class="vo-comparison__item"><strong>Escáner</strong><span><?= $h($receptionForm->scannerCode) ?></span></div><div class="vo-comparison__item"><strong>TAG</strong><span><?= $h($receptionForm->scannerTag??'—') ?></span></div><div class="vo-comparison__item"><strong>Persona</strong><span><?= $h($receptionForm->custodian) ?></span></div><div class="vo-comparison__item"><strong>Empleado</strong><span><?= $h($receptionForm->employeeNumber??'—') ?></span></div><div class="vo-comparison__item"><strong>Área</strong><span><?= $h($receptionForm->areaName??'—') ?></span></div><div class="vo-comparison__item"><strong>Supervisor</strong><span><?= $h($receptionForm->supervisorName??'—') ?></span></div><div class="vo-comparison__item"><strong>Quien entregó</strong><span><?= $h($receptionForm->deliveryResponsibleName??'—') ?></span></div><div class="vo-comparison__item"><strong>Turno</strong><span><?= $h($receptionForm->shift??'—') ?></span></div><div class="vo-comparison__item"><strong>Fecha de entrega</strong><span><?= $h(SpanishDateFormatter::format($receptionForm->deliveredAt)) ?></span></div></div></section>
    <section class="vo-form-section"><h2>Condición registrada en la entrega</h2><div class="vo-comparison"><div class="vo-comparison__item"><strong>Batería</strong><span><?= $receptionForm->deliveryBattery===null?'—':$h($receptionForm->deliveryBattery).'%' ?></span></div><div class="vo-comparison__item"><strong>Valoración</strong><span><?= $receptionForm->deliveryRating===null?'—':$h(round($receptionForm->deliveryRating/20,1)).'/5' ?></span></div><?php foreach($receptionForm->deliveryDetails as$detail):?><div class="vo-comparison__item"><strong><?= $h(ucwords(str_replace('_',' ',$detail['componente']))) ?></strong><span><?= $h($detail['estado']) ?></span></div><?php endforeach?></div><?php if($receptionForm->deliveryObservations):?><p><strong>Observaciones:</strong> <?= $h($receptionForm->deliveryObservations) ?></p><?php endif?></section>
    <form class="ce-form" method="post" enctype="multipart/form-data" data-vo-operation-form><input type="hidden" name="_csrf" value="<?= $h($receptionForm->csrfToken) ?>"><input type="hidden" name="scanner_id" value="<?= (int)$receptionForm->scannerId ?>"><input type="hidden" name="movement_id" value="<?= (int)$receptionForm->movementId ?>">
    <section class="vo-form-section"><h2>Condiciones de regreso</h2><div class="vo-form-grid"><div class="vo-field"><label for="reception-name">Quien devuelve</label><input class="vo-input" id="reception-name" name="receiver_name" required maxlength="160"></div><div class="vo-field"><label for="reception-responsible">Responsable que recibe</label><input class="vo-input" id="reception-responsible" name="responsible_name" required maxlength="160"></div><div class="vo-field"><label for="reception-battery">Batería (%)</label><input class="vo-input" id="reception-battery" type="number" min="0" max="100" name="battery"></div><fieldset class="vo-field ce-star-field"><legend>Valoración</legend><div class="ce-stars" aria-label="Valoración de 1 a 5 estrellas"><?php foreach(range(5,1)as$star):?><input id="reception-rating-<?= $star ?>" type="radio" name="rating" value="<?= $star ?>"><label for="reception-rating-<?= $star ?>" title="<?= $star ?> estrellas">★</label><?php endforeach?></div></fieldset><?php foreach($receptionForm->components as$component):?><div class="vo-field"><label for="reception-<?= $h($component) ?>"><?= $h(ucwords(str_replace('_',' ',$component))) ?></label><select class="vo-select" id="reception-<?= $h($component) ?>" name="component[<?= $h($component) ?>]" required><option value="">Selecciona</option><option>excelente</option><option>bueno</option><option>regular</option><option>dañado</option><option>no funciona</option><option>faltante</option></select></div><?php endforeach?><div class="vo-field" style="grid-column:1/-1"><label for="reception-observations">Observaciones</label><textarea class="vo-textarea" id="reception-observations" name="observations" maxlength="1000"></textarea></div></div></section>
    <section class="vo-form-section"><label class="vo-check"><input type="checkbox" name="confirm_severe_differences" value="1"> Confirmo que revisé cualquier deterioro importante, daño crítico o faltante.</label></section>
    <?php $signaturePrefix='reception';$signatureFirstLabel='Firma de quien devuelve';$signatureSecondLabel='Firma de quien recibe';require __DIR__.'/partials/evidence-fields.php'; ?>
    <div class="vo-actions"><button class="vo-btn vo-btn--primary" type="submit" data-loading-label="Registrando recepción…">Registrar recepción</button><a class="vo-btn vo-btn--subtle" href="<?= BASE_URL ?>/index.php?modulo=control-escaneres&amp;seccion=recepcion">Cancelar</a></div></form>
<?php endif; ?>
</div>
<?php $contenidoModulo=(string)ob_get_clean();require __DIR__.'/plantilla.php';
