<?php
declare(strict_types=1);
namespace App\Repositories;

final class UserAdminRepository
{
    public function __construct(private \PDO$pdo){}
    public function pdo():\PDO{return$this->pdo;}
    public function list(string$search='',?bool$active=null,int$page=1,int$perPage=20,string$areaFilter=''):array
    {
        [$where,$params]=$this->filters($search,$active,'u.');$this->areaFilter($areaFilter,$where,$params,'u.');
        $sql="SELECT u.id,u.nombre,u.numero_empleado,u.usuario,u.correo,u.activo,u.ultimo_acceso,u.created_at,GROUP_CONCAT(DISTINCT r.nombre ORDER BY r.nombre SEPARATOR ', ') roles,MAX(CASE WHEN ua.es_principal=1 AND ua.activo=1 AND ao.activo=1 THEN ao.nombre END) area_principal,CASE WHEN NOT EXISTS(SELECT 1 FROM usuario_areas uac JOIN areas_organizacionales aac ON aac.id=uac.area_id AND aac.activo=1 WHERE uac.usuario_id=u.id AND uac.activo=1) THEN(SELECT GROUP_CONCAT(m.nombre ORDER BY m.orden SEPARATOR ', ') FROM modulos m WHERE m.activo=1) ELSE NULL END modulos_compatibilidad,EXISTS(SELECT 1 FROM auditoria_eventos ae WHERE ae.usuario_id=u.id OR(ae.entidad='usuario' AND ae.entidad_id=u.id)) tiene_historial,EXISTS(SELECT 1 FROM usuario_sesiones us WHERE us.usuario_id=u.id AND us.revocada_at IS NULL AND us.expira_at>CURRENT_TIMESTAMP(6)) sesiones_activas FROM usuarios u LEFT JOIN usuario_roles ur ON ur.usuario_id=u.id LEFT JOIN roles r ON r.id=ur.rol_id LEFT JOIN usuario_areas ua ON ua.usuario_id=u.id LEFT JOIN areas_organizacionales ao ON ao.id=ua.area_id".($where?' WHERE '.implode(' AND ',$where):'').' GROUP BY u.id ORDER BY u.nombre LIMIT '.(int)$perPage.' OFFSET '.(int)(($page-1)*$perPage);
        $stmt=$this->pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll(\PDO::FETCH_ASSOC);foreach($rows as&$row)if(!$row['area_principal'])$row['modulos_compatibilidad']=null;unset($row);return$rows;
    }
    public function count(string$search='',?bool$active=null,string$areaFilter=''):int{[$where,$params]=$this->filters($search,$active,'u.');$this->areaFilter($areaFilter,$where,$params,'u.');$s=$this->pdo->prepare('SELECT COUNT(*) FROM usuarios u'.($where?' WHERE '.implode(' AND ',$where):''));$s->execute($params);return(int)$s->fetchColumn();}
    public function organizationalStats():array{$r=$this->pdo->query("SELECT COUNT(*) total,SUM(EXISTS(SELECT 1 FROM usuario_areas ua JOIN areas_organizacionales a ON a.id=ua.area_id AND a.activo=1 WHERE ua.usuario_id=u.id AND ua.activo=1)) con_area FROM usuarios u WHERE u.activo=1")->fetch(\PDO::FETCH_ASSOC);$total=(int)($r['total']??0);$assigned=(int)($r['con_area']??0);return['total'=>$total,'assigned'=>$assigned,'pending'=>$total-$assigned,'percentage'=>$total?round($assigned*100/$total,1):0.0];}
    public function find(int$id):?array{$s=$this->pdo->prepare('SELECT id,nombre,numero_empleado,usuario,correo,activo FROM usuarios WHERE id=:id');$s->execute(['id'=>$id]);$r=$s->fetch(\PDO::FETCH_ASSOC);if(!is_array($r))return null;$r['role_ids']=$this->roleIds($id);$r['area_ids']=$this->areaIds($id);$r['principal_area_id']=$this->principalAreaId($id);$r['module_allow_ids']=$this->moduleIds($id,'permitir');$r['module_deny_ids']=$this->moduleIds($id,'denegar');return$r;}
    public function roles(bool$activeOnly=true):array{return$this->pdo->query('SELECT id,nombre,descripcion,activo,es_sistema FROM roles'.($activeOnly?' WHERE activo=1':'').' ORDER BY nombre')->fetchAll(\PDO::FETCH_ASSOC);}
    public function roleIds(int$userId):array{$s=$this->pdo->prepare('SELECT rol_id FROM usuario_roles WHERE usuario_id=:id');$s->execute(['id'=>$userId]);return array_map('intval',$s->fetchAll(\PDO::FETCH_COLUMN));}
    public function validRoleIds(array$ids):bool{if($ids===[])return false;$marks=implode(',',array_fill(0,count($ids),'?'));$s=$this->pdo->prepare("SELECT COUNT(*) FROM roles WHERE activo=1 AND id IN ($marks)");$s->execute($ids);return(int)$s->fetchColumn()===count($ids);}
    public function duplicate(string$user,string$employee,?string$email,?int$except=null):?string{$sql='SELECT usuario,numero_empleado,correo FROM usuarios WHERE (usuario=:u OR numero_empleado=:e'.($email!==null?' OR correo=:c':'').')'.($except!==null?' AND id<>:id':'').' LIMIT 1';$p=['u'=>$user,'e'=>$employee];if($email!==null)$p['c']=$email;if($except!==null)$p['id']=$except;$s=$this->pdo->prepare($sql);$s->execute($p);$r=$s->fetch(\PDO::FETCH_ASSOC);if(!is_array($r))return null;return$r['usuario']===$user?'usuario':($r['numero_empleado']===$employee?'numero_empleado':'correo');}
    public function insert(array$d,int$actor):int{$s=$this->pdo->prepare('INSERT INTO usuarios(nombre,numero_empleado,usuario,correo,password_hash,activo,created_by,updated_by)VALUES(:nombre,:empleado,:usuario,:correo,:hash,:activo,:actor,:actor2)');$s->execute(['nombre'=>$d['nombre'],'empleado'=>$d['numero_empleado'],'usuario'=>$d['usuario'],'correo'=>$d['correo'],'hash'=>$d['password_hash'],'activo'=>(int)$d['activo'],'actor'=>$actor,'actor2'=>$actor]);return(int)$this->pdo->lastInsertId();}
    public function update(int$id,array$d,int$actor):void{$s=$this->pdo->prepare('UPDATE usuarios SET nombre=:nombre,numero_empleado=:empleado,correo=:correo,activo=:activo,updated_by=:actor WHERE id=:id');$s->execute(['nombre'=>$d['nombre'],'empleado'=>$d['numero_empleado'],'correo'=>$d['correo'],'activo'=>(int)$d['activo'],'actor'=>$actor,'id'=>$id]);}
    public function replaceRoles(int$userId,array$roleIds,int$actor):void{$this->pdo->prepare('DELETE FROM usuario_roles WHERE usuario_id=:id')->execute(['id'=>$userId]);$s=$this->pdo->prepare('INSERT INTO usuario_roles(usuario_id,rol_id,asignado_por)VALUES(:usuario,:rol,:actor)');foreach($roleIds as$roleId)$s->execute(['usuario'=>$userId,'rol'=>$roleId,'actor'=>$actor]);}
    public function areaIds(int$userId):array{$s=$this->pdo->prepare('SELECT area_id FROM usuario_areas WHERE usuario_id=:id AND activo=1');$s->execute(['id'=>$userId]);return array_map('intval',$s->fetchAll(\PDO::FETCH_COLUMN));}
    public function principalAreaId(int$userId):?int{$s=$this->pdo->prepare('SELECT area_id FROM usuario_areas WHERE usuario_id=:id AND activo=1 AND es_principal=1 LIMIT 1');$s->execute(['id'=>$userId]);$id=$s->fetchColumn();return$id===false?null:(int)$id;}
    public function moduleIds(int$userId,string$type):array{$s=$this->pdo->prepare('SELECT modulo_id FROM usuario_modulos WHERE usuario_id=:id AND activo=1 AND tipo=:type');$s->execute(['id'=>$userId,'type'=>$type]);return array_map('intval',$s->fetchAll(\PDO::FETCH_COLUMN));}
    public function replaceAreas(int$userId,array$areaIds,int$principalAreaId,int$actor):void{$this->pdo->prepare('UPDATE usuario_areas SET activo=0,es_principal=0 WHERE usuario_id=:id')->execute(['id'=>$userId]);$s=$this->pdo->prepare('INSERT INTO usuario_areas(usuario_id,area_id,es_principal,activo,created_by)VALUES(:usuario,:area,:principal,1,:actor) ON DUPLICATE KEY UPDATE es_principal=VALUES(es_principal),activo=1');foreach($areaIds as$areaId)$s->execute(['usuario'=>$userId,'area'=>$areaId,'principal'=>(int)($areaId===$principalAreaId),'actor'=>$actor]);}
    public function replaceModuleExceptions(int$userId,array$allowIds,array$denyIds,int$actor):void{$this->pdo->prepare('UPDATE usuario_modulos SET activo=0 WHERE usuario_id=:id')->execute(['id'=>$userId]);$s=$this->pdo->prepare('INSERT INTO usuario_modulos(usuario_id,modulo_id,tipo,activo,created_by)VALUES(:usuario,:modulo,:tipo,1,:actor) ON DUPLICATE KEY UPDATE tipo=VALUES(tipo),activo=1');foreach(['permitir'=>$allowIds,'denegar'=>$denyIds]as$type=>$ids)foreach($ids as$moduleId)$s->execute(['usuario'=>$userId,'modulo'=>$moduleId,'tipo'=>$type,'actor'=>$actor]);}
    public function setActive(int$id,bool$active,int$actor):void{$s=$this->pdo->prepare('UPDATE usuarios SET activo=:activo,updated_by=:actor WHERE id=:id');$s->execute(['activo'=>(int)$active,'actor'=>$actor,'id'=>$id]);}
    public function setPassword(int$id,string$hash,int$actor):void{$s=$this->pdo->prepare('UPDATE usuarios SET password_hash=:hash,updated_by=:actor WHERE id=:id');$s->execute(['hash'=>$hash,'actor'=>$actor,'id'=>$id]);}
    public function activeAdministratorsExcluding(int$id):int{$s=$this->pdo->prepare("SELECT COUNT(DISTINCT u.id) FROM usuarios u JOIN usuario_roles ur ON ur.usuario_id=u.id JOIN rol_permisos rp ON rp.rol_id=ur.rol_id JOIN permisos p ON p.id=rp.permiso_id WHERE u.activo=1 AND u.id<>:id AND p.clave IN ('usuarios.crear','usuarios.editar','administracion.acceder') GROUP BY u.id HAVING COUNT(DISTINCT p.clave)=3");$s->execute(['id'=>$id]);return count($s->fetchAll());}
    private function filters(string$search,?bool$active,string$prefix=''):array
    {
        $where=[];$params=[];$search=trim($search);
        if($search!==''){
            $literal=str_replace(['!','%','_'],['!!','!%','!_'],$search);$like='%'.$literal.'%';
            $where[]='('.$prefix.'nombre LIKE :search_name ESCAPE \'!\' OR '.$prefix.'usuario LIKE :search_username ESCAPE \'!\' OR '.$prefix.'numero_empleado LIKE :search_employee ESCAPE \'!\' OR '.$prefix.'correo LIKE :search_email ESCAPE \'!\')';
            $params=['search_name'=>$like,'search_username'=>$like,'search_employee'=>$like,'search_email'=>$like];
        }
        if($active!==null){$where[]=$prefix.'activo=:activo';$params['activo']=(int)$active;}
        return[$where,$params];
    }
    private function areaFilter(string$filter,array&$where,array&$params,string$prefix):void{if($filter==='unassigned'){$where[]='NOT EXISTS(SELECT 1 FROM usuario_areas uaf JOIN areas_organizacionales aof ON aof.id=uaf.area_id AND aof.activo=1 WHERE uaf.usuario_id='.$prefix.'id AND uaf.activo=1)';}elseif(ctype_digit($filter)&&(int)$filter>0){$where[]='EXISTS(SELECT 1 FROM usuario_areas uaf JOIN areas_organizacionales aof ON aof.id=uaf.area_id AND aof.activo=1 WHERE uaf.usuario_id='.$prefix.'id AND uaf.activo=1 AND uaf.area_id=:area_filter)';$params['area_filter']=(int)$filter;}}
}
