<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';use App\Repositories\ControlEscaneres\Pdo\PdoScannerRepository;
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec(file_get_contents(__DIR__.'/fixtures/sqlite-schema.sql'));$pdo->exec("INSERT INTO scanners(codigo,codigo_qr,tag_original,imei,numero_serie,marca,modelo,estado,activo)VALUES('SC-5250','scanner:SC-5250','TAG-5250','490154203237518','SER-5250','Zebra','TC22','disponible',1),('SC-5251','scanner:SC-5251','TAG-5251','490154203237526','SER-5251','Zebra','TC22','entregado',1),('SC-5252','scanner:SC-5252','TAG-5252','490154203237534','SER-5252','Zebra','TC22','pendiente_reparacion',1)");$pdo->exec("INSERT INTO scanner_movimientos(scanner_id,folio,estado,persona_entrega_nombre,numero_empleado,turno,entregado_at)VALUES(2,'MOV-FINDER-1','abierto','Persona','E1','A','2026-07-22 05:00:00')");$repo=new PdoScannerRepository($pdo);
foreach(['SC-5250','scanner:SC-5250','TAG-5250','490154203237518','SER-5250']as$value)test('resuelve '.$value,fn()=>same('SC-5250',$repo->resolveIdentifier('  '.$value.'  ')['codigo']));test('identificador inexistente no crea equipo',function()use($repo,$pdo){$before=(int)$pdo->query('SELECT COUNT(*) FROM scanners')->fetchColumn();same(null,$repo->resolveIdentifier('NO-EXISTE'));same($before,(int)$pdo->query('SELECT COUNT(*) FROM scanners')->fetchColumn());});
$root=dirname(__DIR__,2);$controller=file_get_contents($root.'/app/Controllers/ControlEscaneres/ControlEscaneresWebController.php');$js=file_get_contents($root.'/public/assets/js/control-escaneres/equipment-finder.js');$catalog=file_get_contents($root.'/app/Views/control-escaneres/catalogo.php');$delivery=file_get_contents($root.'/app/Views/control-escaneres/entrega.php');$reception=file_get_contents($root.'/app/Views/control-escaneres/recepcion.php');$css=file_get_contents($root.'/public/assets/css/control-escaneres/control-escaneres.css');
test('endpoint sólo recomienda entrega o recepción',fn()=>ok(str_contains($controller,"\$action='recepcion'")&&str_contains($controller,"\$action='entrega'")&&!str_contains($controller,'seccion=registrar&scanner_id')));
test('estado pendiente de reparación queda bloqueado',fn()=>ok(str_contains($controller,"'pendiente_reparacion','mantenimiento','baja_definitiva','extraviado'")));
test('catálogo usa componente compartido',fn()=>ok(str_contains($catalog,"finderMode='automatico'")&&!str_contains($catalog,'data-qr-manual-form')));
test('entrega siempre muestra buscador manual',fn()=>ok(str_contains($delivery,'Escanear QR para entregar')));
test('recepción siempre muestra buscador manual',fn()=>ok(str_contains($reception,'Escanear QR para recibir')));
test('componente evita doble clic y maneja JSON',fn()=>ok(str_contains($js,'this.busy')&&str_contains($js,'response.json()')&&str_contains($js,'redirect_url')));
test('modal es usable a 360 px',fn()=>ok(str_contains($css,'@media(max-width:360px)')&&str_contains($css,'width:100%')));finish('Equipment Finder');
