<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
use App\DTO\ControlEscaneres\DashboardRange;use App\Repositories\ControlEscaneres\Pdo\PdoScannerDashboardQuery;
function dashboardDb():PDO{$p=new PDO('sqlite::memory:');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->exec(file_get_contents(__DIR__.'/fixtures/sqlite-schema.sql'));return$p;}
function seedDashboard(PDO$p):void{$p->exec("INSERT INTO scanners(id,codigo,codigo_qr,marca,modelo,estado,activo,updated_at)VALUES(1,'SC-0001','Q1','A','B','disponible',1,'2026-07-18 08:00:00'),(2,'SC-0002','Q2','A','B','entregado',1,'2026-07-18 08:00:00'),(3,'SC-0003','Q3','A','B','mantenimiento',1,'2026-07-17 08:00:00'),(4,'SC-0004','Q4','A','B','extraviado',0,'2026-07-16 08:00:00'),(5,'SC-0005','Q5','A','B','pendiente_reparacion',1,'2026-07-15 08:00:00');INSERT INTO scanner_movimientos(id,scanner_id,folio,estado,entregado_at,recibido_at)VALUES(1,2,'MOV-1','abierto','2026-07-18 09:00:00',NULL),(2,1,'MOV-2','devuelto','2026-07-10 09:00:00','2026-07-18 10:00:00');INSERT INTO scanner_incidencias(id,scanner_id,tipo,severidad,descripcion,estado,reportada_at)VALUES(1,5,'falla','critica','x','abierta','2026-07-18 11:00:00'),(2,5,'falla','alta','x','en_seguimiento','2026-07-17 11:00:00'),(3,5,'falla','critica','x','resuelta','2026-07-16 11:00:00');");}
$now=new DateTimeImmutable('2026-07-18 12:00:00',new DateTimeZone('America/Mexico_City'));
test('dashboard vacío',function()use($now){$r=(new PdoScannerDashboardQuery(dashboardDb()))->fetch(DashboardRange::fromInput('today',$now));same(0,$r->inventory->total);same(0,$r->incidents->openIncidents);});
$pdo=dashboardDb();seedDashboard($pdo);$query=new PdoScannerDashboardQuery($pdo);$today=$query->fetch(DashboardRange::fromInput('today',$now));
test('conteo total activo inactivo',fn()=>ok($today->inventory->total===5&&$today->inventory->active===4&&$today->inventory->inactive===1));test('estados canónicos',fn()=>ok($today->inventory->available===1&&$today->inventory->delivered===1&&$today->inventory->maintenance===1));test('incidencias sin duplicar equipos',fn()=>ok($today->incidents->openIncidents===2&&$today->incidents->affectedScanners===1));test('críticas excluyen resueltas',fn()=>same(1,$today->incidents->criticalIncidents));test('entregas del día',fn()=>same(1,$today->deliveriesInRange));test('recepciones incluyen entrega anterior',fn()=>same(1,$today->receptionsInRange));test('atención deduplica escáner',fn()=>same(2,count($today->attention)));test('prioridad crítica primero',fn()=>same('critica',$today->attention[0]->severity));test('actividad ordenada',fn()=>ok($today->activity[0]->occurredAt>=$today->activity[1]->occurredAt));test('actividad limitada',fn()=>ok(count($today->activity)<=10));test('tendencia hoy',fn()=>ok(count($today->trend)===1&&$today->trend[0]->deliveries===1&&$today->trend[0]->receptions===1&&$today->trend[0]->incidents===1));
$seven=$query->fetch(DashboardRange::fromInput('7d',$now));test('rango siete días',fn()=>ok(count($seven->trend)===7&&$seven->incidents->openIncidents===2));$thirty=$query->fetch(DashboardRange::fromInput('30d',$now));test('rango treinta días',fn()=>same(30,count($thirty->trend)));test('allowlist inválida vuelve a hoy',fn()=>same('today',DashboardRange::fromInput('DROP TABLE',$now)->key));test('movimiento abierto impide disponible',function()use($now){$p=dashboardDb();$p->exec("INSERT INTO scanners(id,codigo,codigo_qr,marca,modelo,estado,activo,updated_at)VALUES(1,'SC-1','Q','A','B','disponible',1,'2026-07-18');INSERT INTO scanner_movimientos(id,scanner_id,folio,estado,entregado_at)VALUES(1,1,'M','abierto','2026-07-18')");$r=(new PdoScannerDashboardQuery($p))->fetch(DashboardRange::fromInput('today',$now));same(0,$r->inventory->available);});finish('Dashboard Query');
