<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';use App\Services\ControlEscaneres\Schema\{ControlEscaneresSchemaInspector,MigrationManifestVerifier};use App\Services\ControlEscaneres\Import\InitialScannerCsvValidator;$root=dirname(__DIR__,2);$inspector=new ControlEscaneresSchemaInspector();$db=fn()=>new PDO('sqlite::memory:');
test('esquema ausente es WARN',function()use($inspector,$db){$r=$inspector->inspect($db());same('absent',$r->state);same(1,$r->exitCode());});
test('legacy incompatible bloquea',function()use($inspector,$db){$p=$db();$p->exec('CREATE TABLE scanners(id INTEGER,codigo TEXT)');$r=$inspector->inspect($p);same('legacy_incompatible',$r->state);same(2,$r->exitCode());});
test('esquema parcial bloquea',function()use($inspector,$db){$p=$db();$p->exec('CREATE TABLE scanners(id INTEGER,codigo TEXT,codigo_qr TEXT,estado TEXT,activo INTEGER)');same('canonical_partial',$inspector->inspect($p)->state);});
test('esquema completo tipado',function()use($inspector,$db){$p=$db();$p->exec('CREATE TABLE scanners(id INTEGER,codigo TEXT,codigo_qr TEXT,estado TEXT,activo INTEGER);CREATE INDEX idx_ce_scanners_estado_activo ON scanners(estado,activo);CREATE TABLE scanner_movimientos(scanner_id INTEGER,folio TEXT,estado TEXT,entregado_at TEXT);CREATE TABLE scanner_inspecciones(id INTEGER);CREATE TABLE scanner_inspeccion_detalles(id INTEGER);CREATE TABLE scanner_incidencias(scanner_id INTEGER,movimiento_id INTEGER,severidad TEXT,estado TEXT);CREATE TABLE scanner_evidencias(id INTEGER);CREATE TABLE auditoria_eventos(id INTEGER)');$r=$inspector->inspect($p);same('canonical_complete',$r->state);same(1,$r->exitCode());});
$manifest=$root.'/database/migrations/control-escaneres/manifest.json';$verifier=new MigrationManifestVerifier();$rows=$verifier->verify($manifest,$root.'/database/migrations');test('manifest contiene siete migraciones',fn()=>same(7,count($rows)));test('checksums aprobados',fn()=>ok(!array_filter($rows,fn($x)=>!$x['valid'])));test('orden y dependencias',fn()=>ok($rows[0]['depends_on']===null&&$rows[6]['depends_on']===6));
test('migración modificada se detecta',function()use($verifier,$manifest,$root){$dir=sys_get_temp_dir().'/ce_manifest_'.bin2hex(random_bytes(4));mkdir($dir);foreach(glob($root.'/database/migrations/20260718_*.sql')as$f)copy($f,$dir.'/'.basename($f));file_put_contents($dir.'/20260718_001_create_control_escaneres_scanners.sql','alterado');$r=$verifier->verify($manifest,$dir);ok(!$r[0]['valid']);foreach(glob($dir.'/*')as$f)unlink($f);rmdir($dir);});
$validator=new InitialScannerCsvValidator();test('fixture válido sin escritura',fn()=>same(2,$validator->validate(__DIR__.'/fixtures/scanners-demo.csv')['valid']));
function csvTemp(string$content):string{$f=tempnam(sys_get_temp_dir(),'ce_csv_');file_put_contents($f,$content);return$f;}
test('duplicados son inválidos',function()use($validator){$f=csvTemp("codigo,marca,modelo,estado,activo\nSC-1000,A,B,disponible,1\nSC-1000,A,B,disponible,1\n");$r=$validator->validate($f);unlink($f);same(1,$r['invalid']);});
test('estado inválido se rechaza',function()use($validator){$f=csvTemp("codigo,marca,modelo,estado,activo\nSC-1000,A,B,inventado,1\n");$r=$validator->validate($f);unlink($f);same(1,$r['invalid']);});
test('PIN PUK prohibidos',function()use($validator){$f=csvTemp("codigo,marca,modelo,estado,activo,pin\nSC-1000,A,B,disponible,1,1234\n");$blocked=false;try{$validator->validate($f);}catch(InvalidArgumentException){$blocked=true;}finally{unlink($f);}ok($blocked);});
test('dry-run no ejecuta SQL sin bandera',function()use($root){$script=file_get_contents($root.'/bin/control-escaneres-migrate.php');ok(str_contains($script,'No se ejecutó SQL')&&str_contains($script,"if(!\$execute)"));});test('importador exige validación o ejecución explícita',function()use($root){$script=file_get_contents($root.'/bin/control-escaneres-import.php');ok(str_contains($script,'--validate-only')&&str_contains($script,'--validation-approved'));});test('salida no imprime secretos',function()use($root){$scripts=file_get_contents($root.'/bin/control-escaneres-schema-preflight.php').file_get_contents($root.'/bin/control-escaneres-import.php');ok(!preg_match('/DB_PASSWORD|password=|DSN completo/i',$scripts));});finish('Deployment Preparation');
