<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
if(session_status()!==PHP_SESSION_ACTIVE){session_save_path(sys_get_temp_dir());session_id('ce-web-test');session_start();}
use App\Controllers\ControlEscaneres\{ScannerCatalogController,ScannerHistoryController};use App\Domain\ControlEscaneres\{IncidentSeverity,ScannerCode,ScannerFolio,ScannerStatus};use App\DTO\ControlEscaneres\{AuthenticatedActorData,ScannerCreateData,ScannerIncidentCreateData,ScannerMovementCreateData};use App\Presentation\ControlEscaneres\SensitiveScannerDataPresenter;use App\Repositories\ControlEscaneres\Pdo\{PdoAuditQueryRepository,PdoScannerCatalogQuery,PdoScannerHistoryQuery,PdoScannerIncidentRepository,PdoScannerMovementRepository,PdoScannerRepository};use App\Security\ControlEscaneres\{SessionAuthenticatedActorProvider,SessionCsrfTokenManager};use App\Support\ControlEscaneres\{BusinessRequestContextFactory,ControlEscaneresErrorMapper};use App\ViewModels\ControlEscaneres\ScannerCatalogViewModel;
$pdo=new PDO('sqlite::memory:');$pdo->exec(file_get_contents(__DIR__.'/fixtures/sqlite-schema.sql'));$actor=new AuthenticatedActorData(7,'test');$scanners=new PdoScannerRepository($pdo);$one=$scanners->create(new ScannerCreateData(new ScannerCode('SC-3001'),'Q-3001','Zebra','TC22',new ScannerStatus('disponible'),'SER-3001','351756051234561','8952020210123456789'),7);$pdo->exec("UPDATE scanners SET telefono='8121007890',indice_conservacion=95 WHERE id=".$one->id);$two=$scanners->create(new ScannerCreateData(new ScannerCode('SC-3002'),'Q-3002','Honeywell','EDA52',new ScannerStatus('entregado'),'SER-3002','351756051234562'),7);$movements=new PdoScannerMovementRepository($pdo);$movement=$movements->create(new ScannerMovementCreateData($two->id,new ScannerFolio('MOV-20260718-WEB001'),'Persona','E1','A',new DateTimeImmutable('2026-07-18 08:00'),$actor));(new PdoScannerIncidentRepository($pdo))->create(new ScannerIncidentCreateData($two->id,'daño',new IncidentSeverity('media'),'Pantalla',new DateTimeImmutable('2026-07-18 09:00'),$actor,$movement->id));
$presenter=new SensitiveScannerDataPresenter();test('enmascara IMEI',fn()=>same('***********4561',$presenter->imei('351756051234561')));test('enmascara telefono',fn()=>same('******7890',$presenter->phone('8121007890')));test('enmascara ICCID',fn()=>ok(!str_contains($presenter->iccid('8952020210123456789'),'895202021012345')));
$controller=new ScannerCatalogController(new PdoScannerCatalogQuery($pdo),$presenter);$catalog=$controller->index(['por_pagina'=>1]);test('catalogo usa ViewModel',fn()=>ok($catalog instanceof ScannerCatalogViewModel));test('catalogo pagina datos reales',fn()=>same(1,count($catalog->items)));test('catalogo pagina total',fn()=>same(2,$catalog->total));test('catalogo no expone IMEI',fn()=>ok($catalog->items[0]->maskedImei!=='351756051234561'));$filtered=$controller->index(['estado'=>'entregado','incidencia'=>'1']);test('filtro estado e incidencia',fn()=>same('SC-3002',$filtered->items[0]->code));test('allowlist de orden',fn()=>throws(fn()=>$controller->index(['orden'=>'DROP TABLE'])));
$session=[];$csrf=new SessionCsrfTokenManager($session);$token=$csrf->token();test('CSRF valido',fn()=>ok($csrf->validate($token)));$csrf->rotate();test('CSRF rota token',fn()=>ok(!$csrf->validate($token)));
if(session_status()!==PHP_SESSION_ACTIVE){session_id('ce-web-test');session_start();}$provider=new SessionAuthenticatedActorProvider(['user_id'=>9],'127.0.0.1');test('actor desde sesion',fn()=>same(9,$provider->getActor()->userId));test('actor ausente falla',fn()=>throws(fn()=>(new SessionAuthenticatedActorProvider([]))->getActor()));$context=(new BusinessRequestContextFactory(['REMOTE_ADDR'=>'127.0.0.1','HTTP_X_CORRELATION_ID'=>'CORR-1'],'session-test'))->create();test('request context seguro',function()use($context){same('CORR-1',$context->correlationId);ok(strlen($context->requestId)===32);ok($context->sessionFingerprint!=='session-test');});
$history=(new ScannerHistoryController(new PdoScannerHistoryQuery($pdo),new PdoAuditQueryRepository($pdo),$presenter))->show($two->id);test('expediente carga timeline',fn()=>same(2,count($history->timeline)));test('expediente no incluye secretos',fn()=>ok(!array_key_exists('pin',$history->scanner)&&!array_key_exists('puk',$history->scanner)));test('mapper de errores no filtra SQL',fn()=>same('No fue posible completar la operacion.',(new ControlEscaneresErrorMapper())->message(new RuntimeException('SQLSTATE secret'))));
finish('Web Integration');
