<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
use App\Domain\ControlEscaneres\ScannerCode;use App\DTO\ControlEscaneres\{AuthenticatedActorData,BusinessRequestContext};use App\Exceptions\ControlEscaneres\{DuplicateScannerIdentityException,ScannerRegistrationValidationException};use App\Repositories\ControlEscaneres\Pdo\{PdoAuditRepository,PdoEvidenceRepository,PdoScannerAreaRepository,PdoScannerRepository};use App\Repositories\ControlEscaneres\TransactionManager;use App\Services\ControlEscaneres\Auditoria\ScannerAuditService;use App\Services\ControlEscaneres\Catalogo\ScannerRegistrationService;use App\Services\ControlEscaneres\Evidence\EvidenceFileStorage;use App\Services\ControlEscaneres\Shared\SystemBusinessClock;use App\Support\ControlEscaneres\FlashMessageStore;use App\Validators\ControlEscaneres\ScannerRegistrationValidator;
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec(file_get_contents(__DIR__.'/fixtures/sqlite-schema.sql'));$pdo->exec("INSERT INTO scanner_areas(nombre,activo)VALUES('UTM',1),('INACTIVA',0)");$pdo->exec("INSERT INTO areas_organizacionales(clave,nombre,activo)VALUES('sistemas','Sistemas',1),('inactiva','Inactiva',0)");$activeArea=(new PdoScannerAreaRepository($pdo))->findActiveById(1);$organizationalArea=['id'=>1,'nombre'=>'Sistemas','activo'=>1];$validator=new ScannerRegistrationValidator();$base=['tag'=>' tag-9001 ','brand'=>' Zebra ','model'=>' TC22 ','imei'=>'490154203237518','phone'=>'55 1234-5678','area_id'=>'1','organizational_area_id'=>'1','status'=>'disponible','active'=>'1','observations'=>' Equipo nuevo '];$data=$validator->validate($base,new ScannerCode('SC-9001'),$activeArea,$organizationalArea);
test('normaliza TAG, teléfono y espacios',fn()=>ok($data->tag==='TAG-9001'&&$data->phone==='5512345678'&&$data->brand==='Zebra'));test('áreas separadas y bandera se conservan',fn()=>ok($data->areaId===1&&$data->area==='UTM'&&$data->organizationalAreaId===1&&$data->active));
foreach([['tag',''],['imei','123'],['phone','12'],['area_id','999'],['organizational_area_id','999'],['status','activo'],['active','talvez']]as[$field,$invalid]){test('rechaza '.$field,function()use($validator,$base,$field,$invalid,$activeArea,$organizationalArea){$input=$base;$input[$field]=$invalid;$area=$field==='area_id'?null:$activeArea;$org=$field==='organizational_area_id'?null:$organizationalArea;try{$validator->validate($input,new ScannerCode('SC-9002'),$area,$org);}catch(ScannerRegistrationValidationException$e){ok(isset($e->errors[$field]));return;}throw new RuntimeException('Validación ausente.');});}
test('alta activa exige area organizacional',function()use($validator,$base,$activeArea){$input=$base;$input['organizational_area_id']='';try{$validator->validate($input,new ScannerCode('SC-9002'),$activeArea,null);}catch(ScannerRegistrationValidationException$e){ok(isset($e->errors['organizational_area_id']));return;}throw new RuntimeException('Área ausente aceptada.');});
$storageRoot=sys_get_temp_dir().DIRECTORY_SEPARATOR.'ce-registration-'.bin2hex(random_bytes(4));$repo=new PdoScannerRepository($pdo);$service=new ScannerRegistrationService($repo,new PdoEvidenceRepository($pdo),new EvidenceFileStorage($storageRoot),new TransactionManager($pdo),new ScannerAuditService(new PdoAuditRepository($pdo),new SystemBusinessClock()));$actor=new AuthenticatedActorData(77,'registration-test');$context=new BusinessRequestContext('registration-request','127.0.0.1','registration-session','test');$scanner=$service->register($data,null,$actor,$context);
test('alta inserta exactamente un escáner',fn()=>ok($scanner->id>0&&(int)$pdo->query("SELECT COUNT(*) FROM scanners WHERE tag_original='TAG-9001'")->fetchColumn()===1));test('alta conserva ambas áreas y actor',fn()=>ok((int)$pdo->query('SELECT area_id FROM scanners WHERE id='.$scanner->id)->fetchColumn()===1&&(int)$pdo->query('SELECT area_organizacional_id FROM scanners WHERE id='.$scanner->id)->fetchColumn()===1&&(int)$pdo->query('SELECT created_by FROM scanners WHERE id='.$scanner->id)->fetchColumn()===77));test('alta audita área organizacional',fn()=>ok(str_contains((string)$pdo->query("SELECT valor_nuevo_json FROM auditoria_eventos WHERE accion='scanner.create' AND entidad_id=".$scanner->id)->fetchColumn(),'area_organizacional_id')));
test('TAG duplicado no inserta',function()use($service,$data,$actor,$context,$pdo){$before=(int)$pdo->query('SELECT COUNT(*) FROM scanners')->fetchColumn();try{$service->register($data,null,$actor,$context);}catch(DuplicateScannerIdentityException){same($before,(int)$pdo->query('SELECT COUNT(*) FROM scanners')->fetchColumn());return;}throw new RuntimeException('Duplicado aceptado.');});
$inactive=$base;$inactive['tag']='TAG-9002';$inactive['imei']='';$inactive['active']='0';$inactive['organizational_area_id']='';$inactiveData=$validator->validate($inactive,new ScannerCode('SC-9002'),$activeArea,null);$inactiveScanner=$service->register($inactiveData,null,$actor,$context);test('registro inactivo permite área organizacional pendiente',fn()=>ok((int)$pdo->query('SELECT activo FROM scanners WHERE id='.$inactiveScanner->id)->fetchColumn()===0&&$pdo->query('SELECT area_organizacional_id FROM scanners WHERE id='.$inactiveScanner->id)->fetchColumn()===null));
$session=[];$flash=new FlashMessageStore($session);$flash->keepForm('registrar',['tag'=>'TAG-OLD'],['tag'=>'Duplicado']);$saved=$flash->consumeForm('registrar');test('PRG conserva valores y errores una vez',fn()=>ok($saved['values']['tag']==='TAG-OLD'&&$saved['errors']['tag']==='Duplicado'&&$flash->consumeForm('registrar')===[]));finish('Scanner Registration');
