<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';
function renderComponent(string$name,array$data):string{extract($data,EXTR_SKIP);ob_start();require dirname(__DIR__,2).'/app/Views/components/'.$name.'.php';return(string)ob_get_clean();}
$badge=renderComponent('badge',['badgeStatus'=>'disponible','badgeLabel'=>'Disponible']);test('badge tiene texto accesible',fn()=>ok(str_contains($badge,'Estado:')&&str_contains($badge,'Disponible')));$unsafe=renderComponent('badge',['badgeStatus'=>'"><script>','badgeLabel'=>'<script>alert(1)</script>']);test('badge limita clase arbitraria',fn()=>ok(str_contains($unsafe,'vo-badge--info')&&!str_contains($unsafe,'<script>')));
$alert=renderComponent('alert',['alertType'=>'error','alertMessage'=>'<b>Error</b>']);test('alerta escapa y anuncia',fn()=>ok(str_contains($alert,'role="alert"')&&str_contains($alert,'&lt;b&gt;Error')));$empty=renderComponent('empty-state',['emptyTitle'=>'Sin resultados','emptyDescription'=>'Limpia filtros']);test('empty state orienta recuperacion',fn()=>ok(str_contains($empty,'Sin resultados')&&str_contains($empty,'Limpia filtros')));$pagination=renderComponent('pagination',['paginationPage'=>2,'paginationTotal'=>4,'paginationPrevious'=>'?p=1','paginationNext'=>'?p=3']);test('paginacion semantica',fn()=>ok(str_contains($pagination,'aria-label="Paginación"')&&str_contains($pagination,'rel="next"')));
$field=renderComponent('form-field',['fieldId'=>'codigo','fieldLabel'=>'Código','fieldValue'=>'"><img src=x>','fieldRequired'=>true]);test('campo vincula label y escapa',fn()=>ok(str_contains($field,'for="codigo"')&&str_contains($field,'id="codigo"')&&!str_contains($field,'<img')));
$tokens=file_get_contents(dirname(__DIR__,2).'/public/assets/css/vascor-design-tokens.css');$components=file_get_contents(dirname(__DIR__,2).'/public/assets/css/vascor-components.css');test('tokens centrales completos',fn()=>ok(str_contains($tokens,'--vo-color-primary:')&&str_contains($tokens,'--vo-control-min:')&&str_contains($tokens,'--vo-transition-normal:')));test('foco visible presente',fn()=>ok(str_contains($components,':focus-visible')&&str_contains($components,'outline:3px')));test('movimiento reducido presente',fn()=>ok(str_contains($components,'prefers-reduced-motion')));test('responsive mobile first documentado en CSS',fn()=>ok(str_contains($components,'max-width:767px')&&str_contains($components,'min-height:var(--vo-control-min)')));
$catalog=file_get_contents(dirname(__DIR__,2).'/app/Views/control-escaneres/catalogo.php');test('catalogo usa componentes visuales',fn()=>ok(str_contains($catalog,'vo-page-header')||str_contains($catalog,'components/page-header')));test('catalogo sin datos mock',fn()=>ok(!preg_match('/ESC-00[1-9]/',$catalog)));test('catalogo sin PIN PUK',fn()=>ok(!preg_match('/\b(PIN|PUK)\b/i',$catalog)));test('catalogo conserva filtros',fn()=>ok(str_contains($catalog,'name="estado"')&&str_contains($catalog,'name="incidencia"')&&str_contains($catalog,'Aplicar filtros')));test('HTML base semantico',fn()=>ok(str_contains($catalog,'<table')&&str_contains($catalog,'scope="col"')&&str_contains($catalog,'<label')));
$catalogCss=file_get_contents(dirname(__DIR__,2).'/public/assets/css/control-escaneres/catalogo.css');$moduleCss=file_get_contents(dirname(__DIR__,2).'/public/assets/css/control-escaneres/control-escaneres.css');test('catalogo contiene tabla ancha sin ampliar la pagina',fn()=>ok(str_contains($catalogCss,'.ce-catalog .vo-table-wrap{width:100%;min-width:0}')&&str_contains($components,'.vo-table-wrap{max-width:100%;overflow-x:auto')&&str_contains($moduleCss,'.ce-module,.ce-content{min-width:0}')));test('acciones del catalogo son accesibles en telefono',fn()=>ok(str_contains($catalogCss,'@media(max-width:900px)')&&str_contains($catalogCss,'.ce-catalog__heading .vo-btn{width:100%}')));test('filtros del catalogo responden en tableta',fn()=>ok(str_contains($catalogCss,'@media(max-width:1100px) and (min-width:768px)')&&str_contains($catalogCss,'repeat(2,minmax(0,1fr))')));
$csrf=file_get_contents(dirname(__DIR__,2).'/app/Security/ControlEscaneres/SessionCsrfTokenManager.php');test('CSRF permanece criptografico',fn()=>ok(str_contains($csrf,'random_bytes')&&str_contains($csrf,'hash_equals')));
finish('UX Components');
