<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
use App\Repositories\ControlEscaneres\Pdo\PdoScannerRepository;
use App\Services\ControlEscaneres\Qr\{ScannerQrCodeService,ScannerQrContentNormalizer};
$normalizer=new ScannerQrContentNormalizer();
test('normaliza QR antiguo relativo',fn()=>same(31,$normalizer->normalize(" /index.php?modulo=control-escaneres&seccion=expediente&scanner_id=31\n")['scanner_id']));
test('normaliza URL pública codificada',fn()=>same('scanner:SC-5250',$normalizer->normalize('https://vascor.figurbox.net/index.php?modulo=control-escaneres&accion=resolver-qr&codigo=scanner%3ASC-5250')['identifier']));
test('acepta URL local antigua',fn()=>same(31,$normalizer->normalize('http://localhost/Ferrocheck/public/index.php?modulo=control-escaneres&seccion=expediente&scanner_id=31')['scanner_id']));
test('rechaza URL externa',fn()=>throws(fn()=>$normalizer->normalize('https://evil.example/index.php?scanner_id=31')));
test('rechaza ruta ajena aun en dominio permitido',fn()=>throws(fn()=>$normalizer->normalize('https://vascor.figurbox.net/index.php?modulo=administracion&scanner_id=31')));
test('acepta identificador simple',fn()=>same('sc-5250',$normalizer->normalize(' sc-5250 ')['identifier']));
test('genera URL canónica HTTPS',fn()=>same('https://vascor.figurbox.net/index.php?modulo=control-escaneres&accion=resolver-qr&codigo=scanner%3ASC-5250',ScannerQrContentNormalizer::canonicalUrl('scanner:SC-5250')));
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->exec(file_get_contents(__DIR__.'/fixtures/sqlite-schema.sql'));$insert=$pdo->prepare("INSERT INTO scanners(codigo,codigo_qr,tag_original,imei,numero_serie,marca,modelo,estado,activo)VALUES(:code,:qr,:tag,:imei,:serial,'Zebra','TC22',:status,:active)");
$insert->execute(['code'=>'SC-5250','qr'=>'/index.php?modulo=control-escaneres&seccion=expediente&scanner_id=1','tag'=>'5250','imei'=>'490154203237518','serial'=>'SER-5250','status'=>'disponible','active'=>1]);$insert->execute(['code'=>'SC-5251','qr'=>'scanner:SC-5251','tag'=>'5251','imei'=>'490154203237526','serial'=>'SER-5251','status'=>'entregado','active'=>1]);$insert->execute(['code'=>'SC-5252','qr'=>'scanner:SC-5252','tag'=>'5252','imei'=>'490154203237534','serial'=>'SER-5252','status'=>'pendiente_reparacion','active'=>1]);$pdo->exec("INSERT INTO scanner_movimientos(scanner_id,folio,estado,persona_entrega_nombre,numero_empleado,turno,entregado_at)VALUES(2,'MOV-QR-1','abierto','Persona','E1','A','2026-07-22 05:00:00')");
$repo=new PdoScannerRepository($pdo);
test('resuelve código sin distinguir mayúsculas',fn()=>same(1,$repo->resolveIdentifier('sc-5250')['id']));
test('resuelve scanner_id antiguo',fn()=>same('SC-5250',$repo->resolvePublicId(1)['codigo']));
test('scanner_id inexistente es controlado',fn()=>same(null,$repo->resolvePublicId(999)));
$old=(new ScannerQrCodeService($pdo))->png(1,200);$new=(new ScannerQrCodeService($pdo))->png(2,200);
test('PNG existente conserva contenido antiguo',fn()=>same('/index.php?modulo=control-escaneres&seccion=expediente&scanner_id=1',$old['content']));
test('PNG nuevo contiene URL canónica',fn()=>same('https://vascor.figurbox.net/index.php?modulo=control-escaneres&accion=resolver-qr&codigo=scanner%3ASC-5251',$new['content']));
test('ambos resultados son PNG válidos',fn()=>ok(substr($old['bytes'],0,4)==="\x89PNG"&&substr($new['bytes'],0,4)==="\x89PNG"));
$root=dirname(__DIR__,2);$controller=file_get_contents($root.'/app/Controllers/ControlEscaneres/ControlEscaneresWebController.php');$reader=file_get_contents($root.'/public/assets/js/control-escaneres/qr-scanner.js');$partial=file_get_contents($root.'/app/Views/control-escaneres/partials/equipment-finder.php');$public=file_get_contents($root.'/public/index.php');
test('endpoint resolver QR existe y nunca registra',fn()=>ok(str_contains($controller,"'resolver-qr'")&&!str_contains($controller,'seccion=registrar&scanner_id')));
test('lector evita resolución repetida',fn()=>ok(str_contains($reader,'this.resolving')&&str_contains($reader,'this.lastValue')));
test('lector consulta siempre el backend',fn()=>ok(str_contains($reader,'fetch(url.toString()')&&!str_contains($reader,'window.location.assign(url.href)')));
test('cámara compartida en los tres flujos',fn()=>ok(str_contains($partial,'data-qr-scanner')&&str_contains($partial,'data-equipment-finder')));
test('acceso sin sesión conserva retorno interno',fn()=>ok(str_contains($public,'rawurlencode')&&str_contains($public,'modulo=auth&return=')));
finish('QR Phase 1');
